### ISSUE TITLE
pendingNotificationRequests() does not provide details about the schedule

### ISSUE THREAD

**Issue by drcdev** [MaikuB/flutter_local_notifications#1003]
pendingNotificationRequests() does not provide details about the schedule. Might be a feature request rather than a bug.

**To Reproduce**
Calls to pendingNotificationRequests() return a list of PendingNotificationRequest objects. Which contain the id, title, body, and payload.

**Expected behavior**
PendingNotificationRequest should also include details about the TZDateTime and recurrence pattern submitted when it was originally scheduled.

When managing scheduled notifications in an app where the user has control, should I be tracking those details in the database and linking them with ID? Seems to add complexity not being able to confirm the schedule after it is originally set.

**Comment by MaikuB** [comment]
This has been asked before and isn't there because Android doesn't have APIs to get this information. This is because the notification APIs don't support scheduling. Another set of APIs needs to be used to achieved this. If you have a solution for this then PRs are welcome but you'll likely need to manage this yourself
