### ISSUE TITLE
Schedule a notification and repeat periodically

### ISSUE THREAD

**Issue by Lone-Wolf17** [MaikuB/flutter_local_notifications#1008]
Good day, first of all, thank you for the amazing work, highly and very much appreciated.

Please How does one schedule a notification and repeat it periodically? At the moment, to the best of my knowledge, zonedSchedule(), does not have a parameter for repeating interval. While preroidicallyShow() does not have a DateTime or TzDateTime parameter. 

Hence, one cannot directly (or I don't know how to) set a notification to periodically show and specify the first time it should be displayed. The Docs says " specifying an hourly interval means the first time the notification will be an hour after the method has been called and then every hour after that. " I look at being able to specify the first time the notification is displayed and specify the RepeatInterval after that. 

Please how does one do this? if there is no direct method for it in the plugin, Is there any workaround?

Thank you

**Comment by MaikuB** [comment]
There's a parameter that allows you to specify the components of the date/time to match on for a recurring notification. A similar issue was opened recently at https://github.com/MaikuB/flutter_local_notifications/issues/1007. However, you can't specify the first time it appears as I indicate in the thread due to what's provided by the native notification APIs. You may need to consider using a plugin or native code that periodically runs a generic task

**Comment by Lone-Wolf17** [comment]
Oh Thanks, I understand now. By any chance, you do have any plugin you are using or you recommend ?

**Comment by MaikuB** [comment]
No I don't but I hear others have used https://pub.dev/packages/background_fetch
