### ISSUE TITLE
ongoing feature

### ISSUE THREAD

**Issue by dmrcierhn** [MaikuB/flutter_local_notifications#1018]
I am trying to use the ongoing feature, this feature works when the application is open, but when I end the application, the notification disappears. how can i fix this? my tester is xiaomi mi 9 SE. Thank you!

**Comment by MaikuB** [comment]
If you download/clone the entire repo and run the example app where there's a button to show an ongoing notification, do you see the same problem? Also have you tried running it on a stock Android device/emulator? The reason I ask is to see if perhaps your issue is specific to devices from companies like Xiaomi where they are known to restrict background processes. If so, then there's nothing the plugin can do about it. Some devices supposedly have settings that can be changed but that would be something you'd need to look into as it's specific to these devices

**Comment by dmrcierhn** [comment]
i guess this problem is because of my phone because this feature works in emulator and another real device. thanks for support
