### ISSUE TITLE
Is null safety coming soon?

### ISSUE THREAD

**Issue by josh2112** [MaikuB/flutter_local_notifications#1024]
Thank you so much for this plugin Michael!  I understand you were working on a null-safe upgrade to the plugin as of December 31 but were blocked by some problems upgrading `flutter_local_notifications_platform_interface` as per [this issue](https://github.com/dart-lang/sdk/issues/44575).

Did you ever get that sorted out? Is a null-safe version of the plugin something we can look forward to in the near future?

Thanks!

**Comment by MaikuB** [comment]
Looks like `plugin_platform_interface` has been updated so resolves the issue I had. Null safety migration is a WIP and there's a branch up for that work. If you would to help out as well then that would be much appreciated as all my OSS work is done on spare time

**Comment by matuella** [comment]
Hey @MaikuB I also don't have much of spare time, but I think I can help you with that. I'm not quite sure if I will be able to understand each nook and cranny of the `flutter_local_notifications` plugin, but I will give it a try. Are you already on it (so we don't actually do duplicate work), or can I try to migrate it all?

Also, to migrate it, this plugin references a "non" null-safety version of `flutter_local_notifications_platform_interface`, which is required due to an re-export in `flutter_local_notifications.dart`. Can we have a pre-release of this null-safety version in pub?

**Comment by MaikuB** [comment]
@matuella any assistance is appreciated :)

I've published a pre-release for the platform interface. Plan is to have all null safety migration work go to the `nnbd` branch so if you do a PR, please fork/branch off that one and have PRs go to that branch. This was done so that the default/master branch continues to be used for maintaining the stable versions

**Comment by MaikuB** [comment]
Did some research and it looks like the `integration_test` package hasn't been migrated to null safety as it has been moved to be part the SDK (see https://github.com/flutter/flutter/issues/71379). Unfortunately, that change is only on the dev channel. IMO this isn't ideal as what's been announced is to use null safety on beta and dev is viewed as being less stable than beta

**Comment by MaikuB** [comment]
Have run into another [issue](https://github.com/flutter/flutter/issues/76194) with the `device_info` plugin being used by the example app as it looks like the null safety migration isn't actually complete

**Comment by bsutton** [comment]
@MaikuB device_info has now been migrated.

I'm also keen to see an nnbd release of this project.

**Comment by MaikuB** [comment]
Closing this since 5.0.0-nullsafety.0 has been released.  Haven't made this a stable release to get help from the community on the testing side. Should you find bugs, please open an issue using the bug report template.

**Comment by ErliSoares** [comment]
Any news about the stable version for null safety?
