### ISSUE TITLE
Windows notifications support 

### ISSUE THREAD

**Issue by alionour** [MaikuB/flutter_local_notifications#1028]
Feature required to support windows notifications ,windows 8 and windows 10 allows notifications through windows notifications center , 
![Dismiss-windows-10-notifications](https://user-images.githubusercontent.com/37154676/106949367-80fe2900-6735-11eb-9137-041ecce17e31.jpg)

**Comment by MaikuB** [comment]
There's already an existing issue for desktop support in https://github.com/MaikuB/flutter_local_notifications/issues/746 and I had commented and tagged it to say help is needed for it so if you need this support then the best thing to do is to submit a PR for it. Will closing this since there's already an open issue on this
