### ISSUE TITLE
zonedSchedule time array for each day

### ISSUE THREAD

**Issue by kostyanchikoff** [MaikuB/flutter_local_notifications#1038]
Hey! Tell me how you can implement the withdrawal of data every day with an array of time that comes from the server, I tried to run zonedSchedule through a loop, then only the last one works

**Comment by MaikuB** [comment]
Not clear exactly you're trying to do here. Seems like it's one of two possible things happening here

1. you're scheduling notifications using the same id, which is why only the last one works: if this the issue then you should always use a unique id or
2. you're trying to get data every day and then schedule a notification: this one you'd need to look further into as this should approached from the perspective of how to run a generic job everyday that happens to get data from a server and then schedule notifications. You'd need to look at the available native APIs that can accomplish this. As far as I know, the community is using [this plugin](https://pub.dev/packages/background_fetch) to do so. Worst case, you need to write all of the native code yourself

**Comment by MaikuB** [comment]
Closing since this has been answered and there's been no further reply
