### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by eggnstone** [MaikuB/flutter_local_notifications#1045]
Using version 4.0.1

```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: 
```
caused by
```
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel (Unknown Source:46)
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification (Unknown Source:4)
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification
com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (Unknown Source:76)
```
only seen via Chrashlytics on Galaxy A51 5G with Android 10.

**Comment by MaikuB** [comment]
For bug reports, these need to include link to a minimal app that can reproduce the problem. From what I've seen, issues like this have been due to not completing everything required as part of doing release build configuration and addressing this issue won't retroactively fix this as you would still have corrupt notification data that was saved for existing notifications

**Comment by eggnstone** [comment]
Unfortunately I cannot reproduce it and only see it via Crashlytics.

> issues like this have been due to not completing everything required as part of doing release build configuration

I'm not sure I fully understand this but the app has been released for almost 2 years now and works well for the vast majority.

> addressing this issue won't retroactively fix this as you would still have corrupt notification data that was saved for existing notifications

That might be the case (that corrupt notification data is saved).
But couldn't the plugin handle it more gracefully, log a warning, and ignore the notification, instead of crashing?

**Comment by ritheshSalyan** [comment]
I got the same issue while sending notification.

here is my code.

```dart

  Future<void> _showPublicNotification(String title,String message) async {
    final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
            'local_notification_id', 'local_notification_Name', 'Local Notification',
            importance: Importance.max,
            priority: Priority.high,
            ticker: 'ticker',
            visibility: NotificationVisibility.public);

    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);

    await flutterLocalNotificationsPlugin.show(0, title,
        message, platformChannelSpecifics,
       );
  }
```
My android version Is 10

**Comment by ritheshSalyan** [comment]
cleared this issue. I had some initialization problem

**Comment by MaikuB** [comment]
> But couldn't the plugin handle it more gracefully, log a warning, and ignore the notification, instead of crashing?

If that is your preference then IMO that's one you'd need to adopt in your own fork. Making this change removes one way of knowing that there's issue and from what I know, limits this to only seeing the error via Logcat. Some developers may not know about how to use it and it wouldn't be possible to rely on it if a build is distributed to users. Keeping the current behaviour at it likes allows some form of remote logging/crash reporting

**Comment by eggnstone** [comment]
>Making this change removes one way of knowing that there's issue and from what I know, limits this to only seeing the error via Logcat.

That's true!
What about wrapping it in FlutterLocalNotificationException and providing more info that way?
Currently I cannot see which notification caused the issue because it is triggered via the ScheduledNotificationReceiver.
E.g. specifying the notification channel details?

**Comment by MaikuB** [comment]
The corrupt notification data means the deserialised notification is actually null. This is why there are others that say [this PR](https://github.com/MaikuB/flutter_local_notifications/pull/975) works for them when what it actually does is to ignore a null notification as there were already null checks around the channel properties. There isn't any more information that can be provided. Furthermore, it's not a matter on which notification causes the issue but a configuration issue within the app. The only options here IMO are that you either ignore these because the app was misconfigured at one point in time or have fork where you do something similar to ignore these null notifications so you don't see these reports anymore

**Comment by eggnstone** [comment]
Thanks for the detailed explanation!
Closing the bug then ...
