### ISSUE TITLE
OnLaunch method not triggering 

### ISSUE THREAD

**Issue by sachin052** [MaikuB/flutter_local_notifications#1050]
I've integrated local_push_notification with flutter apns package, But whenever i started using your major upgrade of 4.0.0, It's stop working and if i rollback to 3.0.0 it's working fine.

` static configurePush() {
    _connector.configure(
        onLaunch: _onLaunch,
        onResume: _onResume,
        onMessage: _onMessage,
        onBackgroundMessage: _onMyBackground);
    _connector.requestNotificationPermissions();
    _connector.token.addListener(() {
      print("token is${_connector.token.value}");
      if (localDataSource == null) localDataSource = getIt<LocalDataSource>();
      localDataSource.savePushToken(_connector.token.value);
    });
    _initLocalNotification();
  }
static Future<void> _onLaunch(Map<String, dynamic> message) async {
    print("on Launch");
    _navigateToScreen(jsonEncode(message));
  }
`

**Comment by MaikuB** [comment]
Whilst you mention using one of this plugin works and another one doesn't, that doesn't necessarily mean the issue is with this plugin. The only significant change within the plugin in 4.0 was that tapping on a local notification from `flutter_local_notifications` won't trigger the callback exposed by this plugin. This change was specific to this plugin and was only tied to calling the `initialize()` method. 

Furthermore, the `flutter_apns` has open issues on callbacks not being called. There's even an open PR (https://github.com/mwaylabs/flutter-apns/pull/43/files) around fixing `onLaunch` as `onLaunch` would not be called when if you tap on a notification when the app isn't running. The logic has been incorrectly placed in detecting when the app was in the background and goes back to the foreground. You'd need to raise the issue on the GitHub repo for `flutter_apns` as the issue is to do with that plugin
