### ISSUE TITLE
Undefined name 'platform'. 

### ISSUE THREAD

**Issue by osamasado** [MaikuB/flutter_local_notifications#1057]
I 'm trying to use this package, but i have one problem with this line :

` final String timeZoneName = await platform.invokeMethod('getTimeZoneName');`

Undefined name 'platform'.

can you help me to solve this issue?

**Comment by MaikuB** [comment]
You need to trace through the code in the example app more to see where it's defined and read up more on platform channels. More information on platform channels is available in the official docs [here](https://flutter.dev/docs/development/platform-integration/platform-channels). I've also made note of this in the readme at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification

The other part of that section you should refer to that I wrote is

> The timezone package doesn't provide a way to obtain the current time zone on the device so developers will need to use platform channels (which is what the example app does) or use other packages that may be able to provide the information (e.g. flutter_native_timezone).

This is mentioned as the particularly line of code is use to get the timezone that has been set for the device. If you're still struggling with platform channels after going through the docs then I suggest to reach out to others on Slack, Discord etc or make use of the [`flutter_native_timezone`](https://pub.dev/packages/flutter_native_timezone) plugin. The reason why the example doesn't use it is because said plugin doesn't support macOS.
