### ISSUE TITLE
dependency issue with plugin_platform_interface (with ^4.0.1+2)

### ISSUE THREAD

**Issue by samlotti** [MaikuB/flutter_local_notifications#1076]
**Describe the bug**
Updating to ^4.0.1+2, that fixes the plugin_platform_interface version issue, still gets the issue because
flutter_local_notifications_platform_interface also depends on plugin_platform_interface ^1.0.2

**Message**
Because flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 depends on flutter_local_notifications_platform_interface ^2.0.0+1 which depends on plugin_platform_interface ^1.0.2, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 requires plugin_platform_interface ^1.0.2.
And because firebase_messaging >=9.0.0 depends on firebase_messaging_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 is incompatible with firebase_messaging >=9.0.0.

**To Reproduce**
In pubspec.yaml, include the dependecies:
  flutter_local_notifications: ^4.0.1+2
  firebase_messaging: ^9.0.0
run: flutter pub get

**Expected behavior**
should be able to resolve dependencies

**Sample code to reproduce the problem**
n/a

**Comment by Mighty683** [comment]
I have the same issue with flutter_local_notifications version 4.0.1 I am not able to use both firebase and flutter_local_notifications because of this dependency update issue.

**Comment by namansoni** [comment]
I am getting the same problem
                     
Because no versions of firebase_messaging match >9.0.0 <10.0.0 and firebase_messaging 9.0.0 depends on firebase_core_platform_interface ^4.0.0, firebase_messaging ^9.0.0 requires firebase_core_platform_interface ^4.0.0.

And because no versions of firebase_core_platform_interface match >4.0.0 <5.0.0 and firebase_core_platform_interface 4.0.0 depends on plugin_platform_interface ^2.0.0, firebase_messaging ^9.0.0 requires plugin_platform_interface ^2.0.0.

And because flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0 depends on flutter_local_notifications_platform_interface ^2.0.0+1 which depends on plugin_platform_interface ^1.0.2, firebase_messaging ^9.0.0 is incompatible with flutter_local_notifications >=3.0.1+4 <5.0.0-nullsafety.0.

**Comment by MaikuB** [comment]
> Updating to ^4.0.1+2, that fixes the plugin_platform_interface version issue...

There were no changes on that in 4.0.1+2

Regarding the issue on dependencies, this has was previously discussed in [here](https://github.com/MaikuB/flutter_local_notifications/pull/1074#issuecomment-792182724) as it all relates to null safety. So the options here are you either use the null safety prerelease of this plugin or do a dependency override for `plugin_platform_issue` like the example app for `firebase_messaging` https://github.com/FirebaseExtended/flutterfire/blob/8068ff9083ad8c8671f08e1631a21afe558dc1ce/packages/firebase_messaging/firebase_messaging/example/pubspec.yaml#L32

**Comment by samlotti** [comment]
Sorry, I thought yesterdays merge included that open pr.   Changing my dependency to 

flutter_local_notifications: ^5.0.0-nullsafety.0

resolved the issue.
