### ISSUE TITLE
Issues with background notifications when app is restarted

### ISSUE THREAD

**Issue by mrdc** [MaikuB/flutter_local_notifications#1093]
Hi,

I'm experiencing a bug: background notifications don't work after mobile app is restarted.
I was able to reproduce the issue many times.

iOS 14.4
Flutter 2.0
flutter_local_notifications 4.0.1+2

**To Reproduce**
1. Create a mobile app with flutter_local_notifications which is capable to send notifications when it receives data from backend.
2. Build it in Release mode (Xcode 12.3 in my case)
3. Mobile app launches - check if it receives local push notifications
4. Bring the mob app to background - don't close Xcode* or mobile app
*you can force quit Xcode to prevent the mob app from termination
5. Lock the phone 
6. Local push notifications are shown without any issues
7. Local push notifications still work a few minutes later
8. Close the mob app via App switcher
9. Open it
10. Local push notifications work when the app is in foreground
11. Put mob app to background 
12. No local push notifications are shown (in unlocked or locked phone state)
13. Bring the mobile app to foreground 
14. The last notification is shown when app goes from background to foreground (but no notifications in Notification center)
15. BTW Regular push notifications work flawlessly for this mob app (the same build, no changes in code): when it's relaunched, in background, etc - so it's properly configured in Xcode for push notifications.

**Expected behavior**
Local background notifications should work after mobile app close/open cycle.

Can be related to this issue:
https://github.com/MaikuB/flutter_local_notifications/issues/1069

**Comment by MaikuB** [comment]
Local notifications and push notifications are different things. Push notifications refer to remote notifications sent from a server. If you're using these e.g. via `firebase_messaging` then you'd need to check your app to see if it's configured properly. It would also be an issue outside of this plugin. Given you mentioned you mentioned you had to change some settings in XCode before, it sounds like you are using push notifications as the use of local notifications doesn't need any such settings to be configured.

If your issue is *only* relates to this plugin (i.e. you're only using local notifications) then I'd a need a minimal app that can reproduce the problem.

**Comment by mrdc** [comment]
> If you're using these e.g. via `firebase_messaging` then you'd need to check your app to see if it's configured properly.

I use apple apns directly - without `firebase_messaging`

> If your issue is _only_ relates to this plugin (i.e. you're only using local notifications) then I'd a need a minimal app that can reproduce the problem.

Ok, I'll prepare a sample app.

**Comment by MaikuB** [comment]
> I use apple apns directly - without firebase_messaging

firebase_messaging was just an example. I mention this to make sure you've actually pinpointed where the issue lies. With the scenario you've described, if the issue was to do with this plugin then that would mean that after scheduling a notification (via `zoneScheduled`, it won't appear if the app is closed. This could be reproduced by using the example app. You should see that this is working as expected so the issue lies elsewhere. If you're trying to use apns via another plugin together with this one then you should be looking at the plugin that you're using.

> In case I remove regular push notifications and leave flutter_local_notifications and still have the same issue when app is closed and then relaunched - isn't it the issue with the plugin? Or it's some internal issues in iOS?

Did you remove all references to the code that was needed to implement push notifications including the removal of it being referenced in pubspec.yaml and any of the associated setup code though? As I mentioned earlier, the example in the repo could be used to reproduce the problem. No one has reported any issues to do with notifications not appearing in the background on iOS either. It is typically reported on Android because some manufacturers restrict processes from running in the background. Notifications on iOS will always appear unless you have some kind of issue in your app.

**Comment by mrdc** [comment]
> If you're trying to use apns via another plugin together with this one then you should be looking at the plugin that you're using.

I've started to use `flutter_local_notifications` prior to any other notifications plugins. And there was the issue: no background notifications in my case after I close the app via app switcher and open it again. After that I've tried regular push notifications just to be sure that my mob app is properly configured to receive notifications while in background.

> Did you remove all references to the code that was needed to implement push notifications including the removal of it being referenced in pubspec.yaml and any of the associated setup code though?
Yes, I've triple checked everything.

> after scheduling a notification via `zoneScheduled`
I don't use any scheduling in my case. Just this code:

```dart
...
final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

Future<void> _showNotificationWithNoBadge(String title, String body) async {
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'no badge channel', 'no badge name', 'no badge description',
      channelShowBadge: false,
      importance: Importance.Max,
      priority: Priority.High,
      onlyAlertOnce: true);
  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics = NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin
      .show(0, title, body, platformChannelSpecifics, payload: 'item x');
}

void _initNotifications() async {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      new FlutterLocalNotificationsPlugin();
  var initializationSettingsAndroid =
      new AndroidInitializationSettings('app_icon');
  var initializationSettingsIOS = new IOSInitializationSettings(
    defaultPresentAlert: true,
  );
  var initializationSettings = new InitializationSettings(
      initializationSettingsAndroid, initializationSettingsIOS);
  flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: onSelectNotification);
}

```

in `MyApp` I do:
```dart
void initState() {
    super.initState();
    _initNotifications();
}
```
and then, when my mobile app receives data, this:
```
showNotificationWithNoBadge('Alert', 'message');
```
What's strange - in iOS Simulator local notifications DO continue to work in background after I close and then open the app. It can be somehow related to debug build which is used for Simulator or some internal differences in Simulator itself compared to real devices.
Honestly, no more ideas why local notifications stop to work in background after I close and then open the app on real iOS devices...

**Comment by MaikuB** [comment]
> I don't use any scheduling in my case. Just this code:

Whether or not you use scheduling isn't relevant. The point was that a notification would still appear so your issue lies elsewhere.

Currently nothing you have provided indicates an issue is with the plugin.

**Comment by mrdc** [comment]
> Currently nothing you have provided indicates an issue is with the plugin.

Then it looks like iOS internal behavior. Will investigate further. Closing the issue now.

**Comment by mrdc** [comment]
@MaikuB 

BTW, `flutter_local_notifications` version in pubspec was `^0.8.1`, so maybe it was somehow outdated, because when I've updated in to the latest version, it required me to make some changes:
before:
```dart
  importance: Importance.Max,
      priority: Priority.High,
var platformChannelSpecifics = NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

var initializationSettings = new InitializationSettings(initializationSettingsIOS, initializationSettingsAndroid);

```

**after:**
```dart
importance: Importance.max,
      priority: Priority.high,
      onlyAlertOnce: true);
  var platformChannelSpecifics = NotificationDetails(
      iOS: iOSPlatformChannelSpecifics,
      android: androidPlatformChannelSpecifics);

var initializationSettings = new InitializationSettings(
      iOS: initializationSettingsIOS, android: initializationSettingsAndroid);

```
The same bug with background, plus new bug: notifications are fired twice for single call `_showNotificationWithNoBadge`

**Comment by MaikuB** [comment]
That you get notifications twice now, sounds like there's even more like an issue with your own app that you need to track down.  There's still no evidence of a bug with the plugin. If a single call to the plugin would trigger a notification twice then that would be easily reproducible and there's the example app in the repo that acts as a minimal case for testing functionality. No one has ever mentioned getting notifications appear twice.

Also, you linked to another related issue but I hope actually read and understood this particular [post](https://github.com/MaikuB/flutter_local_notifications/issues/1069#issuecomment-791798424) as the OS may actually stop applications from continuing to run when they're in the background

**Comment by mrdc** [comment]
> That you get notifications twice now, sounds like there's even more like an issue with your own app that you need to track down.

Yes, it was caused by other plugin update which brought this behavior. Rule 1: don't update a lot at once :)


> Also, you linked to another related issue but I hope actually read and understood this particular [post](https://github.com/MaikuB/flutter_local_notifications/issues/1069#issuecomment-791798424) as the OS may actually stop applications from continuing to run when they're in the background

My point about this issue is based on observation that local notifications in my app depend on how the app was started: from Xcode or not. Xcode can force background to work when app is launched via Xcode. This behavior is verified many times and it's reproducible with 100% accuracy. Roots are not yet known. 
I'll update when I find out why it happens.

**Comment by MaikuB** [comment]
My understanding of what you described goes back to the post I had tried to highlight where the scenario is exactly the same. I had mentioned in that thread that when an app is run via debug session, this could prevent the  OS from suspending the app whilst it's in the background. In this case, it sounds like you just did via XCode but same thing applies. For a mobile application that is running in real-world scenarios (i.e. not launched by a debug session), when an application goes into the background, the OS can suspend the app (see https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle). This means even though the app is in the background no code will be executed. If you don't see a notification, it's because none of the code is running to even call the method to show a notification.

I'm mentioning this again as I'm concerned you may not be understanding this and could end spending a lot of time looking into something that isn't to do with plugin and should instead look at how you can update your app to handle background scenarios

**Comment by mrdc** [comment]
>  For a mobile application that is running in real-world scenarios (i.e. not launched by a debug session), when an application goes into the background, the OS can suspend the app (see https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle). This means even though the app is in the background no code will be executed. If you don't see a notification, it's because none of the code is running to even call the method to show a notification.

Thanks, I understand that it's iOS related behavior. It was a surprise that iOS Simulator has different behavior compared to real devices as it makes debugging harder.

**Comment by MaikuB** [comment]
Based on what I said and read, it's not to do with the simulator. The key part is to how there's a debug session running, if you stopped debugging and launched the app via the home screen then you I believe you should see the same behaviour
