### ISSUE TITLE
Documentation. Getting started.

### ISSUE THREAD

**Issue by willhaslett** [MaikuB/flutter_local_notifications#1105]
This is clearly the best available package for local notifications in Flutter. However, it seems worth requesting improved documentation for getting started. The extensive narrative content in the README and the 1,767-line `main.dart` file don't leave the reader with a clear path to getting a minimal implementation going with this plugin after getting settings configured.

There is the code snippet under "initialisation", but that contains two undeclared variables, `onDidRecieveLocalNotification` and `selectNotification`, which are clearly function names, but one is left to realize that this code is broken as presented.

There are many great examples of simple get-started documentation, such as https://pub.dev/packages/location.  If that's apples-to-oranges because what this package does is more complex, the documentation for Moor and for Riverpod offer good examples of how to offer thorough documentation that is still friendly.

**Comment by MaikuB** [comment]
There's a lot more involved when dealing with notifications as it's fairly complicated area with the knowledge needed and setup involved. One of the react native libraries for local notifications requires paying for a licence to even use it.

The example app is large because it covers every single feature in the app so provides a reference for developers to use. I've no plans to reduce the example to say, a minimal app, that only displays a basic notification, as more usage questions would likely show up on the repository.

Regarding `onDidRecieveLocalNotification`, the issue there is I had referred to it further in the iOS app that could be fixed. `selectNotification` on other hand, was defined within the same initialisation section.

As this is an open-source project, if you'd like to see the documentation improved then you could help contribute in doing so. Doing an overhaul of the docs is not something I plan to on my unless the community helps out. I only work on this in my spare time and have yet had the opportunity to use this plugin in the apps I've worked on even
