### ISSUE TITLE
Please make the process of using this package simpler and easier for beginners 

### ISSUE THREAD

**Issue by fisforfaheem** [MaikuB/flutter_local_notifications#1116]
A simple beginner flutter dev  has no idea how to use this, please make it easier for them, also make the setup automatic..no ne should go to android or ios settings to change.. Please see this isue also check the GETX package and see how much simpler they make things to be done you can do that too please do

**Comment by JobMoll** [comment]
Hey,

So i didn't make this package but i can explain in very short why the setup is a little more then for example GetX.
For push notifications packages like this one, for firebase_messaging and for onesignal (for example) you have to do some native adjustments since they need extra permissions. 
GetX is just a dart package which doesn't need anymore native permissions from the device. (that's why it's so easy to implement).

There are more then enough tutorials online which explain how to use Xcode and how to edit the android manifests.

Regards, Job

**Comment by MaikuB** [comment]
Closing since this @JobMoll has provided an explanation and thanks for helping to respond too

**Comment by fisforfaheem** [comment]
Thanks for explaining, but when it comes to windows linux and mac os..and
web it becomes a bit harder for everyone
