### ISSUE TITLE
Most efficient way to implement yearly notifications?

### ISSUE THREAD

**Issue by musiolmarco** [MaikuB/flutter_local_notifications#1119]
Hello there, first of all I wanted to thank you for your work and for this package, that makes notifications really easy using Flutter!

But I have a question now: I've created a birthday manager app in the last week and I am wondering, if I could increase the efficiency of my app in view of the notifications. 

My problem is, that I want to show a notification every year a user have birthday. I already informed myself and I am aware that there is no yearly notification in this package, so I solved it my self and everytime the birthdays are loaded, I am deleting all birthday notifications and adding new ones for each next birthday. 
I wonder, if it's degrading the performance of the app, because it's doing it everytime the birthdays are loaded and of course there could be above 50 birthdays everytime that are loaded. The second problem is, that if someone does not open the app once a year, the notification will only show up the next birthday and not the birthday after that. 

My question is, is this the most efficient way to implement it and how am I solving the problem with the birthdays after? Is it a good idea to just get the next 10 birthdays for example and all scheduling them or what do you guys think?

_Thanks for the answers in advance._

**Comment by MaikuB** [comment]
To be honest, I don't know as I'm not an expert when it comes to performance. I would guess it should be fine but iOS does impose a limit on the number of notifications.

I would say the best way to solve this would be to look into trying implementing the notifications yourself with native code (i.e. Kotlin/Java for Android side and Objective-C/Swift for iOS). I believe it'd be doable but up to your application to determine what should happen for edge cases (e.g. what happens if a birthday falls on 29th of February). Other thing is to see if https://pub.dev/packages/device_calendar can be used instead

**Comment by musiolmarco** [comment]
Okay thanks for your advice!
