### ISSUE TITLE
MIUI permissions for sound and floating notifications

### ISSUE THREAD

**Issue by PoeMcMoe** [MaikuB/flutter_local_notifications#1129]
**Describe the bug**

When a notification fires in my Redmi Note 7 which uses MIUI 12.0.3 there is no sound and floating notification. The permissions must given from app settings and I couldn't find any way to do that programatically in the docs. 

**To Reproduce**

Schedule a notification with sound on an android device with MIUI 12.0.3 (have not tested with other versions, saw people having problems with miui 11 also https://stackoverflow.com/questions/64335979/flutter-flutter-local-notification-sound-didnt-play-on-miui-11-0-1).

**Expected behavior**

A floating notification with sound fired.

**Comment by MaikuB** [comment]
This is an issue specific to those devices since it's a customised version of Android. There's no way to programmatically enable this as a result. In other words, there's nothing the plugin can do to address. This appears to be a common issue on such devices so I would guess that users are accustomed to needing to change their settings. You can see that this product also documents the limitations on such devices https://threema.ch/en/faq/notification_channels_xiaomi and you may need to do so as well for your app

**Comment by faizm55212** [comment]
When creating a channel using [awesome_notification](https://pub.dev/packages/awesome_notifications) plugin, floating notification gets enabled, on `high_importance_channel`
but can't recieve fcm background notification to that channel as maybe they don't have specified a **id** while creating the channel.

```
NotificationChannel(
  channelKey: 'high_importance_channel',
  channelName: 'high_importance_channel',
  channelDescription: 'High_importance_channel',
  ledColor: Colors.white,
  defaultColor: Colors.white,
  enableVibration: true,
  playSound: true,
  enableLights: true,
  importance: NotificationImportance.High,
);
```
Maybe this will help you developers to get to a solution.

Thanks
