### ISSUE TITLE
Will the ios plug-in work correctly if we had planned notifications with attachments, but the image file was deleted?

### ISSUE THREAD

**Issue by otopba** [MaikuB/flutter_local_notifications#1167]
Will the ios plug-in work correctly if we had planned notifications with attachments, but the image file was deleted?

![image](https://user-images.githubusercontent.com/4225279/118396158-d7450700-b656-11eb-9fc8-3449b619726b.png)

**Comment by MaikuB** [comment]
I believe so as the way the iOS notification APIs work when the app is in the foreground is that there's a callback to handle if the notification should be shown (https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc). Note though that your question is more on how these APIs work as opposed to the how the plugin works so I'd suggest asking on a forum/chat server with iOS devs. 

Though, given your stack trace has still has details on the Dart calls, it looks more like the issue is occurring right when your app tries to schedule a notification as opposed to when the notification was expected to appear
