### ISSUE TITLE
Schedule local notification with a string as id instead of an integer.

### ISSUE THREAD

**Issue by Hasankanso** [MaikuB/flutter_local_notifications#1169]
Hello, 
I have a string id, which is provided from the database. I would like to use it to store a `localNotification`, any idea how to accomplish that? if not is there any other way to fetch a `localNotification` using another property beside id?

for instance I'm using this method:
`FlutterLocalNotificationsPlugin().zonedSchedule(id..)`

**Comment by MaikuB** [comment]
Android does allow an optional string tag as well so you can refer to the Android docs for more info as the plugin in the end is wrapper for accessing the platform's native APIs.

If you're only using integer IDs then you would need to do your own mapping between integer IDs (e.g. something unique your app would need to generate) and string so that would be for you to design and manage for your application. If you need help on this then as this is a general programming question that is better asked on sites like Stack Overflow.
