### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)

### ISSUE THREAD

**Issue by Worien** [MaikuB/flutter_local_notifications#1170]
Getting MissingPluginException in the background, when app is in the foreground - it is work perfectly. Previously, I had a possibility to register plugin manually, with registerWith method to avoid this error, how can I avoid it now? 

More details here:
https://stackoverflow.com/questions/67582684/unhandled-exception-missingpluginexceptionno-implementation-found-for-method-s

**Comment by MaikuB** [comment]
The warning shown in your Stack Overflow post would imply there's an issue with your application. The plugin registrant is supposed to automatically register all the plugins but seems to be missing. As it's missing, the plugin isn't registered so Flutter can't find it. It's not a problem specific to the plugin so not something I can actually help with nor do I know how the issue came to be with your application. If your app used another plugin in the background, it would also run into a similar issue.

Closing this as it's not specific to the plugin and not something I can help with.

**Comment by Worien** [comment]
In v2 Embedding all plugins should be registered automatically. Also, I have an issue in the background only with local_notifications plugin, for example, firebase_messaging works in the background, so it could be an issue with local_notifications and v2 embedding.
