### ISSUE TITLE
Feature clarification: Full-screen intent / AppLaunchDetails

### ISSUE THREAD

**Issue by mk-dev-1** [MaikuB/flutter_local_notifications#1190]
Good Morning,

the readme states

_Note that when a full-screen intent notification actually occurs (as opposed to a heads-up notification that the system may decide should occur), the plugin will act as though the user has tapped on a notification so handle `those the same way (e.g. onSelectNotification callback) to display the appropriate page for your application._

May I ask, is there a way to identify whether the app was launched via fullscreen intent or via a normal notification? My use case is that the user will tap a notification to access a form, however showing the form on fullscreen intent is rather disturbing as the user would expect a fullscreen **notification** rather than seeing the form immediately.

Thanks for clarifying.

**Comment by MaikuB** [comment]
There's no way to identify via the plugin and I'm not sure if it's even possible to do so. Note that a full-screen intent isn't a full-screen notification. With a full-screen intent, your app is suppose to decide what it should present on the screen. Your app should also know what it's decided to make a full-screen intent since you would've specified that in the code. In which case, you could try to make use of the payload to help identify, which notification was specified to result in a full-screen intent and it should do the same thing, regardless of if the user tapped on a notification or if the app presented a page automatically

**Comment by MaikuB** [comment]
Closing since this has been answered
