### ISSUE TITLE
Foreground Service on Android

### ISSUE THREAD

**Issue by bagintz** [MaikuB/flutter_local_notifications#1193]
Can this library be used in conjunction with a foreground service as talked about here:

https://developer.android.com/guide/topics/ui/notifiers/notifications#foreground-service

**Comment by MaikuB** [comment]
Based on limited knowledge of how foreground services work, I believe answer is no or at least it's better not to. My understanding is you would've needed to have written some native Android code in Java or Kotlin so that there's a service to begin with. In which case, you're already on the native platform side that you should be writing the code to show a notification in the same language. Using the plugin here wouldn't make much sense as its main use is to act as a bridge of sorts to call the platform's notification APIs

**Comment by bagintz** [comment]
That makes sense, thank you!
