### ISSUE TITLE
Scheduled notifications does not show untill app not in foreground

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MaikuB/flutter_local_notifications#1197]
Hi, I am on 5.0.0+3 version.

I am sheduling notifications. If i keep app open in foreground everything works fine. If I leave app with screen turned off local scheduled notifications do not appear untill I open app. After app is opened i receive all notifications that should have been 
shown in the past.

Most interesting part that sometimes notifications shows as expected.

This behaviour is noticed on:
Samsung Galaxy 7
Xiaomi Mi10

Anu ideas?

**Comment by MaikuB** [comment]
Android devices have battery optimisation features that can affect the timing of when scheduled work happens. Some OEMs are more stricter on implementing this. I would suspect your app is being impacted by that. There's nothing further the plugin can do since its calling native APIs though the`androidAllowWhileIdle` parameter allows for exact timings when set to true. Even then, some manufacturers have policies in place that prevent any background work to happen when the app isn't running. This is why this section of the readme exists https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications

**Comment by vytautas-pranskunas-** [comment]
Thanks 😊
