### ISSUE TITLE
firebase_messaging conflict

### ISSUE THREAD

**Issue by tudor07** [MaikuB/flutter_local_notifications#120]
> NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging) as they will most likely do the same and it's only possible to register a single delegate.

Is this still valid ?
It seems to work for me, both Firebase and local notifications.

**Comment by MaikuB** [comment]
See #111

**Comment by tudor07** [comment]
I saw that issue. This is my question. That issue says it doesn't work, but for me it works. I asked if that issue is still valid in the latest versions ? @MaikuB

**Comment by MaikuB** [comment]
Sorry I should clarify that I was trying to point to the fact that there is already an issue discussing this topic. As such the question would belong better in there. If you're saying it works then it would worth letting others know to what extent you've seen it work e.g. do all of the callbacks for both plugins work for you. For example, does both the `onMessage` callback in the firebase messaging plugin and `selectNotification` callback in this plugin work for you for you on iOS. I believe this still doesn't work properly given how delegates work (at least my understanding of it) and there are others that still seem run into the same problem given the recent activity in #111

**Comment by tudor07** [comment]
Ok, I see. I have another question before continuing.
How do you know that firebase_messaging registers any delegate ?
Judging by the code, I don't see it registering a delegate anywhere (code: https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m )

**Comment by MaikuB** [comment]
Using the delegate is required in order to handle any kind of notification-related behaviour on iOS (see https://developer.apple.com/documentation/usernotifications/unusernotificationcenter). The code you're looking at is for the Dart package but bear in mind that on the iOS side so you won't see the code there as it has a dependency of the iOS firebase messaging library. That has some logic on the delegate (e.g. https://github.com/firebase/firebase-ios-sdk/blob/954e4d5df13b14aee9c1112db67a23729d12acfd/Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m)

Perhaps you're right now that it does work but as I mentioned earlier, there still seem to be reports of it not working and I've logged on issue to the main Flutter on how to make it easier. I don't have a firebase subscription myself to check this so have been relying on the community's reports. I use to be able to run the firebase_messaging example on Flutter but had issues recently with running it.

Either way, I would encourage you to continue the discussion in #111

**Comment by tudor07** [comment]
Yes, you are right, I see now, Let's continue discussion in #111, closing this as duplicate of that
