### ISSUE TITLE
How to increase duration of the sound

### ISSUE THREAD

**Issue by Shashwat2708** [MaikuB/flutter_local_notifications#1217]
I have 3 questions and please help me with these-
1. I want to add a 10 minute sound on the notification. How can I play the entire sound. 
2. I was able to hear the default notification on the emulator but it wasn't audible on my phone. How to fix this🤔
3. Also, I added the logo image which is supposed to appear but it wasn't and instead flutter logo was appearing. I have checked the path thrice and it still is showing flutter logo instead of my logo. How to fix this? 

Please help me with this🙏

**Comment by Shashwat2708** [comment]
@MaikuB I know you must be very busy but your help is really needed. Please help.

**Comment by MaikuB** [comment]
1. Not possible as far as I know. If it is, then you would you need to research what APIs are available on the Android side to do what you're after
2. This is something you would need to investigate. It might be possible you have a phone that requires changing the settings for the sound to be enabled or you haven't realised that you have actually muted notification sounds as the media volume settings is separate from the ringer settings that determines if a sound occurs when you get a notification and if you will hear your ring tone when receiving a phone
3. There's most likely an issue with your configuration and something you would need to investigate further as well. You can make use of the example app and refer to the official Android documentation. As the plugin is a wrapper for a platform's native APIs so you are still required to know how each platform works as it dictates what features are available

A reminder that I had mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/1209 that I don't provide direct assistance with each person's use case so if you are in need of help then the place you should look to get helps are places like Stack Overflow. With the limited time I have and since I don't even use the plugin, I only look at bugs and potential feature requests.
