### ISSUE TITLE
[iOS Foreground-Notifications] Customize notifications

### ISSUE THREAD

**Issue by Babwenbiber** [MaikuB/flutter_local_notifications#1291]
I know, that since iOS 10+ the notifications are not getting shown by default if the app is in foreground.
However, the options state:

> The default settings of the plugin will configure these such that a notification will be displayed when the app is in the foreground.

I haven't received a notification when the app is in foreground. 
Furthermore, the doc says, that one can customize the notifications by the presentation options. For me this is not a real customization. 
**Real world scenario:**
You have a chat app. You want your users to get local notifications when someone writes you. But you DON'T want to have a local message when your are currently chatting with the person (e.g. routeName is X and globalVarCurrentChatPartner is Y).

I haven't figured out how to apply this scenario to this package. I currently use firebase_messenging and for Android this was quite simple to implement.

If this is possible with this package, I am sorry, but I couldn't find out how to apply it from the docs and the (way to monolithic) example.

Cheers

**Comment by MaikuB** [comment]
Based on what you described, I'd say the scenario you described has more to do with push/remote notifications than local notifications. Local notifications are used in response to something happening on the local device where something should be shown immediately or scheduled to be shown based on time. This is different from chat scenarios and the reason why you're probably struggling (e.g. haven't seen a notification in the foreground) is you haven't been able to differentiate between push/remote notifications and local notifications. I'd suggest you read more into FCM as it sounds like you might be confusing what is being done by this plugin with what `firebase_messaging` is doing. For example, if you read the docs for it at https://firebase.flutter.dev/docs/messaging/usage, you'll see that it says no visible notification will be shown unless some configuration is done.

If you are really using both plugins together that this plugin is the one displaying the notifications then it's up to you implement the logic so that it only displays a notification when it should do when `firebase_messaging`'s `onMessage` is triggered

**Comment by Babwenbiber** [comment]
Thanks for clarifying!
