### ISSUE TITLE
AndroidManifest receiver and service usage

### ISSUE THREAD

**Issue by zakblacki** [MaikuB/flutter_local_notifications#1325]
So I've been trying to figure the how and when and why I'm getting theses error when calling for theses 
specifically for android:name 

> Class references in the manifest, was not found in the project or the libraries Unresolved class and Package

    ` <receiver
            android:name="com.app.example.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>
        <receiver android:name="com.app.example.flutterlocalnotifications.ScheduledNotificationReceiver" />

        <service
            android:name="com.app.example.localnotifications.services.LocalNotificationsService"
            android:exported="false" />

        <service
            android:name="com.app.example.flutterlocalnotifications.ForegroundService"
            android:exported="false"
            android:stopWithTask="false"/>`

**Comment by MaikuB** [comment]
Is there a reason why you are trying to configure these? Doing this is no longer required for recent versions. The issue you have is also valid as you have specified the path/namespace of these files as though they are part of your app. The correct details can be found in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/AndroidManifest.xml. This is part of the plugin now so that's why you shouldn't need to do this yourself

**Comment by MaikuB** [comment]
Note in general I only look at bugs given the spare time I have. If you need help then places like Stack Overflow is the place to go. In saying that, you should take a look at the example app in the repository as there's code for your exact scenario and make sure to cross-reference with the readme as the code you have would seem to indicate you hadn't checked either of those things
