### ISSUE TITLE
Could the notification id changed to be a string 

### ISSUE THREAD

**Issue by cedvdb** [MaikuB/flutter_local_notifications#1353]
It would be easier if the notification id was a string to update a current notification based on an entity ID received from backend.

Use case: chat messages

**Comment by MaikuB** [comment]
That's right. You'll also find that similar plugins for other cross-platform frameworks like React Native (https://github.com/wix/react-native-notifications/blob/7d606f2c07a7a69a6f4d803312121d7348aa0a01/lib/src/Notifications.ts#L58) and Xamarin (https://github.com/thudugala/Plugin.LocalNotification#show-local-notification) take integer IDs because of this
