### ISSUE TITLE
Large icon only shows when notification is expanded

### ISSUE THREAD

**Issue by MaxiSonntag** [MaikuB/flutter_local_notifications#136]
As the title says, if using a large icon on Android, it only shows when the notification is expanded to show the big picture. I think the desired behaviour should be to show the icon when the notification is collapsed to indicate it can be swiped down to show the bigger version of it.

These screenshots show what I mean, ignore icon and big picture are different, I'm using random images.

![collapsed](https://user-images.githubusercontent.com/22814120/49944863-c1621380-feeb-11e8-8d1b-e3ae43c9b53c.jpg)

![expanded](https://user-images.githubusercontent.com/22814120/49944868-c4f59a80-feeb-11e8-8510-3b8b7fb8b027.jpg)

**Comment by MaikuB** [comment]
Thanks for reporting this. I can see where the issue is but I wouldn't say what you mentioned is the desired behaviour overall. Rather, it's one of the options. Will look to how to address this as per https://developer.android.com/training/notify-user/expanded#java. Happy to take a PR as well if you'd like to look at contributing

**Comment by MaikuB** [comment]
Added a way to do this now in version 0.4.3. Check the example app for sample code
