### ISSUE TITLE
Efficient way to pull Assets Image as BigPicture/Icon?

### ISSUE THREAD

**Issue by YohanWadia** [MaikuB/flutter_local_notifications#1375]
hi,
What if i have the images that is needed as **LargeIcon/BigPicture** already there in my Assets folder?
I worked out something like this... but could this be correct/efficient... or am I missing something that you have already provided?
I just edited your pre made method **_showBigPictureNotificationBase64**
png files of _polo_ & _youtube_ i placed inside the **Icons** folder you have already created

```

Future<void> _showBigPictureNotificationBase64fromAssets() async {
      //edited extra code============
      ByteData bytesBigPic = await rootBundle.load('icons/polo.png');
      var buffer = bytesBigPic.buffer;
      var bigPicture = base64.encode(Uint8List.view(buffer));
      ByteData bytesIcon = await rootBundle.load('icons/youtube.png');
      buffer = bytesIcon.buffer;
      var largeIcon = base64.encode(Uint8List.view(buffer));
      //edited extra code============

    final BigPictureStyleInformation bigPictureStyleInformation =
    BigPictureStyleInformation(
        ByteArrayAndroidBitmap.fromBase64String(bigPicture),
        largeIcon: ByteArrayAndroidBitmap.fromBase64String(largeIcon),
        contentTitle: 'overridden <b>big</b> content title',
        htmlFormatContentTitle: true,
        summaryText: 'summary <i>text</i>',
        htmlFormatSummaryText: true);
    final AndroidNotificationDetails androidPlatformChannelSpecifics =
    AndroidNotificationDetails(
        'big text channel id', 'big text channel name',
        channelDescription: 'big text channel description',
        styleInformation: bigPictureStyleInformation);
    final NotificationDetails platformChannelSpecifics =
    NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0, 'big text title', 'silent body', platformChannelSpecifics);
  }

```

**Comment by MaikuB** [comment]
There currently isn't another way to do this with the plugin. Should you find another way to do so then please do submit a PR for review. The Android API expects a bitmap so if there's a different way, I suspect all this would do this move the logic to load the asset and read its data on the Android side instead of having it done on the Flutter side

**Comment by YohanWadia** [comment]
HI,
Thanks for the reply.
The reason I dont submit PRs immediately, is to avoid unnecessary backlog... SO I always confirm first if this is concurrent with your apps concepts.
Also, Im not clear about your answer...

Q1. Isnt this a requirement that hasnt been tackled by your example?
Q2. Now if Im not missing something that your example already has that could solve this kind of a requirement, then let me know if this is an efficient way of doing this... because I am presently using this kind of a code.
If its a **YES** for both the above questions... then I will submit a PR.

thanks,
YOhan

**Comment by MaikuB** [comment]
> Also, Im not clear about your answer...

What exactly wasn't clear? I answered your original question ("Efficient way to pull Assets Image as BigPicture/Icon?") in the first sentence of my response by saying there isn't any other way to do it. This should also answer Q2 although you haven't properly formed it as a question to indicate what I would saying yes or no to. Put simply, what you have is the only way to do it. What can or can't be done with this plugin depends on the APIs it exposes.

Regarding Q1, yes it doesn't show how to load an asset in this specific scenario because it wasn't intended to cover every single scenario. In saying that, when I talked about submitting a PR, I was referring to submitting a PR if you find a different way to load assets via this plugin's APIs by exposing new APIs for the plugin itself. This would involve writing code in Kotlin or Java (e.g. there'd be code changes required in https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java). I wasn't referring to submitting a PR to the example app, which I suspect is what you thought I was referring to.

**Comment by MaikuB** [comment]
Also there is actually one tweak that could be done with your original code, which is to get rid of the code that base 64 encodes your data. This step is redundant when you can pass a byte array directly via https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/ByteArrayAndroidBitmap/ByteArrayAndroidBitmap.html. This was demonstrated in the example app https://github.com/MaikuB/flutter_local_notifications/blob/1126d47222c4a6ddc49b1e7ee49f26253f92f450/flutter_local_notifications/example/lib/main.dart#L1102
