### ISSUE TITLE
Android 12 Local Notifications not received

### ISSUE THREAD

**Issue by JoelSuyati** [MaikuB/flutter_local_notifications#1403]
Actually I implemented Local notifications in our project but that seems to be working fine but when we look at Android 12 that was not working.

**Comment by MaikuB** [comment]
There are no known issues with Android 12 and this has been tested by myself and other members of the community. You'll need to look further into what your issue is. The example app is there in the repository as well. If you want to report a bug then use the bug report template and providing a link to a repository with a minimal app that can produce a problem. The emphasis here is being on reporting bugs with this plugin as if the issue you have is with your own application then please use community forums/chat servers like Stack Overflow, Discord, Slack etc
