### ISSUE TITLE
Custom sound not working

### ISSUE THREAD

**Issue by suyxx** [MaikuB/flutter_local_notifications#1424]
cloned the project :- 

generated app from example package

on click of button "show notification with custom sound"

in both real device (android 9) motorola-x4 and emulator android(11) -pixel5

notification is showing but sound doesn't play.

notification sound works on android 8 on tab

**Comment by MaikuB** [comment]
You'll need to check your device settings and your environment. There are no (known ) issues with notification sounds and that you can get this issue by running the example app should indicate this as many others (myself included) have successfully run it without issues. Recently, another developer had run into an issue and it turned out to be an problem on their end https://github.com/MaikuB/flutter_local_notifications/issues/1410
