### ISSUE TITLE
Instructions for setting up the plugin are not straightforward

### ISSUE THREAD

**Issue by KCL-TelferAA** [MaikuB/flutter_local_notifications#1441]
**Describe the bug**
Instructions for setting up the plugin are not straightforward.

**To Reproduce**

1. Go to '[flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications)'
2. Try to find clear instructions for setting up plugin

**Expected behavior**

1. Plugin page should have simple instructions for setting up Android project
2. Plugin page should have simple instructions for setting up iOS project
3. Plugin page should have simple instructions for setting up Flutter project
4. Plugin page should include "gotchas", technical details and troubleshooting information at the bottom of the page or on a GitHub

**Actual behaviour**
Documentation is hard to understand and can take more time than necessary to setup the plugin.

**Comment by MaikuB** [comment]
Note what you've described isn't a bug as is to do with the software. As for the issue itself, did you end up being able to use the plugin and if so, what did you find could be simplified? It is open-source so if you feel there's something missing then you can submit a PR for review. At the moment, you haven't provided much detail and have used the word "should" a lot , implying that everything you said you should be mandatory when this can often be a matter of preference

**Comment by therenca** [comment]
@KCL-TelferAA agreed

**Comment by MaikuB** [comment]
FYI unless more details are going to be provided then I'll be closing this soon and as mentioned before PRs are welcome. This is something I maintain in my spare time and barely had a chance to use in applications I've gotten to work on.

There's something important I also want to point here that plugins interface with APIs with the native platforms. This means the rules that apply to the native platform will apply here and developers should really understand how said platforms work given the plugin's APIs are a layer on top of that. Calling this out as Flutter is getting more popular with more devs using Flutter to target multiple platforms without understanding the platforms they are working with and may think using Flutter means they don't have. Those platforms will be evolving how things need to be setup over time e.g. how to setup image resources and the resolutions required. This is one of the reasons there are links to official docs. I state this if the point I'm trying to make if what you're trying to communicate is that there are too many steps involved, that's because that is what is required by those platforms
