### ISSUE TITLE
app_icon not showing with notification.

### ISSUE THREAD

**Issue by Itiode** [MaikuB/flutter_local_notifications#1453]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
You've not filled in the template to provide any evidence that there is a bug. I dare say your issue is because you haven't configured everything properly otherwise this would be a much more widespread issue and could be reproduced by the example app. On that note, please make use of the example app as a cross-reference for what you've done.

Closing as there's no known issues on this and no evidence provided
