### ISSUE TITLE
Help - How to zone schedule Notification for only 1 time

### ISSUE THREAD

**Issue by tonmooy** [MaikuB/flutter_local_notifications#1499]
How to zone schedule Notification for only 1 time 
I already setup zone schedule notification on  19 feb   at 8 am

but it's show daily at 8 am how can I show it only specific date and time  only  for once, 
thanks in advances

**Comment by MaikuB** [comment]
This is already supported and demonstrated in the example app. If you have a recurring notification then that is because you would've specified that it should be recurring via the `matchDateTimeComponents` parameter. This is covered in the docs that this is for recurring notifications e.g. weekly, daily

Closing as it looks like a user error
