### ISSUE TITLE
Notification being sent every single time

### ISSUE THREAD

**Issue by Shashwat2708** [MaikuB/flutter_local_notifications#1500]
Right now, I am using cloud functions to send notifications and I don't want to push notifications when the app is already on.
Is there a way to do so?

**Comment by MaikuB** [comment]
With what you mentioned, this is off-topic for the repository as that would be for push notifications so will be closing the issue. The plugin hosted in this repository is for local notifications , which is triggered on the local device rather than being pushed remotely via server as you've described
