### ISSUE TITLE
The Android fullScreenIntent attribute cannot be jumped in an application that has the systemAlertWindow permission enabled

### ISSUE THREAD

**Issue by DioboKN** [MaikuB/flutter_local_notifications#1516]

**Comment by MaikuB** [comment]
Could you please elaborate why this is an issue with this plugin? It's responsibility in this case it to specify the attribute on the Android side which it does at https://github.com/MaikuB/flutter_local_notifications/blob/2c0b2db29fef939f1355cd708f8c5fee73deed22/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L240

What happens from there should be the expected behaviour as defined by Android that it is outside the control of the plugin

**Comment by DioboKN** [comment]
I mean, is it inevitable?

**Comment by MaikuB** [comment]
I don't know why you used the word "inevitable" here so I can only repeat what I said before. In other words there's no bug in the plugin with this so what you see should be expected. Perhaps the word "expected" is what you were trying to express. I've shared the exact code that the plugin calls to so going to be closing as the plugin is doing what it's expected to do
