### ISSUE TITLE
iOS Communication Notifications implementation

### ISSUE THREAD

**Issue by PapyElGringo** [MaikuB/flutter_local_notifications#1525]
Is it possible to implement the equivalent messaging notification for iOS ? check [Communication Notifications documentation](https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications)

In order to get something similar to theses notifications

![image](https://support.apple.com/library/content/dam/edam/applecare/images/fr_FR/iOS/ios15-iphone12-pro-lock-screen-notification-animation.gif)

Thanks in advance !

**Comment by MaikuB** [comment]
No as this relies on each extensions specific to the app. This was in the docs you linked to so if you hadn't picked up on that then you may need look deeper in the docs

**Comment by PapyElGringo** [comment]
Hey thanks for the answer but I'm not sure what you are referring to? 
If we are looking at the `Message Intent` it's seem quite similar of what we already have for Android with `MessagingStyleInformation` where you need to declare a `Person` for each messages.

There could be something I'm missing so if you can explain to me I would be glad ! 
Cheers mate

**Comment by MaikuB** [comment]
I've not worked with extensions so bear in mind that regardless of what I say, you're going to need to do a deep dive yourself into it and quite possible that I've missed something. However, I'm going from their docs and if you look at what the docs mention, this works by hooking into what is essentially a native callback (`didReceive`) so that you can modify the notification content before it's presented. This is present in all of the code snippets and the docs refer to how to do this https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications?language=objc. This has steps you can follow and if you do so, you should see that this is something added to and specific to each app. If it's possible to achieve this another way then it'd need a PR  and I'd be happy to look at one. However, all the docs would point to this being the only way.

**Comment by PapyElGringo** [comment]
I did saw that it's required to hook on `didReceive` callback but what do prevent `flutter_local_notifications` to hook it itself and then apply an intent if any provided from flutter side to the plugin?

**Comment by MaikuB** [comment]
> I did saw that it's required to hook on didReceive callback but what do prevent flutter_local_notifications to hook it itself and then apply an intent if any provided from flutter side to the plugin?

Not possible as I explained when I said "you should see that this is something added to and specific to each app". As this wasn't understood the first time, looks like I need to be more explicit. This means it is done completely outside of the plugin with no way for the plugin to know. Much like you could write a lot of custom Objective-C/Swift code deep within your app and it's not something a plugin can be made aware of. All of this takes place outside of the context of Flutter. It could even happen when the app isn't running and for a communication notification, this would most likely be the scenario as your app would be responding to a push notification

**Comment by iosephmagno** [comment]
Hi Maiku, why do you think this should be done by app? Awesome_notification will add this after they release their version 0.7.0. The approach is to  code the fcm companion plugin to implement the new iOS chat layout, as I was suggesting here https://github.com/MaikuB/flutter_local_notifications/issues/1615

**Comment by iosephmagno** [comment]
We noticed we can achieve the same result with a UI trick.

Basically we can create on the fly a custom png image to be used in place of the app_icon. We will create the pic to be “user_avatar + app_icon” inside a square box with transparent background (see red square below).

![E2632DE6-4A34-46C9-8B58-30A6420BC31C](https://user-images.githubusercontent.com/83366073/180667682-55af07d3-fb36-40d9-99ef-a3970941ee07.jpeg)

To achieve our scope, we would need to pass our custom image as a field inside DarwinNotificationDetails, so that each badge will show the avatar of related user.
 
![4EEBF824-23AD-4F6D-AA03-E78215B26C38](https://user-images.githubusercontent.com/83366073/180667683-68ca08e2-649a-40cf-a38c-e1d836ec0cff.jpeg)

**Comment by iosephmagno** [comment]
My bad, although trick is doable, image will look smaller.

We will try to enable ios communication notifications, but I’m still curious if you could add this for your part and leave to us only the rest:
https://gist.github.com/Dexwell/dedef7389eae26c5b9db927dc5588905

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by JYeop** [comment]
Still no updates?

**Comment by MaikuB** [comment]
@JYeop This is open-source so if you're in need of something and feel it's possible to implement then you can submit a PR
