### ISSUE TITLE
The problem in the example code home page syntax, this: Undefined name 'onDidRecieveLocationLocation'.

### ISSUE THREAD

**Issue by LukeDaniel16** [MaikuB/flutter_local_notifications#153]
"var initializationSettingsIOS = new IOSInitializationSettings(
    onDidReceiveLocalNotificationCallback: onDidRecieveLocationLocation);"

When written this part of code example in my VS Code, it generate for me the error: Undefined name 'onDidRecieveLocationLocation'.

Syntax error or simple bug that i don't see? Sorry, i'm beginner in Flutter.

**Comment by MaikuB** [comment]
There's a bug in your own code where you haven't defined `onDidRecieveLocationLocation`. You'll need to take a closer at the sample app and possibly run it, which you can do by cloning the repo. On a related note, I've just realised I've had `onDidReceiveLocalNotificationCallback` as the name of the property when it should've been `onDidReceiveLocalNotification`. This is now fixed in version 0.4.4+1

**Comment by LukeDaniel16** [comment]
So, better i wait for the new version?....

I don't how to resolve, still. Sorry
