### ISSUE TITLE
Scheduled Notifications with flutter_local_notifications package

### ISSUE THREAD

**Issue by mpronoitis** [MaikuB/flutter_local_notifications#1530]
When i reboot or stop program alla scheduled notifications does not appear.What should i look for ?

**Comment by MaikuB** [comment]
This is most likely this is to do with https://github.com/MaikuB/flutter_local_notifications/issues/17#issuecomment-1061502547

**Comment by mpronoitis** [comment]
Thank you for your immediate response.It is essential to add proguard-rules.pro ? If yes where should i add them ?

**Comment by MaikuB** [comment]
Yes it is and that is why it's referred to in the readme. For where to add it, if you check that section of the readme, there's a link to the example app that shows you where it goes so that you would need to place it in a similar location in your own app https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by mpronoitis** [comment]
so the only think that i must do is to add proguard-rules.pro into app folder ?

**Comment by MaikuB** [comment]
I don't know what you have and haven't done yet so you'll need to check what you've got and cross reference with the readme and if need be, the example app as well

**Comment by mpronoitis** [comment]
I must follow the example folder or something else ?

**Comment by MaikuB** [comment]
You must follow the readme. I mentioned the example app as it can be used a reference. Going to close this issue now as the original post was implying a bug but there is none on this

**Comment by mpronoitis** [comment]
Hi! How i can request permisions for android? I want notification to pop-up without user must check it form app info.Also, vibration is not play when having a scheduled notification.
