### ISSUE TITLE
How to show two fullScreenIntents one below the other ?

### ISSUE THREAD

**Issue by olhybrius** [MaikuB/flutter_local_notifications#1551]
Hi !

I'm currently building a countdown timer app which triggers a notification once a timer reaches zero. It works fine with a single timer, but if I set two timers to end at the same time, the second fullScreenIntent is hidden under the first one and the only way to reveal it is to tap on the first one beforehand. I would like to have the two notifications appear at the same time on the screen, one below the other. Is there any way to achieve that or am I facing some kind of android limitation here ? 
If it helps, here is the function I'm using to display a notification to the user :
```
Future<void> showNotifications(String timerLabel) async {
    const notificationDetails = NotificationDetails(
        android: AndroidNotificationDetails('timers_channel', 'Timers Channel',
            channelDescription: 'Notify when a timer is over',
            importance: Importance.high,
            fullScreenIntent: true));

    await flutterLocalNotificationsPlugin.show(
      UniqueKey().hashCode,
      'Timers',
      "Time's up : $timerLabel",
      notificationDetails,
    );
  }
```

Thanks for your help !

**Comment by MaikuB** [comment]
Not really sure what you mean here but most likely what is happening is expected behaviour. The reason I'm not sure what you mean is even if you have requested a full screen intent, if the app/device is still active, regular notifications may end up being presented so normal OS behaviours apply to notifications (e.g. OS may group/collapse notifications) and this has nothing to do with full screen intents. Sounds like that is what you're referring to here

**Comment by olhybrius** [comment]
> Not really sure what you mean here but most likely what is happening is expected behaviour. The reason I'm not sure what you mean is even if you have requested a full screen intent, if the app/device is still active, regular notifications may end up being presented so normal OS behaviours apply to notifications (e.g. OS may group/collapse notifications) and this has nothing to do with full screen intents. Sounds like that is what you're referring to here


So basically what you're saying is that there's no way around the grouping/collapsing here ?

**Comment by MaikuB** [comment]
Assuming you're referring to notifications, which you haven't explicitly confirmed

**Comment by olhybrius** [comment]
Well, the issue is the same whether the app is active or not. In the notification drawer, the notifications are not grouped, which is good. But what is shown on the screen while the device is in use is that the second notification hides the first one instead of being added below like in the notification drawer. Is there really nothing to be done about this ?

**Comment by MaikuB** [comment]
Not as far as I know but as this is really more to do with notifications rather than the plugin itself, you can try on forums where Android developers with experience in this can answer. 

Given you are still talking about notifications then I don't think you understood why I brought up the point about if the app/device. I suggest you read https://developer.android.com/training/notify-user/time-sensitive#display-notification-user and the last paragraph of https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#full-screen-intent-notifications as if a full screen intent did actually occur you **wouldn't** see a notification

**Comment by MaikuB** [comment]
Yes but it's typically based on if the device is being used or not. A reminder that the plugin has an example app so you can check what happens there

**Comment by olhybrius** [comment]
Well, thanks for all the explanations. And thanks for your work on the plugin so far as well. I'm closing the issue now since, as you said, it has more to do with notifications and Android than with the plugin itself.
