### ISSUE TITLE
[Help] How can I make a notification without banner, only sound?

### ISSUE THREAD

**Issue by FantaZZ** [MaikuB/flutter_local_notifications#1558]
Why I have to make sound by notification, because I want use system default notification sound.

**Comment by MaikuB** [comment]
Not sure exactly what you mean here but if you mean you don't want any kind of visual notification at all, i.e. not even in the system tray then that's not possible. If you mean it can still go to tray but not show the heads up notification then at least on Android then you should read their documentation as mentioned at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#displaying-a-notification. Note that in general, it's a prerequisite that you understand  how notifications work on the platforms you're targeting before using this plugin as it's a wrapper for the native APIs. For iOS and macOS, there's already an open issue on the banner https://github.com/MaikuB/flutter_local_notifications/issues/1295

General comment here that if you need help then look to use Stack Overflow, Discord, Slack etc as I maintain the plugin in spare time so can only look at bugs. Furthermore, I don't even really use the plugin as there's not been opportunities to do so and that means there'll be others in the community with more experience to provide answers and people who on this repository tend to do so to post issues rather than answer them

**Comment by FantaZZ** [comment]
ok, many people say that is not possible
