### ISSUE TITLE
didNotificationLaunchApp always false

### ISSUE THREAD

**Issue by monmonja** [MaikuB/flutter_local_notifications#156]
I copied the example and put this on main function, the notification works when user is on app but i cant get the payload or the didNotificationLaunchApp to work in Android when the user is in another app, both emulator and device
`var flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
  var notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
  print(notificationAppLaunchDetails.didNotificationLaunchApp);`

added this two on manifest too
`<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>`

I updated to flutter_local_notifications: ^0.4.4+2 and still no luck

**Comment by MaikuB** [comment]
Could you provide more details about the scenario you're going through? `didNotificationLaunchApp` should only return true when an app has been launched from a terminated state due to the user interacting with a notification. Off memory, that flag will still return true within the same session if `getNotificationAppLaunchDetails()` is called again as it's not cleared upon after calling it once

**Comment by MaikuB** [comment]
I should also point out the method was originally written to allow devs to change the first page that should be displayed based on the notification payload as per #99

**Comment by monmonja** [comment]
Hi, i just found out that the backend is not sending data.click_action = 'FLUTTER_NOTIFICATION_CLICK', after adding and the intent filter on manifest, the onResume and onLaunch seems to work. Thanks a lot
