### ISSUE TITLE
AndroidNotificationAction without back to foreground [HELP]

### ISSUE THREAD

**Issue by MohsenHaydari** [MaikuB/flutter_local_notifications#1561]
I want to get notification action on onDidReceiveNotificationResponse without back to the foreground to use NotificationResponse in the main thread, I get data in onDidReceiveNotificationResponse when set showsUserInterface property to true but the app opens after clicking action. otherwise i get action data in onDidReceiveBackgroundNotificationResponse,

**Comment by MaikuB** [comment]
I'm having some trouble understanding what you're after. Do you mean you want to be able to respond to an action on the main isolate without the action trying to bring the app to the foreground i.e. the app would remain in the background? If so then I believe the only option is to have it as a background action and using the various Flutter/Dart APIs that can allow communication between the background and main isolate as mentioned in the readme. The example app has demonstrates this too using the `IsolateNameServer` APIs. If there's a different way to do this then it'd be something you need to investigate and submit a PR for

**Comment by MaikuB** [comment]
Closing this since there's been no more response on this. Assuming I understood what's being asked, I believe this isn't possible either as an app's resources may be released when it's in the background. In these scenarios, the main isolate wouldn't exist to my understanding. If you believe otherwise then you're welcome to submit a PR
