### ISSUE TITLE
App Icon in notification(release build) is empty: shown as grey square

### ISSUE THREAD

**Issue by Programmerflash** [MaikuB/flutter_local_notifications#1566]
> If you have an issue with the icon then either you haven't changed it correctly the way Android expects it (you'll need to check their docs on this e.g. if all of is non-transparent then I believe you may have issues) or hadn't follow all the steps in the readme as I explicitly warned that not setting it up properly may mean the icon won't appear as expected [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration). There's no issue with the plugin when it comes to the icon as the steps you describe are the same as what's done in the example app https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example

I have followed all instructions but still it is neither displaying icon nor playing custom sound on release build. It is working fine or debug build.
[https://stackoverflow.com/questions/61301786/flutter-android-notification-icon-grey-square](https://stackoverflow.com/questions/61301786/flutter-android-notification-icon-grey-square) 
many people also facing same issue in this StackOverflow issue, check comment section of answer

_Originally posted by @Programmerflash in https://github.com/MaikuB/flutter_local_notifications/issues/1017#issuecomment-1100243224_

**Comment by MaikuB** [comment]
If you believe there is a bug then provide a link to a minimal app that follows all the instructions and can reproduce the issue. What you've showed doesn't really mean there's many people with the same issues and those claims aren't substantiated either. If there's a legitimate issue here then logically speaking, there should be more reports of on this repository. Currently, your issue is the only one open on this. There have been others who have claimed they followed the instructions yet when they provided the requested minimal app, this turned out to be false

**Comment by kenguyenduc** [comment]
I did the following and it worked for me:

1. Create a transparent and white notification icon (you can use the following tool: AndroidAssetStudio )
Download the zip folder, unzip and you'll see it contains a res folder with different drawable folders. Copy and paste the contents of the res folder in "android\app\src\main\res" path
![image](https://user-images.githubusercontent.com/32872158/167284466-15ae1a45-f05c-452f-98d7-425af448d94d.png)

2. Then open the AndroidManifest.xml file and add the following lines to it:
ic_stat_calendar_today is the name of my notification icon. And each of the drawable folders that have been pasted contain a different size of icon with the same name.
![image](https://user-images.githubusercontent.com/32872158/167284479-dfc8ea5d-3c09-4252-8489-ecfd00107b6e.png)

3. If you want to change the color of the icon then check the above image. Add the metadata tag after the notification icon tag
4. Go to "android\app\src\main\res\values" and add a colors.xml file
![image](https://user-images.githubusercontent.com/32872158/167284498-7d0cf7c6-d7c3-4c5a-8a30-7e2fce6687f6.png)

+++ AND if you use .show, you can add color in function:
_flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            _channel.id,
            _channel.name,
            channelDescription: _channel.description,
            icon: 'app_icon',
            importance: Importance.max,
            priority: Priority.max,
            color: Color(0xFFBB2030),
          ),
        ),
        payload: jsonEncode(message.data),
      );

+++ References: https://github.com/flutter/flutter/issues/17941#issuecomment-622268132

**Comment by MaikuB** [comment]
thanks for sharing @kenguyenduc but note that this is different issue than what was originally described by @Programmerflash where the icon works in debug builds but not for release builds. There's a callout in the readme that failing to do the release build configuration can lead to the icon not appearing properly. As it's been a while now since there's been evidence to indicate there's a problem even after doing the release build configuration steps, I'm going to close to this issue. Feel free to re-open if you can provide a minimal example app and have ensured the steps were followed. The example app also exists to be used as a reference and for reproducing issues
