### ISSUE TITLE
Problem with group notifications - Grouping from the third notification

### ISSUE THREAD

**Issue by burekas7** [MaikuB/flutter_local_notifications#1569]
Hi,

I'm trying to implement the Group Notification feature.
But I have a strange behavior:

This is the code:
Before each notification I increment the channel id, id=1 is the first notification id.
As you can see on the first notification I set **setAsGroupSummary: true**, on the other I don't set it.
On both I set **groupKey: channelName**.
(channelName is the same for all notifications)
* Just to mention, I use the **zonedSchedule** option.

What happen is:
1) channelID = 1 : The first notification is showing up.
2) channelID = 2 : The second notification replace the first notification.
3) channelID = 3 : The group notifiaction start from the third notification which join the to second.

So my question is why does the grouping not start from the second notification after the first one.
What am I doing wrong?
Am I using the **setAsGroupSummary: true** correctly? (Because in you example you put it only in the third notification.
```
  static Future<void> instantFutureNotification(
      int channelId,
      String channelName,
      String channelDescription,
      String title,
      String content,
      tz.TZDateTime dt) async {
    AndroidNotificationDetails androidDetails;
    if (channelId == 1) {
      androidDetails = AndroidNotificationDetails(
        channelId.toString(), channelName,
        channelDescription: channelDescription, groupKey: channelName,
        setAsGroupSummary: true,
      );
    } else {
      androidDetails = AndroidNotificationDetails(
        channelId.toString(), channelName,
        channelDescription: channelDescription, groupKey: channelName,
      );
    }
    var iosDetaild = const IOSNotificationDetails();
    var platformDetails =
        NotificationDetails(android: androidDetails, iOS: iosDetaild);

    await _flutterLocalNotificationsPlugin.zonedSchedule(
        channelId, title, content, dt, platformDetails,
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime);
  }
```

Version: ^9.4.0
Android

**Comment by burekas7** [comment]
By the way, I'm looking on this example here:
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart#L1293

Why do you seperate the first and the second notification by **firstNotificationAndroidSpecifics** and **secondNotificationAndroidSpecifics** if they are the same?

**Comment by mrishabh72** [comment]
I faced the same issue.At the end, I didn't found any solution and gave up. :(

**Comment by burekas7** [comment]
In addition to that, I noticed that in the app's notification permission page, there are duplicate of the same notification category (As you can see it has the same name). Every new notification create new category there. 
Why does it happen? Is it a bug?
Maybe it also can explain the problem here.

![image](https://user-images.githubusercontent.com/13424257/164246874-aa403e30-d000-40fa-a0df-86eec42c48db.png)

**Comment by MaikuB** [comment]
> Why do you seperate the first and the second notification by firstNotificationAndroidSpecifics and secondNotificationAndroidSpecifics if they are the same?

This is because I was trying to translate the samples more directly and have separate details for each notification. There's no other reason beyond that and it could be the same like you appear to be implying

> In addition to that, I noticed that in the app's notification permission page, there are duplicate of the same notification category (As you can see it has the same name). Every new notification create new category there.
Why does it happen? Is it a bug?
Maybe it also can explain the problem here.

Given you don't know what is going on, you'll need to spend more time to look into the Android documentation get a better understanding how notifications work. As the plugin is a wrapper for the native APIs, you still need to have an understanding on how notifications work on Android and all the concepts surrounding it. All notifications are meant to be associated with a channel and you have used a different channel for each one. A channel uniquely identified by it's id **not** its name. If you look at the example, which in itself is based on official Android example and had a link to the the page with it (i.e. https://developer.android.com/training/notify-user/group.html), you see they make use of the same notification channel. I suggest you start investigating from there. If you need further help then I suggest you jump onto places like Slack or Stack Overflow
