### ISSUE TITLE
Notification.MessagingStyle support on Android

### ISSUE THREAD

**Issue by Hixie** [MaikuB/flutter_local_notifications#159]
https://developer.android.com/reference/android/app/Notification.MessagingStyle

**Comment by MaikuB** [comment]
I assume that you've linked [Notification.MessagingStyle](https://developer.android.com/reference/android/app/Notification.MessagingStyle) to instead of [NotificationCompat.MessagingStyle](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.MessagingStyle) to provide richer notifications?

If so, it would sound like, and correct me if I'm wrong, for API 28+ [Notification.MessagingStyle](https://developer.android.com/reference/android/app/Notification.MessagingStyle) should be used. This would in turn mean that plugin will need to switch to using [Notification.Builder](https://developer.android.com/reference/android/app/Notification.Builder) instead of [NotificationCompat.Builder](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder)

For API < 27, can use [NotificationCompat.MessagingStyle](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.MessagingStyle). The API surface of the plugin should still provide the means to specify the details of each [person](https://developer.android.com/reference/android/app/Person.Builder)

**Comment by Hixie** [comment]
I have no strong opinion, I just noticed that this style wasn't offered by the plugin but is listed in the Android documentation.

**Comment by MaikuB** [comment]
Noted, this is partly due to not being able to version 28 of the support library before as apparently other devs had pointed out there was an [issue](https://github.com/flutter/flutter/issues/19644) with Flutter when it came to using that version of the library. Though I can see you've said you've believed it's fixed.

Was also hoping to migrate to AndroidX but from what I gather, there are open issues (e.g. https://github.com/flutter/flutter/issues/23995) on that so guess will have to defer that to later

**Comment by MaikuB** [comment]
Given the plugin has been migrated to AndroidX, it looks like there's no need to be concerned with branching off the code anymore. AndroidX has the Person class that was appeared to be missing in the support library

**Comment by MaikuB** [comment]
Added in v0.5.1. Let me know if you've got any feedback :)

**Comment by MaikuB** [comment]
Closing this. Please feel free to reopen if you feel there's something missing
