### ISSUE TITLE
[macOS] Example not working

### ISSUE THREAD

**Issue by Fraa-124** [MaikuB/flutter_local_notifications#1610]
Hello, I tested it on android & ios and working fine, but I didn't have success running the example provided in this repository on MacOS. Nothing broke but the notifications didn't showed up. I don't know if it is really broke or I'm missing something.

**Comment by MaikuB** [comment]
In my experience, this is something that happens when permissions haven't been granted. Perhaps you had dismissed it when it originally appeared or it didn't appear for some reason. Note the permissions prompt on macOS appears as a notification so it's easy to have missed or dismissed it. If you have trouble getting it to reappear after cleaning, re-running etc then can try granting the app permissions via macOS's system preferences

**Comment by Fraa-124** [comment]
Yep, you are right, The system was blocking notifications, I must have missed the request at the beginning
