### ISSUE TITLE
Can you use showPeriodically with an offset?

### ISSUE THREAD

**Issue by erolasan** [MaikuB/flutter_local_notifications#1611]
Hi, 
I need to schedule reminders for my habit tracker app, which in some cases can be repeated every day (but the user can select any custom repetition). If I use zoneScheduled it will create 7 notifications for a single reminder and having a limit of 64 notifications for IOS, this greatly reduces the number of reminders I can have before they start overriding each other.

So, I thought of using the showPeriodically() and just setting the interval depending on the repetition. For example, if I have a reminder that's repeating every day I can set the interval to 24 hours and this way I will have only 1 notification per reminder instead of 7. My question is can I somehow specify an offset to the showPeriodically() interval? Let's say it's 15:00 now and I have a reminder set for 16:00 every day, can I somehow say to the showPeriodically() method - show this notif every 24 hours starting after 1 hour?

**Comment by MaikuB** [comment]
The closest thing to this is to used `zonedSchedule` where you specify the date/time and also allows for a recurring notification. You'd still be subjected to the iOS limits. Besides that, there's no other option to my knowledge due to what the native Apple notification APIs support. If I've missed something on then and you know of a native API that supports this then feel free to submit a PR. Another thing you may need to consider is if the https://pub.dev/packages/device_calendar plugin is better suited for your app
