### ISSUE TITLE
Move away from deprecated Support Library to AndroidX

### ISSUE THREAD

**Issue by vladaman** [MaikuB/flutter_local_notifications#162]
Android Support Library is being deprecated and even flutter and firebase plugins requires you to migrate to AndroidX.

Currently with Flutter 1.1.8 and AndroidX migration I get following error:
```
/home/vlad/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-0.4.5/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:17: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/home/vlad/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-0.4.5/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:139: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class FlutterLocalNotificationsPlugin
2 errors
```

**Comment by MaikuB** [comment]
Thanks, I'm aware of this but there were open issues around migrating to AndroidX that from what I've seen, have only been recently resolved

**Comment by JeffScaturro** [comment]
@MaikuB, given those are now resolved, do you have any more hesitation in migrating? If not, are you currently working on a branch with support for AndroidX? We have a flutter app that we're releasing shortly and were planning on migrating to X. Tonight I was going to look into what it would take to get this plugin migrated, but I haven't been following AndroidX much.

**Comment by MaikuB** [comment]
I don't know if migration will break devs on stable, which is what I use and would imagine most are devs are on. I believe additional effort is required on devs to migrate their apps to Android and is supposedly covered in 

https://developer.android.com/jetpack/androidx/migrate

Based on what I've seen/read (https://github.com/flutter/flutter/issues/27106 and https://github.com/flutter/flutter/wiki/Postmortem:-AndroidX-plugin-migration), the tooling on stable hasn't been updated so that new apps support AndroidX so migration of apps will be required.

Currently got no branch to migrate the plugin but I believe the migration process for the plugin should be straightforward

**Comment by MaikuB** [comment]
Thanks I'll also do some testing as well when I get a chance to, particularly on a new app by calling `flutter create ...` on the stable channel though I imagine you'll also test that

**Comment by MaikuB** [comment]
Have migrated to AndroidX in version 0.5.0 so will close this. Thanks again @JeffScaturro for the PR :)
