### ISSUE TITLE
iOS端 第一次运行app时 onSelectNotification 没有收到回调

### ISSUE THREAD

**Issue by lurongshuang** [MaikuB/flutter_local_notifications#1674]
iOS端 第一次运行app时，点击发送的通知， onSelectNotification 没有收到回调，重新打开app后，就正常了，
什么原因呢？

**Comment by lurongshuang** [comment]
@MaikuB

**Comment by MaikuB** [comment]
Please post your issue in English. If you can't do so then I suggest you use another forum where others use the same written language you have used here

**Comment by Artimeo** [comment]
This bug appears now with versions higher than 9.6.0

Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
D/FlutterGeolocator(10718): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate(10718): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(10718): Creating service.
D/FlutterGeolocator(10718): Binding to location service.
D/FlutterLocationService(10718): Creating service.
D/FlutterLocationService(10718): Binding to location service.
D/FlutterGeolocator(10718): Geolocator foreground service connected
D/FlutterGeolocator(10718): Initializing Geolocator services
E/AndroidRuntime(10718): FATAL EXCEPTION: main
E/AndroidRuntime(10718): Process: com.***.***.***, PID: 10718
E/AndroidRuntime(10718): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.***.***.***/com.***.***.***.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime(10718): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5304)
E/AndroidRuntime(10718): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5343)
E/AndroidRuntime(10718): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime(10718): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(10718): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(10718): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(10718): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
E/AndroidRuntime(10718): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10718): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10718): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10718): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(10718): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10718): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(10718): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime(10718): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onRequestPermissionsResult(FlutterLocalNotificationsPlugin.java:1576)
E/AndroidRuntime(10718): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(10718): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(10718): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(10718): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:901)
E/AndroidRuntime(10718): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
E/AndroidRuntime(10718): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8529)
E/AndroidRuntime(10718): 	at android.app.Activity.dispatchActivityResult(Activity.java:8386)
E/AndroidRuntime(10718): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
E/AndroidRuntime(10718): 	... 13 more
