### ISSUE TITLE
AndroidNotificationDetails should accept an androidResource as a color

### ISSUE THREAD

**Issue by gbaccetta** [MaikuB/flutter_local_notifications#1683]
**Describe the bug**
AndroidNotificationDetails should accept an androidResource as a color (same as per the icon). This would allow to customize the color between light mode and darkmode. When handling the notification in background you do not have a context to retrieve the system brightness mode. 
Also an existing notification will change color dynamically if the user switch between modes 

**To Reproduce**
1. Generate local notification in background with color BLACK
2. Switch Phone to dark mode
3. the color of the icon is grey as contrast of Black is not enough

**Expected behavior**
Declaring a specific color in the res/color-night folder should allow to define a specific color for dark mode

Ideally this should be an additional field in the default configuration and in the AndroidNotificationDetails.
In this case we would have two parameters:
- color
- colorResource

**Comment by MaikuB** [comment]
I'm not sure how you expect this to work. Have you researched to see if that is even possible at all or is that based on more on how you'd like to things work? If you know of a way then please do submit a PR. What you're describing where resources are specified requires matching identifiers and that there's an API that allow for specifying a resource by its identifier. That way, Android can dynamically handle theme changes. The Android notification API for specifying the colour (see https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setColor(int)) only allows specifying a colour **value**. It doesn't provide any API for passing a resource identifier for Android to look up the colour value. For what it's worth, none of the notification libraries I've seen in other cross-platform ecosystems support this either as the Android notification APIs themselves don't support this

**Comment by gbaccetta** [comment]
Hi @MaikuB if I have some time I'll investigate it myself and try to open a PR. I admit I did not look deeper into this for now but you should be able to get color int from resource id as follows :
 
`setColor(ContextCompat.getColor(context, R.color.your_color))`

**Comment by MaikuB** [comment]
I'm aware that it can be done that way but I'm referring to a direct Android notification API to do so. This plugin's purpose is to act as a wrapper for the available notification APIs and there are none to do what you've mentioned. Therefore what you've described is more to do with custom app behaviour for your own to implement e.g. detect theme change, do processing etc. Otherwise, this leads to plugins having a bloated API surface in trying to solve all problems when the nature of open source. In other words, if you do find a way this would need to be done in a fork of your own so will be closing this.

I'm not sure if this changing your notification design either as what you're trying to do seems to be something that would take more effort than it's worth. Furthermore, as another developer in the community found, the behaviour of setting the colour differs with Android versions
https://github.com/MaikuB/flutter_local_notifications/issues/1642#issuecomment-1182812642

**Comment by fulstadev** [comment]
Just wanted to add a possible workaround, as @gbaccetta mentions that the main issue for a "required workaround" is: 

> When handling the notification in background you do not have a context to retrieve the system brightness mode.

You could simply define a root-level navigator`GlobalKey` that you provide to your app as a global app variable. Then, whenever you have to determine if the app is in dark or bright mode, you set the color of your `AndroidNotificationDetails` based on the value resutling from the following evaluation, which you can very well perform right before calling `flutterLocalNotificationsPlugin.show()`: 

```
MediaQuery.of(yourRootNavigatorKey.currentContext!).platformBrightness == Brightness.dark
```

I've tested this and it works, with the exception of always applying the color you provide to `values/styles.xml` to your notification icon for notifications received while the app is in the foreground. But that was good enough for me.
