### ISSUE TITLE
The plugin flutter_local_notifications requires Android SDK version 33.

### ISSUE THREAD

**Issue by abdullah230695** [MaikuB/flutter_local_notifications#1689]
The plugin flutter_local_notifications requires Android SDK version 33.

Im using 9.4.0 version 

but flutter compatible version is upto 32 .

**Comment by MaikuB** [comment]
Please be more specific on the issue and on what basis do you say Flutter is incompatible with Android 13 (API level 33). I've already seen Flutter apps can run on Android 13 (API 33) and the requirement for the SDK is for changing the compileSdkVersion. This isn't the only plugin that requires this either https://github.com/Baseflow/flutter-permission-handler. Note that just because the out of the box Flutter app created by the CLI specifies a certain compileSdkVersion, this doesn't mean it can't be changed

**Comment by Trend74X** [comment]
did you find any solution?
