### ISSUE TITLE
timeoutAfter property in AndroidNotificationDetails not working when app is in background mode

### ISSUE THREAD

**Issue by maulikchak** [MaikuB/flutter_local_notifications#1735]
timeoutAfter property in AndroidNotificationDetails not working when app is in background mode or kill mode

**Comment by maulikchak** [comment]
timeoutAfter property also not working with "startForegroundService" mode

**Comment by MaikuB** [comment]
The plugin's responsibility is to call the platform's native APIs so the behaviour you see is the way it's expected to work and outside the control of the plugin. On a stock Android device this is working fine using the example app so it could also be that your issue is device-specific. The following is recorded from my Pixel 6


https://user-images.githubusercontent.com/25263378/197367123-31b173ac-2a0a-4ca2-977e-08fc11d54a5c.mp4

Closing as there's nothing further the plugin can do
