### ISSUE TITLE
[Question] multiple initialize calls

### ISSUE THREAD

**Issue by angel1st** [MaikuB/flutter_local_notifications#174]
Hi there,
I have one specific use case and since I didn't able to find it illustrated into the examples, I would appreciate your feedback. 

Below is the case:
#### Requirements:
I have an app with few routes / pages and the app is in NOT closed, meaning, when I click on the notification, `onSelectNotification` will be invoked. Once notification arrives and `onSelectNotification` is invoked, I will need the current widget `context` to perform specific actions. 

### Case
At the moment notification has been clicked, the user can be at any of the routes / pages and can decide to click on the notification, hence to fire `onSelectNotification`. Since I would need the context of the current widget (which in fact is the currently open page / route), my thought was to initialize the plugin in each `initState` call and passing widget specific implementation to `onSelectNotification` callback for the current statefull widget. That way, at the moment user clicks on the notification the callback with the right context will be invoked.
Since the user may navigate back and forth over the app pages, this will lead plugin `initialize` method to be called multiple times - basically each time a new page is loaded.

### Questions
1. Is it ok to handle the case as described above - calling `initialize` multiple times?
1. Is there a better way to handle the above case?

**Comment by MaikuB** [comment]
I can't comment on if it's ok to do but I suspect it could cause issues. I believe the better solution would be to create and initialise the plugin in your main function. In this case, the plugin becomes a global variable. Create another global variable that is a stream/observable. Each page could listen/subscribe to it when it appears and you'll need to ensure that when the `onSelectNotification` callback is triggered that an item is added to the stream so that the appropriate page handles the event where the user has tapped in the notification. If you aren't familiar with streams then look at https://www.dartlang.org/articles/libraries/creating-streams or RxDart

**Comment by angel1st** [comment]
Thanks for the prompt respond, @MaikuB. Yeah - a bloc approach should do the trick and this seems to be the best one.
