### ISSUE TITLE
Can I use Group Alert If my Object same date

### ISSUE THREAD

**Issue by Gslvr** [MaikuB/flutter_local_notifications#1764]
Hi: 
Thanks for awesome package.

I have a list it has a title and alert date.  Some object have same date in list.
So they alert same time but different alert. 

Can I  group same alert if they have same date?
Thanks for it

**Comment by MaikuB** [comment]
This is something you would need to check further based exactly what it is you want to do. As this plugin is a wrapper for native APIs, your first step should be start exploring the features supported by each platform's native notification APIs to so that you can find out what's possible. From there you can see the plugin wraps around these APIs. All the supported features by this plugin can be explored by running the example app and the readme has called out that it's possible to group notifications. You will need to see if it's the same as what you're after
