### ISSUE TITLE
Time zone issues with scheduled notifications

### ISSUE THREAD

**Issue by jonahgreenthal** [MaikuB/flutter_local_notifications#179]
Apologies as this issue is really difficult to test (I think).

While in Central (Standard) Time, I set a notification for `2019-03-01T17:00:00-05:00`, i.e., 5 p.m. Eastern Standard Time on March 1.

On March 1 I went to Eastern (Standard) Time. The notification fired at 4 p.m. local time. This doesn't seem to be just a local time issue, as that's _3_ p.m. Central time; if it were a local time issue, I would have expected the notification to fire at 6 p.m. Eastern time = 5 p.m. Central time.

This might also be an issue with respect to Daylight Savings Time.

Any thoughts on what to do here? Would converting to epoch-milliseconds and using the `DateTime.fromMicrosecondsSinceEpoch()` constructor help?

**Comment by MaikuB** [comment]
what platform was this on? there's already an open issue on handling daylight savings time at #118 . Is it alright if I close this and reference this one in that issue. I've added the help wanted label to that #118 however it's difficult to test as you say and I'm not sure what the solution is here. It may be that developers need to handle this themselves. 

There's a few parts to this that make it tricky

- On Android, the notification APIs don't have the capability to schedule by date and require using the Alarm Manager APIs where the date has been converted to milliseconds since epoch
    - This conversion is done before it goes over the platform channel and is done for both platforms for consistency's sake.  It's also not possible to pass DateTime objects over them, which is why this conversion was also done. As such, I don't think your idea of doing conversion will help
-  DateTime objects have no timezone info on them, it's either UTC or local time and the [toIso8601String](https://api.dartlang.org/stable/2.2.0/dart-core/DateTime/toIso8601String.html) method doesn't have timezone info on it
    - UTC is fixed but the concept of local time here could vary. This makes it a _bit_ questionable on if it should be handled by the plugin. 
         - It could be it should be local to the device's timezone, which may change if they go between locations. Though I don't think it's common people schedule notifications with that in mind.
         - The other interpretation is it should be based on the user's timezone not in terms of offset but geographic location (e.g. IANA timezone). This is generally what I'd imagine what people would want. However, I don't know of a way on Android to detect when daylight savings has occurred so that if it has happened, notifications could be rescheduled since the Alarm Manager APIs doesn't deal with dates. This is further complicated as on iOS, they have their own list of [timezones](https://developer.apple.com/documentation/foundation/timezone/2293621-knowntimezoneidentifiers) that are supported that may not match the IANA timezone list

I'll update the readme to add a note about the issue/limitation but to summarise, there are technical issues/limitations that make it difficult to solve. If someone has an idea on how to do and/or can submit a PR then that would be awesome too

**Comment by jonahgreenthal** [comment]
This was on iOS. I haven't tested this on Android.

Would it be possible to change the plugin to accept a seconds-since-epoch (or milliseconds or microseconds) directly to the plugin, rather than dealing with Dart's awful, underspecified `DateTime` objects?

To explain my use case: my application is a companion/guide to a conference. There are particular events/meetings within the conference at particular times, and I'm using this plugin to let people set reminders for the events (and I want it to work even if they set the reminder before they travel to the conference).

**Comment by jonahgreenthal** [comment]
By the way, I really appreciate how attentive and responsive you are to the issues I and other people open on this plugin. Thanks!

**Comment by MaikuB** [comment]
If you were able to follow my response above, Youl see that the conversion already happens underneath the hood (you can see the source code in https://github.com/MaikuB/flutter_local_notifications/blob/master/lib/src/flutter_local_notifications.dart). So unless I'm missing something, I don't think that change will do much besides making it explicit (which I think is a good thing)

**Comment by MaikuB** [comment]
Just saw your other response after I replied, thanks :)

**Comment by jonahgreenthal** [comment]
I followed most pieces of your response above but not necessarily the overall logic.

Is the upshot that you don't think it's possible to guarantee that a notification will occur at a specific instant; it will always have some aspect of being relative to the local time, the time zone in which the notification was set, and/or the time zone the device is in when the notification happens?

**Comment by MaikuB** [comment]
In short, I don't know of a solution to deal with dates across all platforms that will take into consideration daylight savings and what the user means when they pass a date and say it's in local time.

In your original post you mentioned the timezones changed, was that triggered manually? Am curious how that took place (e.g. physically went somewhere else with a different timezone)

**Comment by jonahgreenthal** [comment]
> In short, I don't know of a solution to deal with dates across all platforms that will take into consideration daylight savings and what the user means when they pass a date and say it's in local time.

I understand. It's a high priority for me, so if there's any way I can help, or if you think of any other options, please let me know.

> In your original post you mentioned the timezones changed, was that triggered manually? Am curious how that took place (e.g. physically went somewhere else with a different timezone)

I set the notification in Chicago, then flew to Orlando.

**Comment by MaikuB** [comment]
i guess the obvious one is if you're able to come up with a solution that works and submit a PR for it then great. given it's a high priority for you i feel you may have to look at forking or at least deal with using platform channels. For example, if you're only concerned about iOS then write code that's specific for scheduling notifications on iOS. The notifications API on iOS allows you to deal with dates and specify the time zone

**Comment by MaikuB** [comment]
Just an update on this, I believe I've found a solution that I tried out when Sydney required changing the time due to daylight savings. It involves specifying the timezone.  There's a plugin available for getting the local timezone [here](https://pub.dev/packages/flutter_native_timezone) though it is lacking the ability to query supported timezones. 

My thoughts are to change the scheduling functionality to take a timezone but this kind of change cannot be retroactively applied. I'll be trying to see if this can be done as part of the plugin restructuring. For backwards compatibility, I'm thinking to provide methods that would provide the current functionality so as to not break existing apps but mark those as deprecated. These would potentially be phased out down the line

**Comment by jonahgreenthal** [comment]
That would be great; thanks for continuing to work on this!

**Comment by MaikuB** [comment]
Hmm ran into a bit of problem. AFAIK the original date related classes in Android are rather limited. They can only be used to create a date in the local timezone. Only the newer APIs support creating a date in a specific timezone and that requires being on a minimum version of Android. Perhaps using a library like Joda-Time will help solve the problem. If anyone is willing to help investigate the solution then it would be much appreciated

**Comment by MaikuB** [comment]
I've got a [beta release](https://pub.dev/packages/flutter_local_notifications/versions/1.5.0-beta.1) out with better timezone support that should hopefully resolve the issues with daylight savings. At least it with based on testing I did a spike I did with some native code. May be difficult to get feedback on it but would be much appreciated if you can give it a spin.

**Comment by MaikuB** [comment]
Changes from beta release are now in the stable 1.5.0 release so will be closing this now
