### ISSUE TITLE
Notification Displaying repeated 

### ISSUE THREAD

**Issue by devRaphe** [MaikuB/flutter_local_notifications#1818]
Showing periodic notifications is giving unexpected behavior, I set it to be displayed every minute when the notification arrives it is also displayed multiple times in the notification drawer with the same timestamp, I would also point out that the notification is not displayed every minute when the app is killed, it takes about 20 minutes there about.

here is my code. 
`Future<bool> scheduleTipsNotification(
      {required String title,
      required String body,
      required Duration duration}) async {
    await _flutterLocalNotificationsPlugin.periodicallyShow(
      UtilityMethods.generateUniqueId(),
      title,
      body,
      _getRepeatIntervalFromDuration(duration),
      androidAllowWhileIdle: true,
      NotificationDetails(
        android: AndroidNotificationDetails(
          FitnessPlusStrings.tipsNotificationChannelID,
          FitnessPlusStrings.tipsNotication,
          channelShowBadge: true,
          color: FitnessPlusColors.primaryColor,
          importance: Importance.max,
          priority: Priority.max,
          sound: const RawResourceAndroidNotificationSound(
              FitnessPlusStrings.defaultNotificationSoundWithOutFileExtention),
          enableVibration: true,
        ),
        iOS: const DarwinNotificationDetails(
          presentSound: true,
          sound: FitnessPlusStrings.defaultNotificationSoundIos,
        ),
      ),
    );
    _log.v('Tips Notification scheduled');
    return true;
  }`

Here is a live screenshot, take a look at the notification at 11:03.  
![Screenshot_20221130-111038_One UI Home](https://user-images.githubusercontent.com/72768624/204769462-0108b9b7-6935-487a-a89f-429eafc85ff6.jpg)

Also, while I am here is there any configuration I am missing as to why there is no drop down to view the hidden part of the notification content, all other apps have a drop down button that you can use to view the hidden parts but my app doesn't. help pls.

**Comment by devRaphe** [comment]
@MaikuB Help pls

**Comment by MaikuB** [comment]
The behaviour you get would be because of way you've specifically written your code as there aren't bugs with the plugin around this. If you need more help with your app then note this is something I don't have time/resources to do so you'll need to look elsewhere like Slack, Discord etc for such help. My advice would be that you spend more time understanding how notifications work to achieve what you need to do. It's still your responsibility to look into this as a plugin is a wrapper for native APIs. There's already an example app that shows all the supported features that you can cross-reference as well.

Note the readme also calls out that some manufacturers customise their implementation of Android that can impact how scheduled notifications work. This is outside the control of the plugin. You should validate on a device/emulator running stock Android OS first
