### ISSUE TITLE
Check if a notification is already displayed?

### ISSUE THREAD

**Issue by josephlam1984** [MaikuB/flutter_local_notifications#187]
Is there a way to check if a notification is already displayed on the device?

A sample scenario where this check might be useful:
- App checks for status of something in the background as a service
- App displays a notification if the status matches a defined value
- If the notification is already displayed on the device from a previous background check, the app will not display another notification (a cancel and a show does not work here because it will generate an audible sound/vibration to the user)

**Comment by MaikuB** [comment]
No there isn't. it relies on having a callback on when a notification is shown, which isn't implemented at this point time due to issues I've had with headless execution. Even if that gets added, there is no plan to add this in as none of the notification APIs support this and the responsibility of tracking what's been shown is the responsibility of the application i.e. it's application state
