### ISSUE TITLE
Custom notification sound in not working in ios during firebase push notification

### ISSUE THREAD

**Issue by jobjosekuty** [MaikuB/flutter_local_notifications#1871]
Custom notification sound in not working in ios during firebase push notification
**Sample code to reproduce the problem**
```dart
static void showNotificationOnForeground(RemoteMessage message) async{
    final notificationDetail = NotificationDetails(
        android: AndroidNotificationDetails(
            "com.*********.myapp", "4U_Captain_Flutter_App",
            importance: Importance.max,
            priority: Priority.high,
            playSound: true,
            sound: RawResourceAndroidNotificationSound('notification')),
            iOS: DarwinNotificationDetails(sound:'notification.aiff'
        ));
   await _notificationsPlugin.show(unid++, message.data['title'],
        message.data['body'], notificationDetail,
        payload: message.data['body']);
  }
```

**Comment by MaikuB** [comment]
This doesn't help provide evidence of an issue so please provide a link to a repository hosting code to a minimal app that can reproduce the problem. This should also **not** use Firebase Cloud Messaging (FCM) because this would prove if it's actually an issue with the plugin. I've seen a number of issues where developers get confused between the notifications that come from FCM and those from this plugin

**Comment by MaikuB** [comment]
Closing due to lack of response and issue was likely raised due to confusion between FCM and this plugin
