### ISSUE TITLE
Change local notification Priority for ios

### ISSUE THREAD

**Issue by AliEasy** [MaikuB/flutter_local_notifications#1876]
Is there any way to change notification priority for ios?
Like avoiding `screen on` when pushing notification while phone is locked

**Comment by sh3rlock97** [comment]
iOS: DarwinNotificationDetails(
                  presentAlert: true,
                  interruptionLevel: InterruptionLevel.passiv);

**Comment by MaikuB** [comment]
Thanks @sh3rlock97 for answering. Will close this issue. On a related note, a reminder that the API docs for the plugin is on pub.dev and that you should also be looking at what capabilities there are on iOS in order to use the plugin as the purpose of the plugin is to expose the native APIs. This means there's an implicit prerequisite in knowing how said APIs work and should be part of the research done to then work backwards on what can be done via Flutter
