### ISSUE TITLE
Removing notification

### ISSUE THREAD

**Issue by ugly-soul** [MaikuB/flutter_local_notifications#1884]
**Removing notification**
When I want removing localNotification，I caught it doesn't use "UNUserNotificationCenter.current().removePendingNotificationRequests(withIdentifiers: 'xxxx-xxxx-xxxx')" on Apple devices。In your example ，I just found about use "id"(just int type. Very chicken ribs!) or "tag" to remove notifications, this is extremely inconvenient! 

**rationalization proposal**
I wonder if I might trouble you for provide function？

**Comment by MaikuB** [comment]
Your message seems to be conveying a few different things that I'm not sure is due to using some translation program (sidenote: please use English here, your last message appears to be in Chinese). 

- If you're trying to ask about moving away from using integer IDs. There's no plan for this. Linux uses an integer ID and the primary ID on Android is an integer as well
- The plugin calls the API you are pointing to already. See https://github.com/MaikuB/flutter_local_notifications/blob/f6d3fe1cd7b0da7d15cbc1f8aa462e0cae927a6e/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L835 and https://github.com/MaikuB/flutter_local_notifications/blob/f6d3fe1cd7b0da7d15cbc1f8aa462e0cae927a6e/flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift#L308. If you're after a different usage specific to your application then this is where you should fork for your own purposes
