### ISSUE TITLE
getNotificationAppLaunchDetails() not consuming the notification details

### ISSUE THREAD

**Issue by tratteo** [MaikuB/flutter_local_notifications#1901]
**Describe the bug**
A call to the function `getNotificationAppLaunchDetails()` does not *consume* the notification details.
Further calls to the function will always return the notification that initially launched the app.
This is not usually what is done in other packages such as FirebaseMessaging.

**To Reproduce**
Simply create a local notification, close the app and relaunch it.
Calling the method `getNotificationAppLaunchDetails()` will not consume the notification that initially opened the app. This makes difficult to handle events only once.

**Expected behavior**
If the app is launched by interacting with a notification, further calls to the method should return `null`, as normally is (FirebaseMessaging, FirebaseDynamicLinks).

**Sample code to reproduce the problem**
```dart
var response = await _instance._plugin.getNotificationAppLaunchDetails();
// response is always not null if the application is initially launched by interacting on a local notification
```

**Comment by MaikuB** [comment]
That other plugins behave this way doesn't mean it's a bug as it was actually intentional for this plugin. There were two reasons for this

1. The semantics behind the API. Invoking the method equates to the app ask if a notification launched the app so when called multiple times throughout the same "session", this is actually true that returning `null` is actually incorrect
2. The API is a query so consuming the details and returning null breaks [command-query separation](https://en.wikipedia.org/wiki/Command–query_separation)

Are you able to provide info on where and why you are calling it multiple times? This ordinarily should be called in your application's `main()` function as it is the entry point of the application so that is the appropriate time to query if the app was launched via a notification. AFAIK, `main()` is ordinarily only called once for a normal application "session" too (i.e. ignoring hot reload, restart etc)

**Comment by tratteo** [comment]
Thanks for the reply.
Without the presence of the discussion section, and being the bug report the only template for an issue, I submitted the bug report. Did not mean to accuse of being an actual bug, sorry for the inconvenience.

I basically structured the whole app around the _consuming_ feature of FCM, therefore I was expecting a similar behaviour, thought that maybe I was handling something not in the correct way.

At the moment I refactored the code in a way that is actually compliant with the API.
Closing this, thanks for the reply
