### ISSUE TITLE
android 13 scheduled alarms vs exact alarms

### ISSUE THREAD

**Issue by hichaudh** [MaikuB/flutter_local_notifications#1906]
according to android 14. apps using **SCHEDULE_EXACT_ALARM** will not be enabled by default: https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

Just curious whether this has been recognized by the plugin team and whether there will be any necessary changes to usage of the plugin etc.
Would also be nice to see an update to documentation whether on here or pub.dev

**Comment by MaikuB** [comment]
Could you to help look into this? There isn't a team that works on the plugin as it's maintained by myself (during my spare time) with contributions by the community

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs

**Comment by pranavo72bex** [comment]
Any update on this issue. I am facing this issue in android 14.

**Comment by MaikuB** [comment]
@timobaehr your issue isn't directly (emphasis on directly) related to what was raised by @hichaudh. The point raised by @hichaudh is around how to handle behavioural changes in Android 14. What you're seeing isn't a device-specific either that trying to reproduce this on different devices won't help. If you look the stack trace then this permissions related that means app had a permission revoked that impacts the ability to send a notification at the exact time. Your issue was already reported in https://github.com/MaikuB/flutter_local_notifications/issues/1526 and 14.0.0 made some changes to log an error instead of resulting in a crash and also allowed apps to schedule notifications with inexact timings should they choose to do so

**Comment by MaikuB** [comment]
Changes have been done as part of the 16.0.0 prerelease relating to this and details have been added to the readme as well

**Comment by angelru** [comment]
@MaikuB 
I have this problem on android 14, not on 13, I am new to flutter and with teste plugin, I request permissions but I still get exact_alarms_not_permitted
