### ISSUE TITLE
is there any way to add metod to "periodicallyShow"

### ISSUE THREAD

**Issue by makets** [MaikuB/flutter_local_notifications#191]
i want to call any metod before notification in periodicallyShow for dynamic body message. 
For example get message from http url and periodicallyShow it on body or tittle? How to do that?

**Comment by MaikuB** [comment]
there is no support for doing this as the purpose of scheduling the notifications is that you're suppose have all the information as you're telling the OS "show a me a notification with this title, message etc at these points in time". If you need to handle doing this even when the app is terminated, then I believe you may need to look at doing platform-specific code  (i.e. in Swift/Objective-C for iOS and Android/Kotlin for Java) so that you can schedule periodic jobs that will do those http requests you've mentioned and show the notification once they've been retrieved. If you only care about doing this when the app is running then you may need to look at something like [this](https://github.com/MaikuB/flutter_local_notifications/issues/191). Either way, this is not something that can be done through the notifications package so will be closing this
