### ISSUE TITLE
Payload from activeNotifications alway return null on Android in background isolate.

### ISSUE THREAD

**Issue by ASE55471** [MaikuB/flutter_local_notifications#1912]
**Describe the bug**

The payloads from `await flutterLocalNotificationsPlugin.getActiveNotifications();` always return `null`.

**To Reproduce**

1. Show notification with payload with FirebaseMessaging.onBackgroundMessage()
2. Get playloads from `await flutterLocalNotificationsPlugin.getActiveNotifications();` in background isolate (When onBackgroundMessage triggerd).
3. Get any playload from activeNotifications.
4. All payloads are null.

**Expected behavior**

It should return playload which notification associated with.

**Sample code to reproduce the problem**

```
await flutterLocalNotificationsPlugin.show(0,
        "title", "message", notificationDetails,
        payload: "test");

final activeNotificationsTest = await flutterLocalNotificationsPlugin.getActiveNotifications();

// This return null
print(activeNotificationsTest[0].payload);
```

**Comment by MaikuB** [comment]
This is actually working as expected and not to do with the isolate. If you checked the API docs, you should find that it's documented that the plugin can only return the payload on `iOS` and `macOS`  https://pub.dev/documentation/flutter_local_notifications_platform_interface/latest/flutter_local_notifications_platform_interface/ActiveNotification/payload.html. This is due to a limitation on what can be done via the native APIs
