### ISSUE TITLE
iOS: separate isolate for actions - why?

### ISSUE THREAD

**Issue by kibsoft** [MaikuB/flutter_local_notifications#1983]
Hello! Firstly, I want to thank you for your great plugin! 

Platform: iOS 16
May I ask why it is necessary to start a separate Flutter Engine to handle actions? The problem is that I need to use SQflite when the user clicks any actions, but it only works in the main isolate. I forked your project and turned off the creation of the Flutter engine, and it started to work as I expected.
Diff: https://github.com/MaikuB/flutter_local_notifications/compare/master...kibsoft:flutter_local_notifications:master

After these changes when the app is killed then click on action launches the app but it remains in the background (only **main()** called). Then we can use **getNotificationAppLaunchDetails()** to determine _actionId_ and do something.

**Comment by MaikuB** [comment]
Actions can run on the main isolate provided they have been configured to do so. This is mentioned in the readme at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions where `DarwinNotificationActionOption.foreground` should be specified. This is because this is the only kind of action that requires the app running that would mean there's a main isolate. The rest don't require the app to run so therefore require a background isolate to run

**Comment by kibsoft** [comment]
`DarwinNotificationActionOption.foreground` opens the app, but I don't need it.

> The rest don't require the app to run so therefore require a background isolate to run

The problem is that when `onDidReceiveBackgroundNotificationResponse` is called, `main()` is also called. 
In my case, the Sqflite plugin is initialized twice(main isolate and background), which is forbidden.
Therefore, I have disabled the handling of actions in the background, which means that only `main()` is called but the app doesn't go to the foreground.

**Comment by MaikuB** [comment]
Based on what you said, the issue is more on initialisation happening twice than to do with the isolate being used. A similar issue has been raised at https://github.com/MaikuB/flutter_local_notifications/issues/1932. The FCM plugin has a similar issue as well. Given isolates are only meant to run a single specific entry point, I suspect there's an issue with isolating handling in Flutter as I've not heard of this happening on Android. Perhaps you'll need to put some checks to prevent double initialisation until there's a fix

**Comment by kibsoft** [comment]
Actually, the question is why do we need to handle actions in the background if the main isolate starts anyway? I haven't tested on Android, I say about iOS only.

**Comment by MaikuB** [comment]
The point I was making was `main()` shouldn't be called with to begin with hence why I said I suspect there's an issue within Flutter. In other words, the question is why is the main isolate being started? In saying that, to try to reproduce the issue you said is happening, I tried updating the example app (see https://github.com/MaikuB/flutter_local_notifications/tree/background_isolate_test) to write to and read from shared preferences when `main()` is called. I started the app, triggered a notification with actions by tapping on "Show notification with plain actions"then killed the app without tapping on an action. Only after the app was killed did I tap on the notification action that triggers a background isolate (action 1). I still didn't find an updates to the shared preferences key that fired as a result of tapping on that action that would mean that `main` got fired as well. I'd be curious to see if you can fork the repo to update the example to demonstrate this issue but currently I don't see both isolates firing.

**Comment by kibsoft** [comment]
I can reproduce the issue with your example.
1) When I open the app I can see
> Tapped background false
> Time {current time}
2) Tap 'Show notification with plain actions'
3) Terminate the app
4) Tap 'Action 1' on notification
5) Open the app. The result is:
> Tapped background true
> Time {first launch time}, {time when I tapped the action}

![image](https://user-images.githubusercontent.com/757789/236472839-811d75be-7454-4c35-8ab9-fb6ebb746529.png)

My environment:
```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A380 darwin-arm64)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1
iOS simulator: iPhone SE (3rd generation) (mobile) iOS 16.4 (20E247)
```

**Comment by kibsoft** [comment]
I think the problem with your example is that multiple write operations cannot be performed on the same file simultaneously. To address this issue, I modified the example to use the 'logger' package. https://github.com/kibsoft/flutter_local_notifications/tree/background_isolate_test

I used the iOS simulator to reproduce this issue, and the log files can be found in the following directory:
`/Users/{your_username}/Library/Developer/CoreSimulator/Devices/{device_uuid}/data/Containers/Data/Application/{app_uuid}/Library/Application Support`
**NOTE: replace {your_username}, {device_uuid}, {app_uuid} with your values**

**Comment by MaikuB** [comment]
Tried your one and can't reproduce it either. I opened `main.log` to show the log entry that gets written when app starts and then opened it again after tapping on the action after the app was terminated and the same log entries remained

https://user-images.githubusercontent.com/25263378/236589755-cee327c2-e21e-4c22-9f1f-d7979f462d6b.mov

I saw you used to have a reply that I assume you deleted where you tried my example without your changes and said you were able to reproduce it but when you say

> Open the app. The result is:
> Tapped background true
> Time {first launch time}, {time when I tapped the action}

That second time is really from running the app again and so same behaviour again. Not sure if you deleted the message because you realised this but even with these changes to log to a file, it's led to the same outcome where `main()` isn't called. I don't see `main()` called either if it had a code to call `print()` and the action was called when the app is running

**Comment by kibsoft** [comment]
> That second time is really from running the app again and so same behaviour again
Yep, I realised that and then deleted the message.

Here is a video of the reproduced issue(can't upload more than 10MB on GitHub): https://www.dropbox.com/s/gnt9u69cq4vt1he/ios_main_issue.mov?dl=0

My environment:
```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A380 darwin-arm64, locale ru-RU)
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

iOS 16.4 on simulator
```

And what's yours?

**Comment by MaikuB** [comment]
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale
    en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

Regardless of what SDK we have and what you're seeing, I believe this something you're better of reporting to the Flutter team as a background isolate should only be triggering the function that was specified. That the background isolate is meant to call the specific function where it's considered another entry point is how it's been communicated by the team before as well. If you can't reproduce this on Android either then it helps provide an argument that there's inconsistencies in the implementation across multiple platforms. Not sure how much luck they'll have reproducing it given I can't.

**Comment by kibsoft** [comment]
Okay, got it. Thank you for your answers. I believe we can close this issue in light of this.

**Comment by raphire08** [comment]
@kibsoft 

were you able to find any alternative for this ?

**Comment by kibsoft** [comment]
@raphire08 yes, I write some data to a file from the background isolate (_notificationTapBackground_) and then listen to it in the main isolate using _DirectoryWatcher_. This allows us to use only one instance of Sqflite.
