### ISSUE TITLE
Custom Long Sound

### ISSUE THREAD

**Issue by zakarya-dev** [MaikuB/flutter_local_notifications#1986]
Hello, I added custom sound with 3 to 4 seconds it works fine, but when I add a long sound with one minute or more it works on emulator but it doesn't work on real device, like azan sound, I added an azan sound but it doesn't work(I mean the sound does not work, but the notification works fine but it only vibrates), does anyone face this issue? or added a long sound and worked?

here is my notification code, it works perfectly on the emulator, but it doesn't work on real device, tested with Xiaomi 11T, Huawei Mate 10 Lite, Honor X7,

![Screenshot 2023-05-08 221219](https://user-images.githubusercontent.com/77733277/236911919-74bc4f53-be4d-4961-9e4e-70363896c3db.png)

**Comment by MaikuB** [comment]
Note that this issue is outside of the plugin as its responsibility is to call the native platforms APIs. This means what you see is what you get. Furthermore, a lot of various Android manufacturers customise their own implementation of Android that it doesn't behave like the stock Android OS that's used on the emulator or say, a Pixel device. A generic search via Google would reveal issues/posts like https://stackoverflow.com/questions/46587759/maximum-sound-duration-on-android-notification. This means there's nothing you can really do about this and may need to find a different approach to this to play a longer sound that you want that I can't advise you on or limit the length of the audio file.

**Comment by zakarya-dev** [comment]
fixed by adding keep.xml to raw folder
