### ISSUE TITLE
Improvement to `onDidReceiveBackgroundNotificationResponse` callback example

### ISSUE THREAD

**Issue by dfilter** [MaikuB/flutter_local_notifications#2048]
After reviewing the `README` and the example application provided, I still am struggling to understand what `onDidReceiveBackgroundNotificationResponse` can be used for. How can this callback be used to interact with the rest of the application if it starts a new engine? Maybe I'm missing some key concept but I think it would be helpful to expand the example application to perhaps display a widget with the action payload.

**Comment by MaikuB** [comment]
> How can this callback be used to interact with the rest of the application if it starts a new engine

Perhaps the confusion here is that it's because you're wanting to interact with the rest of the application when that's (ideally) not the scenario for it. Consider an example where a notification appears to remind you about an event and there's an action button with the text "Dismiss". A user tapping on it would cause the notification be removed and doesn't interact with the rest of the application. This would be an example of where this applies. Interactions with the app should really be done on the main isolate and it's mentioned in the readme which settings should be used for this to happen. This would be similar to a regular notification without action buttons where tapping on it can launch the app if it's in a terminated state or trigger `onDidReceiveNotificationResponse` if it's running so you can interact with a widget

> Maybe I'm missing some key concept but I think it would be helpful to expand the example application to perhaps display a widget with the action payload.

This is already covered and you can check by tapping on the action related to https://github.com/MaikuB/flutter_local_notifications/blob/44158f840fdba642c94d02a7858f468bd01494ec/flutter_local_notifications/example/lib/main.dart#L130 and https://github.com/MaikuB/flutter_local_notifications/blob/44158f840fdba642c94d02a7858f468bd01494ec/flutter_local_notifications/example/lib/main.dart#L1112. These should trigger the app to go to another page and show the payload

**Comment by dfilter** [comment]
Thanks for the explanation, I've reviewed those examples you've pointed out and I think I understand where I was getting confused. Since you're satisfied with the coverage of this concept in the example app I'll go ahead and close this issue.
