### ISSUE TITLE
didReceiveLocalNotificationCallback not called on iOS

### ISSUE THREAD

**Issue by kakkoisan** [MaikuB/flutter_local_notifications#205]
@override
  void initState() {
    super.initState();
    getDataFromDB();
    var initializationSettingsAndroid =
    new AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = new IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidRecieveLocalNotification);
    var initializationSettings = new InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    NotificationManager().sharedNotificationPlugin().initialize(initializationSettings,
        onSelectNotification: onSelectNotification);
    print(NotificationManager().sharedNotificationPlugin().didReceiveLocalNotificationCallback);
  }

  Future onSelectNotification(String payload) async {
    print('clicked');
  }

  Future onDidRecieveLocalNotification(int id, String title, String body, String payload) {
    print('received');
  }

onSelectNotification is called correctly, but onDidRecieveLocalNotification can't

**Comment by MaikuB** [comment]
Which version of iOS are you running on? It's only supposed to be applicable to iOS versions before 10 (note: this is documented)

**Comment by kakkoisan** [comment]
> Which version of iOS are you running on? It's only supposed to be applicable to iOS versions before 10 (note: this is documented)

Sorry, I am running at iOS12. So I cant call any functions when I receive the notifications?

**Comment by MaikuB** [comment]
not at this stage, no

**Comment by FineTillYouCameAlong** [comment]
How about if the app is in foreground? Should this make a difference whether onDidReceiveLocalNotification gets called? Because I am getting a notification when the app is in foreground. In your docs it says

> By design, iOS applications do not display notifications when they're in the foreground. For iOS 10+, use the presentation options to control the behaviour for when a notification is triggered while the app is in the foreground.

How would I do this in Flutter?

**Comment by MaikuB** [comment]
See API docs https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/IOSInitializationSettings-class.html

If you take a look there the default values are already set to true so you shouldn't need to worry about it out of the box as that's likely what most developers would want. The exception here you would need to handle it for older versions of iOS but only if plan to target those on iOS versions before 10. 

What was written in the docs the presentation options about foreground behaviour was for informational purposes since there are going to be developers that might not go read further about how things work on iOS.

There's an example app in the repo that you can run to see how it works, if you run on, say, an iOS 9 simulator you don't get a notification when the app is in the foreground but will trigger `onDidReceiveLocalNotification `
