### ISSUE TITLE
[Android] Cannot get callback `onDidReceiveNotificationResponse`  in case application has multiple Activities

### ISSUE THREAD

**Issue by nhanvhn** [MaikuB/flutter_local_notifications#2050]
. In case, application has multiple Activities and activity use to show  notification is not started with
```
<intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
```
it will no callback `onDidReceiveNotificationResponse`

.Example: `Splash Screen` (Laucher) - native code -> `Auth Screen` - native code -> `Main Screen` (more feature) - only Flutter code.
When I show a notification in `Main Screen` -> then I click on that notification -> I cannot get callback `onDidReceiveNotificationResponse` because peddingIntent will start again `Splash Screen`

. Here is problem:
```
protected static Notification createNotification(
      Context context, NotificationDetails notificationDetails) {
    NotificationChannelDetails notificationChannelDetails =
        NotificationChannelDetails.fromNotificationDetails(notificationDetails);
    if (canCreateNotificationChannel(context, notificationChannelDetails)) {
      setupNotificationChannel(context, notificationChannelDetails);
    }
    Intent intent = getLaunchIntent(context);
    intent.setAction(SELECT_NOTIFICATION);
    intent.putExtra(NOTIFICATION_ID, notificationDetails.id);
    intent.putExtra(PAYLOAD, notificationDetails.payload);
    int flags = PendingIntent.FLAG_UPDATE_CURRENT;
    if (VERSION.SDK_INT >= VERSION_CODES.M) {
      flags |= PendingIntent.FLAG_IMMUTABLE;
    }
    PendingIntent pendingIntent =
        PendingIntent.getActivity(context, notificationDetails.id, intent, flags);
```

When create a notification, you use `getLaunchIntent(context)` to push pendingIntent. If a project was developed by only Flutter (with single Activity) => that code will execute right. But with a project with mutiple Activity, that code may execute wrong. As my project, my LAUCHER activity is not current activity that show notification so when I click on notification, I cannot get callback in function `onDidReceiveNotificationResponse`.

. My suggestion:
I see you get current Activity in `onAttachedToActivity`
```
public void onAttachedToActivity(ActivityPluginBinding binding) {
    binding.addOnNewIntentListener(this);
    binding.addRequestPermissionsResultListener(this);
    mainActivity = binding.getActivity();
```

so when we create a pendding intent for a notification if we can use `mainIntent` first then to `getLaunchIntent(context)` I think we can use this package for case have multiple Activity

**Comment by MaikuB** [comment]
I believe I get your problem though don't understand what you're trying to propose as the solution. Could you clarify what you're suggesting? In saying that, I have some thoughts that may be worth reading through first. From what you've described and based on my understanding (welcome to provide more input), I'd question if this may well be a case where this plugin isn't suitable for your app that you would need have your own custom solution or consider using your own fork. I'm saying this based on what you said around

> As my project, my LAUCHER activity is not current activity that show notification so when I click on notification

There's really not meant to be any dependency on which activity you see when a notification is shown. Another part is that a launcher activity is means an activity that gets launched in response to an intent e.g. tapping on a notification. This is separate to the an activity that may be visible on screen as you're talking about. Moreover, it's possible that a user may tap on a notification when the application isn't running at all. This is why the plugin needs be to able to identify the launcher activity so that if the user taps on a notification, it starts the appropriate launcher activity that in your case is the splash screen. If my understanding was correct, you're proposing that the plugin find out which activity is visible when a notification appears so that is where the intent goes to but this doesn't work with the scenario I mentioned on when an app is killed. 

You also mention

> I see you get current Activity in onAttachedToActivity

Strictly speaking, it doesn't get the current activity, it gets the activity associated with a Flutter engine. Whilst in your case that should be the one where your app is built with Flutter and receives the callbacks, it potentially solves the callback issue only to introduce the problem I alluded to earlier where it won't start the appropriate launcher activity when the app is in a terminated state. Even if this scenario was desirable for your scenario, that would be specific to your scenario and not necessarily applicable for everyone else
