### ISSUE TITLE
about IOS notification that do not produce sound in most of the devices 

### ISSUE THREAD

**Issue by AGDesig** [MaikuB/flutter_local_notifications#2058]
So i want your development team to notice this that you package do not work properly on IOS. 
1. On IOS Firebasemessaging,onBackground(handler); does not initiate.
2. On IOS it do initiate once but when  _flutterLocalNotificationsPlugin this function do not work on many IOS devices like Iphone 8 and other it wont produce sound it just go through the whole function but do not work at all.
3. i am using FlutterMessaging to get notification. when notification recieve only this function

 Future forgroundMessage() async {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
  }
function calls not the background function on IOS
i know its a firebase messaging package fault but when it go through this function your _flutterLocalNotificationsPlugin never calls even on background 
4. i dont know i tried to research everything on your github to find the function that triggers background notification but on Android it automatically does everything but on IOS it never goes through out the background functions or any function that is on firebasemessaging and flutter local notification services.
5. we even added native code that you provide on documentation but still we were almost give up. i hope you will see this problem and try to send the solution or fix this in future. no sound produce on many of the devices no notification trigger on background nor the sound. the problem is with the sound system. i am also gonna report the bug on firebase messaging as well. even i have enable sound: true, but it never produce sound when notification arrives. i am using alert type notification but no sound is produce on any of the case. PLease recheck your package on IOS let me know the proper procedure and please update your documentation and provide deep details about how to integrate flutter_local notification on IOS. full and final details everything. and tell in which devices it can run and what to do for older devices like iphone 8 10 11 etc even more older.

Regards

**Comment by MaikuB** [comment]
I don't understand most of what you're saying as it doesn't make sense from an English point of view. What is written in points 1 and 2 already contradicts each other. You also make references to variables (`_flutterLocalNotificationsPlugin`)  and methods (`forgroundMessage`) that belong to your own as though you expected that I had seen your app.

If you believe there is a bug then you will need to provide a link to repository hosting a minimal app that can reproduce the problem. I won't be investigating issues unless evidence has been provided as it's not sustainable for me to do so otherwise. Note that I do not look through each person's own to get it working either. If you're in need of something like that you'll need to elsewhere like Slack, Discord etc.

Currently, nothing you've written has showed that you tried to use FCM on its own try to isolate the problem. If you thought you have then it's not come across clearly with what you've ended up writing. Furthermore, as you have alluded to, most of what you've written about is to do with FCM and you've been the only person to report this. What you've written about seems to confuse FCM and this plugin. With the code you've shared and when you say

> i know its a firebase messaging package fault but when it go through this function your _flutterLocalNotificationsPlugin never calls even on background

this would indicate you don't understand how FCM works and have not properly gone through its documentation. Whether or not a notification plays a sound or not isn't dependent on phone either.

Respectfully, with what you've shared (e.g. with how you implemented the code that FCM says needs to be done), it looks like you need to improve your reading ability before trying to assign the blame to someone else. With what you said about not wanting links, note that understanding how each platform works is a prerequisite.  Not reading through each platform's documentation is irresponsible as you'd be building apps targeting specific platforms without trying understand how they work, what features they offer and the constraints . If you're struggling to communicate with due to lack of proficiency in English then I suggest you reach out to the development community through other channels that may speak in your native tongue.

I would also like to remind you that open-source software is provided as is and you can read the license terms at https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/LICENSE. There isn't a development team behind this plugin, I'm a developer who spent my spare time learning the associated languages to build this library and share it with the community. Others in the community have also contributed to it and it is provided for free. Maintainers do not actually have an obligation to provide support and what you've been written shows a sense of entitlement and lack of empathy around how you're requesting others to spend their free time for you. With that in mind, I'd ask that you be mindful of your tone when engaging with others on GitHub in the future. Open-source burnout is a real problem and there are maintainers who abandon their projects due to issues like lack of contribution, people showing entitlement etc
