### ISSUE TITLE
Setting off vibration does not take effect and still triggers vibration

### ISSUE THREAD

**Issue by laterdayi** [MaikuB/flutter_local_notifications#2167]
Setting off vibration does not take effect and still triggers vibration

```
    const AndroidNotificationChannel androidNotificationChannel = AndroidNotificationChannel(
      'channelIdNewMessage',
      chdNewMessage',
      description: 'chdNewMessage',
      enableLights: false,
      enableVibration: false,
      showBadge: false,
      importance: Importance.max,
    );
    await _flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(androidNotificationChannel);
```
```
  static const androidChannelNewMessage = AndroidNotificationDetails(
    'channelIdNewMessage', "chdNewMessage",
    importance: Importance.max,
    priority: Priority.max,
    enableVibration: false,
    channelShowBadge: false,
    visibility: NotificationVisibility.public,
  );
```

**Comment by MaikuB** [comment]
Please check the [API docs](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/enableVibration.html) as it specifically says 

```
For Android 8.0 or newer, this is tied to the specified channel and cannot be changed after the channel has been created for the first time.
```

Sounds like you continued to use the same channel, changed the value and expected it to work. If you're still developing then you can uninstall the app. Otherwise, you need to use a different channel

**Comment by udoy-touhid** [comment]
I turned off sound programmatically but it was still playing.

@MaikuB thanks for the insight! really helpful. Your reply solved my issue after hours of debugging.
Same is true for notification sound and some other properties.
