### ISSUE TITLE
 Local notifications not working on iOS release mode 

### ISSUE THREAD

**Issue by zhaoweiguo5505** [MaikuB/flutter_local_notifications#2178]
I'm using the [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) package to display notifications in and outside the app (background mode). Everything is working as expected on Android (debug + release) and iOS debug mode but, strangely, local notifications are not displayed in background mode for iOS release.
 
  
  
  
![image](https://github.com/MaikuB/flutter_local_notifications/assets/34048223/d2ffc2b3-23f0-43d0-ac7e-3a776c7b015d)

![image](https://github.com/MaikuB/flutter_local_notifications/assets/34048223/a1978f3a-17ff-4aeb-a559-8f1e582fa9fc)

**Comment by aubryjn** [comment]
Same problem for me.
Works in Android debug + Release mode, works in iOS debug mode and only foreground in release mode. I never get notifications in background release mode.

**Comment by hortigado** [comment]
Same not work on android realease mode

**Comment by MaikuB** [comment]
The plugin doesn't have any code or do anything that requires additional configuration for release mode when it comes to iOS. Android does due to how it processes like resource shrinking and minification. As such there's not much I can do to advise on how to solve this beyond checking the configuration/code for your own app in case there's something you've done specific to you. I had checked the example app on release mode on my iPad as well to double check and can confirm that it's working. If there's an issue with the plugin that was iOS-specific then I would also expect this issue to be more widely reported as the plugin has existed for a very long time. Closing due to what I've mentioned.

@hortigado your issue isn't the same as the @zhaoweiguo5505. There are instructions for the plugin that is in the readme that is specific to Android for release builds that you should check

**Comment by Levi-Lesches** [comment]
Make sure you're following all the instructions in the readme for your platform and that you have all the necessary permissions from the user/apple if that's relevant

**Comment by tangdongchuan520** [comment]
解决了吗？
