### ISSUE TITLE
how i can listen when notification appear

### ISSUE THREAD

**Issue by minh98** [MaikuB/flutter_local_notifications#222]
i see IOSinit have callback 
var initializationSettingsIOS = new IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidRecieveLocalNotification);
but androidinit don't have

**Comment by MaikuB** [comment]
If you look at the documentation around `onDidReceiveLocalNotification`, you'll see that it's really only for a specific scenario on older versions of iOS due to how the notifications API works on those older versions. There's no support for knowing when a notification appears at this stage. I've tried implementing this before but looks like there are some issues to be resolved within the Flutter engine

**Comment by minh98** [comment]
oh If you don't plan to do it in the future, close it.

**Comment by MaikuB** [comment]
i'll close it as it doesn't really need to remain open as it's something i looked into before and will look to add
