### ISSUE TITLE
[Question] How can i route application when it has been terminated?

### ISSUE THREAD

**Issue by Raonshi** [MaikuB/flutter_local_notifications#2227]
Hi. I'm making a mobile alarm application using flutter_local_notifications and go_router.

When I use flutter_local_notifications, I want to set route path dynamically.

For example, There are two pages. HomePage and AlarmPage.
When user execute application by tapping app icon, the initial route should be HomePage. On the other hand, when user execute application by tapping notification, the initial route should be AlarmPage.

If you need some code to understand my situation, I will offer some code to you.

**Comment by burhanaksendir** [comment]
Hi, I understand your scenario. You can achieve this by checking whether the app was opened from a notification or not. If opened from a notification, navigate to the AlarmPage; otherwise, navigate to the HomePage.

Here's a simplified example in Dart:

`import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  var initializationSettingsAndroid =
      AndroidInitializationSettings('app_icon');

  var initializationSettings =
      InitializationSettings(android: initializationSettingsAndroid);

  await flutterLocalNotificationsPlugin.initialize(initializationSettings);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: determineInitialRoute(),
      routes: {
        '/home': (context) => HomePage(),
        '/alarm': (context) => AlarmPage(),
      },
    );
  }

  String determineInitialRoute() {
    // Check if the app was opened from a notification
    // You need to implement the logic to check this based on your app's setup
    bool openedFromNotification = true; // Replace this with your actual check

    return openedFromNotification ? '/alarm' : '/home';
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home Page'),
      ),
      body: Center(
        child: Text('This is the Home Page'),
      ),
    );
  }
}

class AlarmPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Alarm Page'),
      ),
      body: Center(
        child: Text('This is the Alarm Page'),
      ),
    );
  }
}
`
In this example, the determineInitialRoute function checks if the app was opened from a notification. You'll need to replace the placeholder openedFromNotification with your actual logic to determine this. If opened from a notification, it sets the initial route to '/alarm'; otherwise, it sets it to '/home'. Adjust this logic based on your app's requirements.

**Comment by MaikuB** [comment]
This is covered in the readme and example app already. Please take a more thorough look through both of these e.g. As the purpose of the plugin is to call the native APIs
