### ISSUE TITLE
About "int java.lang.Integer.intValue()' on a null object reference" crash.

### ISSUE THREAD

**Issue by tall-nuts** [MaikuB/flutter_local_notifications#2261]
I've seen a lot of user feedback about this bug, and I've had the same problem myself. I passed the debug debugging, found the cause of the crash is the user is not in "AndroidNotificationDetails" pass "icon" parameter, while the official document only transfer notification icon at initialization time. The user is not instructed to pass this necessary parameter when creating notifications. This issues is put forward to help all users solve this problem.

debug:
![image](https://github.com/MaikuB/flutter_local_notifications/assets/9261499/142ce574-3c9d-4c54-8487-5552f5376113)
![image](https://github.com/MaikuB/flutter_local_notifications/assets/9261499/828bf62c-1871-453e-9115-7ebee29f8972)

solution:
![image](https://github.com/MaikuB/flutter_local_notifications/assets/9261499/2ff519d0-7247-4e8f-ac1e-75484db896ee)

Is this also a bug? Why is defaultIcon set during initialization, but it does not take effect.
![image](https://github.com/MaikuB/flutter_local_notifications/assets/9261499/6d0d2664-a634-4cc8-9bd8-323e04092583)

**Comment by MaikuB** [comment]
If by official document, you mean readme then that the reason it doesn't specify when the notification is created is because a default icon is specified during initialisation. This makes specifying it for each notification redundant. This is reliant on developers making sure they do the initialisation as based on the name of the method and mentioned in the documents. If you believe there is a bug and have actually done the initialisation before trying to show the notification then please provide a link to a repository hosting code for a minimal app that can reproduce the issue

**Comment by MaikuB** [comment]
Closing due to lack of response with steps to reproduce. One thing I should also point out is that if you use initialisation method to specify the default icon, it should be done before attempting to show any notifications. This method is also asynchronous but I can see the method you have being synchronous so the initialisation won't be awaited properly
