### ISSUE TITLE
notification occuss twice when handle with fire base

### ISSUE THREAD

**Issue by qwicksoftteam** [MaikuB/flutter_local_notifications#2330]
@pragma('vm:entry-point')
Future<void> _firebaseRemoteMessageHandler(RemoteMessage message) async {
  print('Handling a background message ${message.messageId}');
  await Firebase.initializeApp(options: AppConfig.firebaseOptions);
  print('firebase initailized');
  await setupFlutterNotifications();
  showFlutterNotification(message);
}

Future<void> firebaseFCMlistern() async {
  await Firebase.initializeApp(options: AppConfig.firebaseOptions);

  FirebaseMessaging.onMessageOpenedApp.listen(_firebaseRemoteMessageHandler);
  FirebaseMessaging.onMessage.listen(_firebaseRemoteMessageHandler);
  FirebaseMessaging.onBackgroundMessage(_firebaseRemoteMessageHandler);
}

**Comment by Prince2347X** [comment]
This behavior is happening because firebase_messaging plugin automatically sends a push notification if the notification object is passed in its data (coming from FCM)... To avoid this, just pass the data without notification via FCM since you're already handling the data to show a local notification.

**Comment by MaikuB** [comment]
@Prince2347X has answered this so please make sure you understand how FCM works. Will be closing this issue
