### ISSUE TITLE
Remove Exact alarm permissions permission By Play store policy

### ISSUE THREAD

**Issue by shresthaashok** [MaikuB/flutter_local_notifications#2337]
- I am using schedule notification from last year it's working fine previously but it hasn't worked recently and Google warned me to remove " <uses-permission android:name="android.permission.USE_EXACT_ALARM" /> " this permission.
And only able to add this permission  If my app is a clock or an alarm. So how do I use this permission for my app my app does not alarm or clock but I have schedule notifications.

**Comment by shweta-alike** [comment]
@shresthaashok Did you find anything?

**Comment by MaikuB** [comment]
You've not mentioned which permission specifically but sounds like you're referring to `USE_EXACT_ALARM` as Google says it's only for calendar and alarm clocks.  If so, Google had already stated in their own docs that this was subject to their approval that implied there was risk involved and was relayed in the plugin readme https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#androidmanifestxml-setup. When they introduced changes in Android 14, they had provided guidance on this as well (see https://developer.android.com/about/versions/14/changes/schedule-exact-alarms) and the plugin was updated in 16.0 to accomodate. The section I linked to earlier in the readme also mentions this. Have you checked this?

**Comment by jiayixu420** [comment]
Hi! @MaikuB I added the permissions below to the AndroidManifest.xml file and published the app to Google Play Store.

<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.USE_EXACT_ALARM" />

However the publishing failed due to Exact Alarm permission.

Publishing failed :|
Google Play failed to upload artefacts. You must let us know whether your app uses any exact alarm permissions: {
    "error": {
        "code": 403,
        "message": "You must let us know whether your app uses any exact alarm permissions",
        "status": "PERMISSION_DENIED"
    }

Could you please check this issue?
