### ISSUE TITLE
Show notification from backgroundtask don't work

### ISSUE THREAD

**Issue by tb2761** [MaikuB/flutter_local_notifications#234]
**Describe the bug**
When i try to show a notification from backgroundtask, nothing happens. I use backgroundfetch to fetch data also when app is closed and want to show a notification.

**Expected behavior**
Show notification from backgroundtask also when app is closed, without schedule it.

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment]
Could you please provide a sample to reproduce this and provide details on which platform(s) you have issues on?

**Comment by tb2761** [comment]
Link to sample project: https://github.com/tb2761/flutter_local_notifications_issue

Platfrom is Android 7.0 and 9.0. Devices are a Nokia 7 Plus, Google Pixel 3 XL and Samsung Galaxy Tab S2.

**Comment by MaikuB** [comment]
Looking at the code and logs, I saw two issues. First one is that the notification won't be shown even without the use of the background-fetch plugin as a valid icon for the Android notification hadn't been provided and an exception was thrown to indicate this. The other issue is that you'd see after fixing that issue is a null reference exception. The `FlutterLocalNotificationsPlugin` class needs to be instantiated within the function used for headless execution as it runs in its own context when the app is terminated.

I'd suggest inspecting the logs more closely if you haven't been already. For reference, I saw these in VS Code's debug console. The null reference exception appeared without the need to have a debug session running provided I had started one beforehand. If you're using Android Studio, you should be seeing these in Logcat

**Comment by tb2761** [comment]
Yeah, now it works perfectly. Thanks for the fast support.

The wrong icon was an issue only in the sample app, but the instantiation was the solution. 
But I didn't see any exceptions, but this should be a personal problem.
