### ISSUE TITLE
[Android] When matchDateTimeComponents is dayOfWeekAndTime, zonedSchedule fires before scheduledDate.

### ISSUE THREAD

**Issue by ikoamu** [MaikuB/flutter_local_notifications#2346]
Hello and thank you for putting in the work to do this.

**Describe the bug**

When `matchDateTimeComponents` is `dayOfWeekAndTime`, `zonedSchedule` fires before `scheduledDate`.

**To Reproduce**

1.  Execute the following function at 8:00PM on June 19, 2024.
```dart
    await flutterLocalNotificationsPlugin.zonedSchedule(
      notificationId,
      title,
      body,
       tz.TZDateTime(
        tz.local, 2024, 6, 25, 21,
      ),
      matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
      NotificationDetails(
        android: AndroidNotificationDetails(
          channelId,
          channelName,
          channelDescription: type.channelDescription,
        ),
      ),
      androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.wallClockTime,
    );
```

2. Notification sent on June 19, 2024  at 9:00PM.
I think the notification should be sent for the first time on June 25, 2024 at 9:00 PM.

**Expected behavior**

When matchDateTimeComponents is dayOfWeekAndTime, the notification should be issued at the time after scheduledDate.

I understand the points that need to be corrected, so I am creating a pull request. If there are no issues, please merge it.

**Comment by MaikuB** [comment]
Thanks for the compliment and raising the PR. However, if you look at the API docs then is documented as expected behaviour. It isn't a bug and is like this as it aligns with how it works on Apple platforms and the semantics behind it. This is where from a semantica point of the request is to have a recurring notification that matches the rule with matching the date/time components of the date/time value. This is different from asking for a notification to first trigger on the given date and then make it recurring afterwards. Apple's own APIs do not support this

**Comment by ikoamu** [comment]
I apologize for not being able to explain it better.
The problem is only occurring on Android. iOS works fine.

Android also works fine with [this PR](https://github.com/MaikuB/flutter_local_notifications/pull/2347) fix. Could you please check?

**Comment by MaikuB** [comment]
No need to apologise as I understood what you meant. I'm not sure if you understood what I said though. What I'm saying is it doesn't behave the way you expect it to. In other words, your PR would introduce inconsistency between iOS/macOS and Android. This is based on my testing and Apple's own documentation at https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger. If you read the docs it says 

```
You use an [NSDateComponents](https://developer.apple.com/documentation/foundation/nsdatecomponents) object to specify only the time values that you want the system to use to determine the matching date and time.
```

Note how they talking about matching. It's not about having a notification scheduled such that the first instance happens on the given date and time. You're expecting it to behave that way but Apple states that it doesn't

I also reconfirmed this by testing a similar scenario to what you described. Video is below where it the date specified is 28th of June but will fire today because the specified matching pattern is day of week (Friday) and time (6:40pm). It fires today on the 21st, not on the 28th like you would have expected


https://github.com/MaikuB/flutter_local_notifications/assets/25263378/843c35a0-d7d6-445d-bb6c-552cad6318e4

**Comment by ikoamu** [comment]
Thank you for explaining it to me so carefully!
It seems that due to my poor method of verifying the behavior on my iOS device, it appeared as if iOS and Android were behaving differently.
I also understood about the matching behavior. I will withdraw the PR.

By the way, is there an appropriate method to achieve what I want to do (registering weekly notifications starting from the following week and beyond)?

**Comment by MaikuB** [comment]
> By the way, is there an appropriate method to achieve what I want to do (registering weekly notifications starting from the following week and beyond)?

Not to my knowledge

**Comment by ikoamu** [comment]
OK.
Thank you.
