### ISSUE TITLE
Possibility to listen Notification changes.

### ISSUE THREAD

**Issue by KlausJokinen** [MaikuB/flutter_local_notifications#235]
Currently you can get pending notifications which returns a future, would it be possible to create a stream which would trigger when Notification is removed / added.

**Comment by MaikuB** [comment]
The reason that call returns a future is because any of code to get access to native platform APIs goes via platform channels and is done asynchronously. What kind of use case are you looking to cover? If a notification is scheduled then it's really considered added at the point so there doesn't seem any value in having a stream for that scenario.

Once improvements have been done on background execution within the Flutter engine itself, I'm looking to provide a callback on when a notification is shown so that should tell you when a notification has been removed

**Comment by KlausJokinen** [comment]
I'm building an app which uses a lot of notifications, currently I'm tracking incoming notifications via PendingNotifications method. For me it just would be easier if it would be a Stream. Nothing else.

**Comment by MaikuB** [comment]
Sorry still no seeing why much of a case for a stream based on the information you've provided. Regardless, I still don't much of a case for having a stream. Having a callback for when a notification is shown would overlap and has more functionality as it could be execute headless Dart code i.e. run code when the app is terminated. Streams wouldn't allow for this. Thus, I don't see this being added. Since the code is open source though, you're more than welcome to make modifications so that a stream is provided if helps your scenario.

**Comment by KlausJokinen** [comment]
> Sorry still no seeing why much of a case for a stream based on the information you've provided. Regardless, I still don't much of a case for having a stream. Having a callback for when a notification is shown would overlap and has more functionality as it could be execute headless Dart code i.e. run code when the app is terminated. Streams wouldn't allow for this. Thus, I don't see this being added. Since the code is open source though, you're more than welcome to make modifications so that a stream is provided if helps your scenario.

I just re-read your answer and you're absolutely right. Those Callbacks will be more than enough..

**Comment by MaikuB** [comment]
Will close this as I will look into headless execution once that's matured more so to speak. Open to PRs from the community as well
