### ISSUE TITLE
Android and IOS notification behaviour is different

### ISSUE THREAD

**Issue by gdhananjay** [MaikuB/flutter_local_notifications#2402]
Notification actions:
My need is notification for calling app in flutter , where call notification comes as notification with accept and decline button.

In android it looks good, but problem is with IOS , by default i have to pull down (swipe down) the notification to see notification actions, and no way to give custom look for accept and decline button. 
I run your sample example app. Notification actions looks different in android and in ios. 

Below are screenshot when i click on show "notification with plain actions"

Android:

<img width="510" alt="image" src="https://github.com/user-attachments/assets/1fe8a82b-978c-47ef-a398-5bc8abd79825">

IOS: 

<img width="411" alt="image" src="https://github.com/user-attachments/assets/5db0ad4d-03a5-4340-af2a-639d12d853e5">

1. UI should look same
2. Why i need to pull down (swipe down) on IOS notification. (because of this i cannot add calling notification which has accept and decline buttons)

Regards,
Dhananjay.

**Comment by MaikuB** [comment]
It is like this because this is how each platform/OS works. The plugin's purpose is to expose the native APIs so developers are really supposed to understand how each platform works beforehand. Putting aside this plugin, developing an app for different platforms requires understanding their capabilities as well

If you have a need for UI to be the same then you'll need to do your research around this to see what is and isn't possible. It may be that you need your own custom solution or that you develop within constraints
