### ISSUE TITLE
Notifications not being received in Android on Battery restriction 

### ISSUE THREAD

**Issue by ccbernardo** [MaikuB/flutter_local_notifications#2414]
**Describe the bug**
I've an application that depends a lot on push notifications, some users with battery optimisation/restriction aren't receiving notifications when the app is closed ( with the app in background it's ok) but as soon as they open the app the push are coming immediately.

**To Reproduce**
just using the app the battery optimisation turned on 

**Expected behavior**
Receiving notifications without constraints.

**Comment by MaikuB** [comment]
This plugin is for local notifications not push notifications. Push notifications are also referred to as remote notifications as they're remotely triggered. In other words, a server pushes the notification to the device. If your issue is really on push notifications then you'll need to check the docs for the service you're using for push notifications for guidance around this.
