### ISSUE TITLE
Scheduling notifications

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [MaikuB/flutter_local_notifications#2417]
I don't know if I'm misunderstanding this but scheduling notifications seems very complicated now. I have to use some `timezone` dependency from an unverified uploader which is very suspicious. I just want to schedule a notification 8 minutes in the future. Is this possible with flutter_local_notifications without these suspicious dependencies?

**Comment by MaikuB** [comment]
Being a verified publisher doesn't amount to much as all that requires is owning a domain and verifying that you own the domain. This can be done by anyone. There are other popular packages in the ecosystem that aren't tied with a publisher either. As for the `timezone` package itself, if you think it is suspicious then you've likely not have vetted the dependency enough since the package is actually being worked on by Google team members.

As for why it is used, this is because timezones and daylight savings. Even if you were to write it natively, x minutes in the future still needs to translate to a date. As the plugin needs to consider general use cases, the it also needs to ensure that the date specified respects the timezone given even if daylight savings takes place. If this too complicated for you then you can write your custom code via platform channels that would be specific to your app
