### ISSUE TITLE
[Android] Issue with showing notification icon on production build

### ISSUE THREAD

**Issue by hlazarpesic** [MaikuB/flutter_local_notifications#2432]
During development and testing, the Android build displays the notification icon correctly (on the left side). However, after creating the production build and releasing it on Google Play, the notification icon fails to appear (right side). What could be the issue?

Tested on Pixel 9 Pro XL, Android 14 and Android 15

Code:
`const AndroidInitializationSettings androidInitializationSettings = AndroidInitializationSettings('@mipmap/ic_notification');`

Pub version:
`flutter_local_notifications: ^17.2.3`

<img width="1419" alt="Screenshot 2024-10-17 at 19 34 23" src="https://github.com/user-attachments/assets/e356889b-023a-4a90-a970-8b3d0134a77c">

**Comment by contato-araujor** [comment]
hlazarpesic the same problem happened to me. When the application is in debug it works, but if it is put into production it stops working.

**Comment by efrain2007** [comment]
a mi me pasa lo mismo que solucion le diste

**Comment by berkerozgur** [comment]
i was checking issues before i check the documentation and i read something like this. might be useful for your case:
Ensure that you have configured the resources that should be kept so that resources like your notification icons aren't discarded by the R8 compiler by following the instructions [here](https://developer.android.com/studio/build/shrink-code#keep-resources). If you have chosen to use @mipmap/ic_launcher as the notification icon (against the official Android guidance), be sure to include this in the keep.xml file. If you fail to do this, notifications might be broken. In the worst case they will never show, instead silently failing when the system looks for a resource that has been removed. If they do still show, you might not see the icon you specified. The configuration used by the example app can be found [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/keep.xml) where it is specifying that all drawable resources should be kept, as well as the file used to play a custom notification sound (sound file is located [here](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/android/app/src/main/res/raw/slow_spring_board.mp3)).

**Comment by hlazarpesic** [comment]
@berkerozgur Thanks for the answer, it works.
