### ISSUE TITLE
Create notification channels without posting a notification

### ISSUE THREAD

**Issue by naiveai** [MaikuB/flutter_local_notifications#246]
Currently, if we `show` a notification using a non-existent channel, the plugin creates the channel for us. Is there a way to create the channel beforehand (during initialization of the app or something) so that we can both categorize remote notifications correctly and have the option of passing in only the `channelId` when showing a notification, when it is already defined?

I'm a little bad at describing but all I'm saying is that it would be appreciated if a method existed that simply created a notification channel without needing to show a notification.

**Comment by MaikuB** [comment]
No as it would rely on having a platform-specific method. If you need this in your app then you create a platform channel to handle the scenarios your app needs

**Comment by naiveai** [comment]
Fair enough. A platform-specific method wouldn't be exactly unprecedented, since `FirebaseMessaging` has one to request permissions on iOS that's a no-op on Android, but I can see the logic in that reasoning.

**Comment by MaikuB** [comment]
Yep trying to keeping as the exception rather than the norm. One example, is there is a callback specific to older versions of iOS but that is critical functionality as older versions of iOS wouldn't show a notification if the app was in the foreground.

Also, I did think about this back when I first time I started working on this. If there are more requests to separate the channel creation then I'll be happy to reconsider. Could be something to ask in the form of a poll of some kind

**Comment by Rohansi** [comment]
I'd love to have this. I know I could just fork this to do it but there's a lot more of overhead involved with that because I'll need to update my fork to get the latest changes etc. This is just what Android expects us to do now so I'd expect libraries to try and have a way to do the same.

I wouldn't expect anyone to think this shouldn't be done because it would provide users with better notification options from the start instead of after a notification comes in (that's probably worse when there's multiple channels too).

**Comment by bhumkong** [comment]
This would be a nice addition to the plugin.
I currently use this plugin and FCM together and all notifications go to the same channel. The problem is that channel settings are applied only when a local notification is shown, and if Firebase messages are the first, they're shown with the default settings. And I couldn't find a plugin that allows to create Android notification channels.
So, I think such a method would be appreciated by many people.
And thanks for your work, @MaikuB

**Comment by MaikuB** [comment]
This will be something I've been thinking about but better be tackled as part of moving to new plugin structure that the Flutter team is proposing in https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit#heading=h.pub7jnop54q0

If you are in urgent need this functionality, you could write code that makes use of platform channels within your app.  Provided you understand how to work with platform channels, I don't envisage that taking much effort to do
