### ISSUE TITLE
Deep Linking issue when app open

### ISSUE THREAD

**Issue by 1343** [MaikuB/flutter_local_notifications#263]
I have one issue while using this lib, this is the scenario 

If I click on a notification and App is open deep linking call back I am not getting. 

Steps 
1.  Fire some notification 
2. Kill the App
3. Open app normally (Don't click on notifications) 
4. Now click on a notification while the app is open, I am not getting any callback **Is there any way to handle this**
5. If the app is closed and we are clicking on notification we are getting notification details in main

**Comment by 1343** [comment]
Future<void> onSelectNotification(String payload) async {
    print("Notification selected");
    toastMessage("Notification selected", currentContext);
    Navigator.push(
      currentContext,
      MaterialPageRoute(
          builder: (context) => NotificationDeeplinking(payload, true)),
    );
  }

Any idea how take context

**Comment by MaikuB** [comment]
> Now click on a notification while the app is open, I am not getting any callback

Please clarify if this still true or not for you because you should be getting the `selectNotification` callback and you appear to be asking about in your next post

> Any idea how take context

That ties into how you plan to architect your app so is something you'll need to figure out. I've made a simple suggestion in relation to another issue [here](https://github.com/MaikuB/flutter_local_notifications/issues/174#issuecomment-466307665) that you could apply

**Comment by MaikuB** [comment]
Closing due to lack of further response
