### ISSUE TITLE
Getting started steps do not explain GeneratedPluginRegistrant.java

### ISSUE THREAD

**Issue by safield** [MaikuB/flutter_local_notifications#270]
I am trying to look through the example project to get up and running with this library.

The example project contains GeneratedPluginRegistrant.java and some related code in MainActivity.java.

In this file, the  comment mentions...

```
/**
 * Generated file. Do not edit.
 */
```

My application does not contain this code, and I don't know if it needs to. Is there some step I need to run to generate this file? Should there be some sort of explanation in the "getting started" docs?

**Comment by MaikuB** [comment]
If you look at the GitHub repository, there's no such file as Flutter generates a .gitignore that will exclude it. Have you built your application yet? This is generated by Flutter itself so isn't related to this plugin for it to be mentioned in the docs

**Comment by safield** [comment]
I have built my application, and the generated file was not generated. Maybe I have missed a configuration step....though there are none listed in the readme.

**Comment by MaikuB** [comment]
As mentioned above, there no steps for this as there are none related to this plugin. I created a brand new Flutter project via the command line (flutter create --androidx helloworld) and can see the file there. I would go see if your app still works but you may need to raise an issue on the main Flutter repository if you run into a problem that ends up being related to it since that's related to the tooling

**Comment by safield** [comment]
I did not use the 'androidx' arg when creating my app. Is that a concern.

So you are saying the only thing I should have to do to configure this plugin to work is pull the repo, then point to it in the pubspec.yaml file?

**Comment by MaikuB** [comment]
> I did not use the 'androidx' arg when creating my app. Is that a concern?

You would need to migrate your app to use AndroidX following what's mentioned here https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

If you've only just started and don't mind recreating your app then you could recreate it with the argument. I've not tried it in this particular scenario but if the only changes you've made since creating your app is only on Flutter/Dart side (i.e. you don't have any Java/Kotlin or Objective-C/Swift code changes), you could delete the `android` and `ios` folders and then run `flutter create --androidx .` relative to the folder of your application. My understanding is that this command will create the necessary "plumbing" to get a Flutter app running Android and iOS, which will recreate the `android` and `ios` folders.

> So you are saying the only thing I should have to do to configure this plugin to work is pull the repo, then point to it in the pubspec.yaml file?

No there are other steps required, see the Android and iOS integration sections in the readme

**Comment by safield** [comment]
Are you implying that flutter_local_notifications plugin will not work in flutter projects create without the androidx flag? Or are you suggesting that all plugins won't work?

**Comment by MaikuB** [comment]
No I'm not. To clarify what I meant was for this plugin to work your app, it must use AndroidX, so you either (1) migrate your app to AndroidX (given you use the androidx flag) or (2) create/recreate a Flutter app with the androidx flag. The 2nd option wasn't available until recently. Before then, developers would have needed need to go with migrating their app.

**Comment by safield** [comment]
Ok understood. I will migrate, and confirm if that solves the missing generated files.

**Comment by MaikuB** [comment]
On that note, when you said you built the app, how did you going about doing so? Even if I create an app with `flutter create helloworld` and delete the folder at `android/app/src/main/java/io/` (GeneratedPluginRegistrant.java resides in one of the subfolders), it's been sufficient either run the app or run `flutter build apk` for the tooling to recreate it

**Comment by MaikuB** [comment]
Closing since there's been no further response
