### ISSUE TITLE
onSelectNotification is not called when tapping on the notification

### ISSUE THREAD

**Issue by TristanWYL** [MaikuB/flutter_local_notifications#292]
When the process of the app is killed (i.e. the app is working in the background) and tapping on the notification badge, if one wants the APP to work as exptected, say, the onSelectNotification callback is called, then the callback function has to be defined in the main.dart file. I have tested this is true. If I define the callback function in other files and the APP is not working in the foreground, then the callback will not be fired when tapping on a notification badge.

My question is that, even if the callback function is defined in the main.dart file, some time tapping on a notification will not lead to expected specific page/behaviour, while some time it will. I think is it based on the loading time. Is it that if the loading time is too long (relatively), the callback function will not be called. Is there anyboday who noticed this or who knows how it works behind the scenes?

**Comment by MaikuB** [comment]
If you're looking to see if others have encountered the same behaviour you have, then I think you should try to ask via other channels like Stack Overflow or gitter. Since this isn't really a discussion forum, it's not likely you'll find others checking here regularly to be able to answer that kind of question. Personally, I haven't encountered the issue and there have been no other reports of this behaviour as well so may well be something you need investigate how you're writing your app. As such, I'm closing this.

**Comment by TristanWYL** [comment]
No problem. Thanks very much for your kind reply.
