### ISSUE TITLE
How to do not display notifications when they're in the foreground? 

### ISSUE THREAD

**Issue by louwy001** [MaikuB/flutter_local_notifications#302]
The example always display both on foreground and background.

**Comment by MaikuB** [comment]
Local notifications always appear regardless of if the app is the foreground or not i.e. that's how they work. I'm not sure what kind of scenarios you're trying to handle here but perhaps it's something you should be looking at using push notifications for instead. 

Otherwise, it's a problem you'll need to solve in your app so that you either show a local notification when the app is in the background/terminated and do something else when the app is in the foreground.

Closing this as it's not an issue with the plugin given how local notifications. If you need help with handling the foreground and background behaviour, i would suggest you post on Stack Overflow as a generic Flutter question
