### ISSUE TITLE
Is it possible to schedule a push notification when the app is terminated?

### ISSUE THREAD

**Issue by marco2250** [MaikuB/flutter_local_notifications#334]
In firebase we are able to send push notifications even if app is terminated.

Is it possible with this plugin?

Thank you!

**Comment by MaikuB** [comment]
Push notifications work differently than local notifications, which is why they can be displayed when an app is terminated. Just to clarify are you trying to (a) schedule a notification when the app is terminated or (b) trying to ask if a notification that was scheduled whilst running, will appear when the app is terminated? The question in the title of your post would suggest it's (a) that you're interested in. In which case, it may be possible via [headless execution](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124) but it's not something I've tried. I have heard of others using the [android_alarm_manager](https://pub.dev/packages/android_alarm_manager) plugin to trigger notifications when the app isn't running as well.

If your question was actually about (b) then it should work and there's an example app in the repo you can run but would require cloning to repo. Copying the Dart isn't sufficient as there's platform-specific setup involved

**Comment by MaikuB** [comment]
Closing due to lack of further response
