### ISSUE TITLE
Push after receiving notification

### ISSUE THREAD

**Issue by dankop123** [MaikuB/flutter_local_notifications#34]
Hi,
When notification is received I want to open the app (if it's killed or in the background) and navigate to a specific view. The problem is that i don't know which build context to pass to a navigator in order this to work. The solution provided in example project is not working for me because, when I kill the app and open it by tapping on the notification I land on home view of my app and transition to other view is not occurring.

**Comment by MaikuB** [comment]
With regards to your problem about the build context, sorry but I don't think it's something I can help with you as that sounds like an app-specific/architecture problem you have to solve as opposed to it being a plugin issue. I'd suggest you go on the flutter channel on gitter to ask those kinds of questions

As for the solution in the example not working for you, it'd help if you provided more context like what platform you tested with and did you actually run the exact same sample or did you just take bits and pieces of the code? I've been testing the scenarios you've described without any issues and haven't gotten reports of such problems either. I also spun up a brand new flutter project, grabbed the plugin package, pasted in the example code across and it all seemed to work fine. I'd advise you to check the version of the Flutter SDK you're running too. I only tested on what's considered the latest stable (currently beta 3 v0.3.2). There use to be an issue in beta 2 where navigation in the app didn't complete the transition as I've reported in the README but the Flutter team has solved this problem now.

**Comment by MaikuB** [comment]
Closing due to lack of response and sounds like more an app architecture issue not a plugin issue

**Comment by vladaman** [comment]
I am having same issue. Firebase implementation you're referring to is working fine, since it works with current screen and context.

However when app is hidden or user has already navigated to another screen calling method onSelectNotification(String payload) will result in missing context

```dart
@override
  void initState() {
    super.initState();
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.initialize(initializationSettings,
        selectNotification: onSelectNotification);
  }

 Future onSelectNotification(String payload) {
   // in this method I am missing context - it's null. So when Notification is tapped on I'd like to redirect user to specific screen. Do you know how to get context here?
// this will not work -> context = null
    Navigator.of(context).push(new PageRouteBuilder(
          pageBuilder: (_, __, ___) => new HistorieItemScreen(),
        ));
  }
```

So the issue is not with the library itself but with an example which does not work when user has navigated away from the screen.

**Comment by MaikuB** [comment]
As mentioned in another issue you created, you have other issues going on with your code and should request help through other resources given it's not an issue with the plugin but the code you've got. If you were to modify the example code I have the plugin, you'll see that navigation will work even from another page. You could check this by making the following changes in the example to confirm (note: I've already tested this already)

- modify `_scheduleNotification()` so that the notification id is 1
- run the example
- tap on the button that will call `_scheduleNotification()` ("Schedule notification...)
- tap on the button to show a plain notification
- tap on the notification for the plain notification, this will take you to another page
- scheduled notification appears, tap on it and it will trigger navigation as well
