### ISSUE TITLE
didReceiveLocalNotification for iOS 10+

### ISSUE THREAD

**Issue by delef** [MaikuB/flutter_local_notifications#346]
Hi! Sorry, I can’t solve the problem of changing the contents of a notification after receiving it.
onDidReceiveLocalNotification don't work on iOS 10+ 🙁

**Comment by MaikuB** [comment]
The callback is not supposed to work on iOS 10+. See the API docs for it [here](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/IOSInitializationSettings/onDidReceiveLocalNotification.html). This callback exists because on older versions of iOS (i.e. < 10), when a notification is triggered and the app is in the foreground, the OS won't show the notification. Apps would typically need to show the content another way e.g. via an alert dialogue

**Comment by MaikuB** [comment]
For reference here's a link to Apple's documentation to the API that is related to the callback https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?changes=__9&language=objc

Hopefully you now understand what this callback is used for and the scenarios it can gets triggered. Will close this as the problem appears to be due to a misunderstanding on when it fires. I'll look at adding more info about the callback in the readme as well. Note that there's no callback when a notification is shown in general due to technical issues as mentioned in https://github.com/MaikuB/flutter_local_notifications/issues/341
