### ISSUE TITLE
Compatibility issues when used with firebase plugins

### ISSUE THREAD

**Issue by Galahand** [MaikuB/flutter_local_notifications#35]
if you use the latest versions of the firebase plugins you get the next error 

Android dependency 'com.android.support:support-compat' has different version for the compile (27.0.1) and runtime (27.1.0) classpath.

**Comment by Galahand** [comment]
yeah sure, i'm using cloud_firestore:7.1, firebase_messaging:0.2.5, firebase_storage:0.3.5, firebase_auth:0.5.10

I fixed the issue changing from com.android.support:support-compat:27.1.0 to com.android.support:support-compat:27.0.1 of the build.gradle of this plugin, but i will  aslo try the solution you said.

Thank you

**Comment by MaikuB** [comment]
No worries. I believe changing from the dependency from "implementation" to "api" in the build.gradle file would also solve it except that my understanding is that "implementation" to used to signify an internal dependency (which it is in this case). I might raise an issue on the Flutter repository to see if they have guidance on this as this may start to become a common problem as devs use multiple plugins so that they can add to their documentation

**Comment by MaikuB** [comment]
FYI, turns out the Flutter documentation already has some guidance for conflict resolution at this [link](https://flutter.io/developing-packages/#conflict-resolution)
