### ISSUE TITLE
iOS Push notification hides automatically from notification centre When app is in foreground (Not hide when app is in background))

### ISSUE THREAD

**Issue by sspogra** [MaikuB/flutter_local_notifications#359]

**Comment by MaikuB** [comment]
Not sure what you're trying to describe here but

- this plugin isn't for push notifications so perhaps you're confusing what you're seeing coming from another source
- there isn't anything in the iOS notification APIs that controls how a notification behaves in relation to the notification centre. In other words, whatever it is you're trying to describe is expected behaviour.  As such going to be closing this
