### ISSUE TITLE
Invalid sound

### ISSUE THREAD

**Issue by thaitanloi365** [MaikuB/flutter_local_notifications#365]
Hello guys !

When i tried to send push notification with custom alert on Android.

I got this error `PlatformException(INVALID_SOUND, The resource %s could not be found. Please make sure it has been added as a raw resource to your Android head project., null)`

Here is my showNotification alert.

```
Future<void> showNotification(
      {int id,
      String title = "The Fitt Cycle",
      String body,
      Map<String, dynamic> payload}) async {
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      id.toString(),
      Config.ANDROID_NOTIFICATION_CHANEL,
      Config.ANDROID_NOTIFICATION_CHANEL_DESCRIPTION,
      importance: Importance.Max,
      priority: Priority.High,
      ticker: 'ticker',
      sound: "alert.mp3",
    );
    var iOSPlatformChannelSpecifics = IOSNotificationDetails(
      presentAlert: true,
      presentSound: true,
      presentBadge: true,
      sound: "alert.mp3",
    );
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
      id,
      title,
      body,
      platformChannelSpecifics,
      payload: json.encode(payload),
    );
  }
```

I don't make sure If I'm wrong config (I already put alert.mp3 file into res/raw). Could you give me a instruction for custom alert ?

Thanks you.

**Comment by MaikuB** [comment]
There's an example app in the repo that should cover pretty much all of the functionality of the plugin including how to have custom sound. See https://github.com/MaikuB/flutter_local_notifications/tree/master/example

I suspect the issue is because you've specified the full name of the file including the extension. Android's resource system is based on just the name. See https://github.com/MaikuB/flutter_local_notifications/blob/590d8190ef76f5c32c0fc16ffcb21c4443decf33/example/lib/main.dart#L274, where it omits the mp3 extension that is part of the file placed in https://github.com/MaikuB/flutter_local_notifications/tree/master/example/android/app/src/main/res/raw

**Comment by thaitanloi365** [comment]
Hi @MaikuB !

After remove extension, it's works.

Thanks you for your quick response.

**Comment by ANORAK-MATTFLY** [comment]
Did anyone find a solution for this?
