### ISSUE TITLE
onSelectNotification context returns null

### ISSUE THREAD

**Issue by erenbertr** [MaikuB/flutter_local_notifications#380]
I'm trying to show a simple alert box (`showGeneralDialog`) `onSelectNotification`. The `showGeneralDialog` function needs context. I'm never able to show a simple dialog because the `context` returns always `null`. I tried some solutions (which I found in issues) but couldn't solved.

```
Future<void> onSelectNotification(payload) async {
    print(context); // returns null
    showGeneralDialog(
      context: context,
      barrierDismissible: true,
      barrierLabel: MaterialLocalizations.of(context).modalBarrierDismissLabel,
      barrierColor: Colors.black.withOpacity(0.3),
      transitionDuration: const Duration(milliseconds: 150),
      pageBuilder: (BuildContext context, Animation<double> animation,
          Animation<double> secondaryAnimation) {
            return Text('Test');
      },
    );
}
```

```
initializeNotifications() async {
    var initializationSettingsAndroid =
        AndroidInitializationSettings('@drawable/ic_bell');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);
  }
```

**Comment by MaikuB** [comment]
Hard for me say what the cause is but if you have a problem with getting access to the context then that is more of a general Flutter question that I would encourage asking on places Stack Overflow. You'll likely need to share more code as well as part of this as there are likely other issues in your code that need looking at that don't necessarily relate to the usage of the plugin. For example, could be running code at the wrong points of a widget's lifecycle (e.g. see here for an explanation https://flutterbyexample.com/stateful-widget-lifecycle/)
