### ISSUE TITLE
Local Notification Redirection not working when App is killed

### ISSUE THREAD

**Issue by technicalbird** [MaikuB/flutter_local_notifications#415]
**Describe the bug**
This plugin is working fine, generating the notifications when the app is in the foreground. Also,  clicking the notification leads to the redirect page. But when App is killed and notification is still active & you kill the app while there are pending notifications, then notifications are not getting killed & clicking on notifications are not redirecting to the desired page 
**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Receive Notification
2. Click on Notification, Desired Page will open
3. Receive another notification and don't click on it
4. Close the App & then click the notification. App Redirection is not happening.

**Expected behavior**
 desired page should be open irrespective of the App State

**Comment by MaikuB** [comment]
>  you kill the app while there are pending notifications, then notifications are not getting killed
That's expected behaviour

>  clicking on notifications are not redirecting to the desired page
This is actually the responsibility of your app not the plugin so not a bug with the actual plugin. If you clone the repo, you can run the example app that's included and you should see that it works fine. I'd suggest you check your code to see what you're missing. Otherwise, please use a site like Stack Overflow since there's no bug with the plugin around this functionality
