### ISSUE TITLE
How to use getNotificationAppLaunchDetails() method

### ISSUE THREAD

**Issue by hkndzdr** [MaikuB/flutter_local_notifications#439]
When the application is closed, the payload variable returns empty when you click on the incoming notification. How can I use getNotificationAppLaunchDetails() method?

widget tree structure ------- main.dart -> splash_screen.dart -> first_page.dart

"onSelectNotification method" in the first_page.dart

**Comment by MaikuB** [comment]
If for some reason you can't move `onSelectNotification` to be handled closer to where the app is started (see example app in the repo), you can look at using the result of `getNotificationAppLaunchDetails` to change the [`initialRoute`](https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html) of your app

**Comment by hkndzdr** [comment]
There's nothing showing how it's used in the example app in the repo or i can't see.

There are only these lines -->
// var notificationAppLaunchDetails =
//     await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

**Comment by MaikuB** [comment]
I was talking about referring to the example app for when the `onSelectNotification` is handled around when the app is started. It's up to developers to figure out how to use `getNotificationAppLaunchDetails` for their use cases, one of which might be to change the page shown when the app is started, which is why I sent the link to the API docs for [`initialRoute`](https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html)

**Comment by MaikuB** [comment]
You may also want to refer to the docs [here](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/NotificationAppLaunchDetails-class.html) that provides information on what is returned by `getNotificationAppLaunchDetails`
