### ISSUE TITLE
flutter_local_notifications not working for me

### ISSUE THREAD

**Issue by Zewe1995** [MaikuB/flutter_local_notifications#454]
I add flutter_local_notifications dependency and setup manifest file (added permission and receives), but notify not working ,do have need to more project setting except the manifest permission for android? 

I added this parameter to my project manifest:

 <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>

**Comment by MaikuB** [comment]
What's required is mentioned in the Android integration guide, which also talks about add the image for the icon. I'd suggest you re-read that section of the readme and look at the errors to see what you missed. I know some members of the community have also put up videos on using this plugin. You could look them up for more visual guidance.

Closing since this is a usage question
