### ISSUE TITLE
Do I need to include "flutter_local_notifications" folder in my project?

### ISSUE THREAD

**Issue by dsibinski** [MaikuB/flutter_local_notifications#458]
Hi guys,
the plugin seems to be really great and doing exactly what I need :)
I'm quite new to Flutter and I have one question:
I noticed that in the [example app](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications/example) in the main project there's a _pubspec.yaml_ adding a dependency like that:
`flutter_local_notifications:
    path: ../`
which as I see means to look for another _pubspec.yaml_ file one catalogue above.

Does it mean that if I want to use the plugin in my project, I need to copy the contents of [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications) catalogue (without the "example" folder of course) with its _pubspec.yaml_ and use it in the same way in my main pubspec.yaml?

It does the job, but I'm not sure I get it correctly :) Maybe there's a smarter way here?

Thanks a lot for answering!

**Comment by MaikuB** [comment]
No that's just what the tooling for creating plugins does out of the box so that plugin developers ship an example app with their plugin together.

Pub has a tab for installation steps. See https://pub.dev/packages/flutter_local_notifications#-installing-tab-

**Comment by MaikuB** [comment]
The Flutter documentation also has information on adding packages to an application [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages). If you're new to Flutter, I'd suggest spending time looking at their docs. There's some doc's for developers coming from other backgrounds such as Xamarin as well. 

Note that this plugin requires a fair bit of setup on the native Android and iOS side as well so ensure you check the related resources linked in the readme. I've seen videos done by members of the community of using the plugin as well.

Closing this now since the original question has been answered
