### ISSUE TITLE
[Feature Required]Support weekday, monthly, yearly notifications?

### ISSUE THREAD

**Issue by vifird** [MaikuB/flutter_local_notifications#485]
**Feature**
May this library support weekday, monthly, yearly notifications? I know iOS supports it.
I know we had supported daily, weekly notifications, that's really good.
Thanks for created such a useful library.

**Comment by MaikuB** [comment]
Not looking to add at this stage. Please submit a pull request if you're after new functionality. Unless I've missed something what you described doesn't appear to be possible. For example, how do I use this [kind of trigger](https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger) so that notifications appear only on weekdays.

The other thing is if the device calendar plugin is better suited to doing what you're after

**Comment by vifird** [comment]
Got it, thanks.
