### ISSUE TITLE
flutter_local_notifications conflict with the firebase_messaging 1.0.1

### ISSUE THREAD

**Issue by MandyKuo8** [MaikuB/flutter_local_notifications#50]
The firebase_messaging doesn't work properly in iOS platform when we apply  firebase_messaging plugin and flutter_local_notifications plugin together, but it works fine in Android platform.

Without  the firebase_messaging plugin, our app works fine and can receive all of the callbacks (onMessage, onLaunch, onResume) from firebase_messaging.
Unfortunately, the callbacks don't be called once we apply the  flutter_local_notifications plugin. 
_firebaseMessaging.configure(
    onMessage: onMessage, onLaunch: onLaunch, onResume: onResume);
Anyone can help to look into this issue?
Here is the firebase_messaging link.
https://pub.dartlang.org/packages/firebase_messaging

**Comment by MaikuB** [comment]
Sorry hadn't realised you also posted the issue but if you could try out what I suggested in my email against the dev branch of this plugin then that would be good. As mentioned in my reply to you, I suspect it's to do with both plugins registering for handling incoming notifications and my last commit to dev will hopefully provide a way to prevent that on iOS as that should be done by Firebase.

**Comment by MandyKuo8** [comment]
Hi Michael,
The solution you provide works. Would you please apply this patch and publish the latest package to Flutter? Thank you.

**Comment by MaikuB** [comment]
I need to do more testing first. You should also be aware that I believe that by having the new setting turned off means you won't be able to use my plugin to display local notifications on iOS. Not sure if that will be a deal breaker for your app but I don't think there's a way around. Partly why I said your team may need to write their own code to handle notifications

**Comment by MaikuB** [comment]
Done some testing and thinking about that and my conclusion is that this change will not be pushed out. Reason being is this can cause more issues. On iOS, the recommendation is that the delegate gets assigned before the app finishes launching (note: there can only be one, which is why you're seeing conflicts). There may also be apps out there that have a settings page where users can decide if they want to allow the app to show notifications. This will in turn initialise the plugin to show the permissions dialog and assign the delegate. In this scenario, it means that if the app is killed and then run again, notifications may not show as the initialisation has is done in settings. I don't want to create methods that only work on specific platforms either as that just creates more problems and breaks the design I have in mind. Thus, my recommendation is that your team uses a fork of the repository. I'll be reverting the commit on dev but have temporarily created another branch (registerUNUserNotificationCenterDelegate) with the change for your team to use as a reference. Will also update the readme with a note about this in case other devs run into similar issues.

**Comment by acudworth** [comment]
`registerUNUserNotificationCenterDelegate` needs to be removed from master if it's not used. It's currently sitting there providing no functionality which is misleading

**Comment by MaikuB** [comment]
Your comment is a bit confusing, registerUNUserNotificationCenterDelegate is a branch not code in master (removing branch from another branch). As explained above it was a reference for her to see what needs to change to avoid the conflict and she was originally using the git method for referencing a package to see if the fixed work.

Having said that the explanation for the how to solve it is in the readme now so I will be removing it

**Comment by ebeem** [comment]
would love to know if there is a workaround, I only use this plugin to display firebase messages for now. It works perfectly for Android, but not IOS.

after deleting these lines, the `onMessage` firebase function gets fired if a message is received

```
UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
center.delegate = instance;
```

but I can display any local notification message, and for some reason .. this statement is not valid for me `iOS handles showing push notifications out of the box` showing notifications only work when the app is running in background, if it's foregrounded, then the `onMessage` gets fired

please let me know if any solution/fork happened, thanks

**Comment by MaikuB** [comment]
If you read the next paragraph in the readme, I mentioned that devs will most likely need to look into rolling custom code. By commenting out the code that I've mentioned (that you've also have highlighted), it removes the conflict so that the Firebase messaging plugin can do its job handling your remote/push notifications so it comes down to how they've handled remote/push notifications when the app in the foreground. As such, I believe your question is better directed to the Flutter repo and may also be worth asking on Stack Overflow and Gitter. This may or may not be of help to you too https://firebase.google.com/docs/cloud-messaging/ios/receive#handle-data-messages-in-foregrounded-apps

**Comment by haroldolivieri** [comment]
I believe I am facing this problem now, any fix for that?

**Comment by MaikuB** [comment]
Please see https://github.com/MaikuB/flutter_local_notifications/issues/111#issuecomment-575843590
