### ISSUE TITLE
flutterLocalNotificationsPlugin schedule ok on emulator but not on android phone

### ISSUE THREAD

**Issue by baaaaaziiiiingaaaaa** [MaikuB/flutter_local_notifications#502]
Hello,

Sorry if me english is not perfect.

I would like to make a scheduled notification 5 seconds later.
In emulator's version with android studio and a "pixel 3a" the notification is operational. But once the APK extracted and that I install it on my "samsung s10" and that I click on the button, the application closes.

I integrated everything and put to the github below.

Thanks for your help

Github exemple : [https://github.com/baaaaaziiiiingaaaaa/scheduledNotification](https://github.com/baaaaaziiiiingaaaaa/scheduledNotification)

**Comment by MaikuB** [comment]
Your repository would indicate that you haven't done the setup required for release builds that are mentioned in the later paragraphs of the Android integration guide. Please double check and follow the steps mentioned there

**Comment by baaaaaziiiiingaaaaa** [comment]
Hello,

thank you for your reply.
I saw this error, but it's my first project's flutter and I do not see what I am missing.
I have everything OK with the command "flutter doctor" and the project is new on android studio 3.6.
Could you tell me the procedure to follow to correct the problem?

**Comment by MaikuB** [comment]
What you need to do is covered in the readme and there's an example app you can use for reference. These are the relevant sections in the readme

> When doing a release build of your app, you'll likely need to customise your ProGuard configuration file as per this [link](https://developer.android.com/studio/build/shrink-code#keep-code) and add the following line. 

```
-keep class com.dexterous.** { *; }
```

The plugin also makes use of GSON and the Proguard rules can be found [here](https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg). The example app has a consolidate Proguard rules (`proguard-rules.pro`) file that combines these together for reference.

If you have resource shrinking enabled, ensure that you have customised the resources that should be kept so that things like your notification images aren't discarded by following the instructions [here](https://developer.android.com/studio/build/shrink-code#keep-resources).

**Comment by MaikuB** [comment]
Note that since my previous post, I've updated the readme to include direct links to the relevant files used by the example app. See the section at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by MaikuB** [comment]
Closing due to lack of further response
