### ISSUE TITLE
Does basic android scheduling need permission from the user in ANY case?

### ISSUE THREAD

**Issue by b-cancel** [MaikuB/flutter_local_notifications#533]
I have a Galaxy S10 running the latest version of android.

And the permission to send notifications is automatically granted and the plugin tells me so (permission_handler)

But is that the case in all scenarios? You don't mention that it's needed for Android (only IOS) but the option to request it exists in permission_handler plugin. 

So does it EVER need to be requested?

Thanks for the help beforehand and fantastic work on the plugin!

**Comment by MaikuB** [comment]
No it doesn't. You can dig through the code of that plugin to find out and you can see it only checks if notifications enabled. It looks like permissions are requested because the plugin exposes a cross-platform API for convenience. If it was needed, you'd have likely seen a method to request permissions that applies to push notifications on Android yet for the `firebase_messaging` plugin, it's only applicable to iOS

**Comment by b-cancel** [comment]
Ah I see

So to confirm, If I want to have basic scheduled notifications for both platforms I only need to request permission with YOUR plugin for IOS?

I ask with your plugin specifically because I'm not sure if it handles the case where notifications are restricted

Whereas the permission_handler atleast exposes what I need to handle that case

Thanks*2 for the help and speedy response 👍

**Comment by MaikuB** [comment]
Should be all you but I imagine you could do a spike to confirm if you have concerns

**Comment by b-cancel** [comment]
I ask because I dont have an IOS device to test on at hand 😅
But I will rent out a remote PC and test it since ur unsure

Either way thanks for the help!
I hope you enjoy the rest of your day 👋

**Comment by MaikuB** [comment]
I'm pretty sure, I only mention doing a spike since you seemed to have doubts that it should be something that can be quickly verified provided you have access to devices or emulators. I'm guessing your response means you at least have access to Android in some form.

In any case, good luck and hope my answers helped :)
