### ISSUE TITLE
Suggested Info To Add To Plugin Readme

### ISSUE THREAD

**Issue by b-cancel** [MaikuB/flutter_local_notifications#554]
I don't know how Android and IOS **always** behaves when checking and requesting permissions 
for **specifically** notifications
I'm worried that it varies by OS version or some other thing I am missing

If you **know** the behavior **always** or **in all the different cases**, 
since it has been a challenge to get a clear cut answer (for me)
I'm sure others would benefit if you posted this information

**Otherwise**, this is what I've been able to understand 
from the Readme of **[notification_permissions plugin](https://pub.dev/packages/notification_permissions)**
and from the reading of **current** documentation

**For the Default Status of notification permissions**

- For '**IOS**': the permission status is '**unknown**' until the user acts. It can then become '**granted**' or '**denied**'
- For '**Android**': the permission status is '**granted**' until the user makes some change. It can then become '**denied**' if the user manually changes it from '**App Settings**'
**NOTE:** that it can **never** be **never ask again** like most other permissions, since the notification permission is handled differently than all other android permissions

**For Requesting notification permissions**

- For '**IOS**': you can request permission, which will show an alert window asking for permission as many times as you wish (Since you can only '**allow**' or '**deny**' but you can't ask it to '**never ask again**' like Android) [alternatively '**you could open App Settings**' and let the user enable it manually]
- For '**Android**': the alert window is not a way to change permissions, you need the user to go into **'App Settings'** (presumably this is because apps are given permissions to send notifications automatically, so request permission to notifications, assumes the user previously removed it from app settings, and if they know that they know what to do when taken to app settings if they desire to re-enable the permission)

**Comment by MaikuB** [comment]
> If you know the behavior always or in all the different cases,
since it has been a challenge to get a clear cut answer (for me)
I'm sure others would benefit if you posted this information

Are you missing something from this sentence as it seems like it might be incomplete and I'm not sure what you're saying trying to say here. As a whole, it's not clear what you are suggesting to add either but based on what you've here and from [your previous issue](https://github.com/MaikuB/flutter_local_notifications/issues/5330) seems to be more from getting confused upon seeing that the readme for other plugins. What you're posting above is more relevant for the plugins that focus on managing permissions such that it's more appropriate for them to go there. Note that you can also open a pull request.

The difference in behaviours you're describing also applies more to the other plugins. There is only an API that is specific to requesting permissions on IOS in this plugin because that is the only platform that needs it as I had mentioned it [here](https://github.com/MaikuB/flutter_local_notifications/issues/533#issuecomment-599965403). This is also listed as an iOS-specific feature in the readme.

**Comment by b-cancel** [comment]
@MaikuB I don't think I'm missing anything, but hopefully, If I reword things I can better express myself 😄 

What I was trying to say is that
Since your plugin requires permission request for IOS
It might also be a good idea to inform other developers
of how to handle permission request **specifically** for notifications in all situations

as far as I've been able to derive
regardless of what version of Android or IOS you are dealing with
the rules are the same

and listed below this block of text in my original suggestion
```
Otherwise, this is what I've been able to understand
from the Readme of notification_permissions plugin
and from the reading of current documentation
```

It's true that this is more relevant for plugins that focus on managing permissions
and because of that, I have requested that they add this to their **Readme** as well

But in either case, this addresses **specifically** permissions for notifications
(the rules for each platform, for other types of permissions, are different)
and your plugin is about notifications
so it seemed proper to make the suggestion

**Comment by MaikuB** [comment]
I'm going to close this. Besides perhaps making it more explicit that Android doesn't require requesting permissions, I don't see a need to add more information as the rest of what you've described isn't relevant IMO. Your suggestion was more of a statement of how your understanding the `notification_permissions` plugin works that even the states ("granted", "denied" and "known") come from that plugin. Including a description of another plugin wouldn't be appropriate here.
