### ISSUE TITLE
Simplify example

### ISSUE THREAD

**Issue by codenoid** [MaikuB/flutter_local_notifications#556]
as new programmer, i'ts hard to understand how this library work (structure & flow), can someone make a dead-simple example of showing notification with this plugin, thank you <3

**Comment by MaikuB** [comment]
Sorry but I'm not seeing how to make this any simpler. It is already quite basic (there's no state management libraries used here, just what's provided out the box besides rxdart) so chances are that given you're a new programmer that you'll need to spend more time on basics first.

It's hard to understand what you're having trouble with unless you go into specifics as what you said is very broad.

**Comment by codenoid** [comment]
i found this : https://github.com/nitishk72/flutter_app_local_notification/blob/master/lib/main.dart

thankyou @MaikuB for awesome plugin

**Comment by MaikuB** [comment]
FYI you could've referred to the example app in this repository as well. The simplest example you appear to be after based on the link you posted would've been the code associated with the first button (https://github.com/MaikuB/flutter_local_notifications/blob/7ba699f0b9d57b8927c4a3a04776b85b0c5b9cd1/flutter_local_notifications/example/lib/main.dart#L226)

There are different buttons there to cover all of the various functionality available. I'n guessing perhaps you got thrown off by looking at all of the code instead of stepping through the code that is relevant to the most basic scenario
