### ISSUE TITLE
How i can manually show notification?

### ISSUE THREAD

**Issue by koteezy** [MaikuB/flutter_local_notifications#594]
Hello!

In our app logic, we need show notification from android, not from flutter, in previously plugin version, we made it something like that:

```
FlutterLocalNotificationsPlugin.showNotification(context, details);
```

But, when i update it to last version, app start crash with message:

```
Cannot access 'showNotification': it is package-private in 'FlutterLocalNotificationsPlugin'
```

Soo... How i can call it manually? Thanks!

**Comment by MaikuB** [comment]
Apologies that you're affected by the change but the ability to call it from Android wasn't intentional and there's a few things underneath the hood that assumes the app is being used within a Flutter. Doing it as you had done before could have done unintended consequences. You could possibly try to trigger to the method that would have been invoked by the plugin from the Dart side (see https://github.com/MaikuB/flutter_local_notifications/blob/60072d6806bf531ac2ec88570027a7a9445c7184/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L731). 

However, in general if you want to do things from the native side then I'd say it is more safer for you to roll your own code for as plugins are created to be used from executing Dart code.

**Comment by koteezy** [comment]
> Apologies that you're affected by the change but the ability to call it from Android wasn't intentional and there's a few things underneath the hood that assumes the app is being used within a Flutter. Doing it as you had done before could have done unintended consequences. You could possibly try to trigger to the method that would have been invoked by the plugin from the Dart side (see
> 
> https://github.com/MaikuB/flutter_local_notifications/blob/60072d6806bf531ac2ec88570027a7a9445c7184/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L731
> 
> ).
> However, in general if you want to do things from the native side then I'd say it is more safer for you to roll your own code for as plugins are created to be used from executing Dart code.

Thanks for reply!

Yep, i thinking about that, but i simply don't know android as well as you, and i [stuck with this](https://imgur.com/gjhfBLX)

If you will have time, can you please provide a small example, how i can do that?

**Comment by MaikuB** [comment]
In terms of an example the code is there in the repo that you could copy and paste what you need (e.g. the method you use to call). The official Android documentation has guides as well (https://developer.android.com/guide/topics/ui/notifiers/notifications) and there are plenty of resources online. 

I'd say you should avoid copying and pasting though, sounds like you were calling a method without knowledge about the native APIs to be sure it would do what you need without any problems

**Comment by koteezy** [comment]
> I'd say you should avoid copying and pasting though, sounds like you were calling a method without knowledge about the native APIs to be sure it would do what you need without any problems

Yep, exactly, i got you, thx. :)

**Comment by MaikuB** [comment]
No worries. Will close this then. Good luck :)
