### ISSUE TITLE
Set over 200+ alarms and application delay

### ISSUE THREAD

**Issue by serikshaikamalov** [MaikuB/flutter_local_notifications#605]
Hi, thank you guys for your work! One of the best library. I am trying with Schedule Notification.  For my project need setup for every day at lease 7 alarms and multiply by 1 month (about 210 alarms). When I set alarms at one time I'll get long delay(20 seconds ~).

**Expected behavior**
![image](https://user-images.githubusercontent.com/11631958/80512129-dcc5a580-899e-11ea-90f7-e95ef0117dad.png)

**Comment by MaikuB** [comment]
Can you elaborate more on where the delay is? I'm wondering if the issue the same as https://github.com/MaikuB/flutter_local_notifications/issues/459. If it is, then you should look at using the fork provided the original poster has. They opened a PR but I intend to deprecate the existing method for scheduling due to issues with timezones that has been documented

**Comment by serikshaikamalov** [comment]
Thank you for your reply! Is it possible to use this repo in my own project? I mean modify some code in your repo and build flutter app. Thanks a lot

**Comment by MaikuB** [comment]
You can modify your own fork/repo and point to it. Read https://dart.dev/tools/pub/dependencies#git-packages
