### ISSUE TITLE
[Android] How to use time-sensitive notifications ?

### ISSUE THREAD

**Issue by amadeu01** [MaikuB/flutter_local_notifications#609]
Is it possible to use time-sensitive notifications? https://developer.android.com/training/notify-user/time-sensitive

It should be basically adding one more option:

```
val notificationBuilder =
        NotificationCompat.Builder(this, CHANNEL_ID)
    .setSmallIcon(R.drawable.notification_icon)
    .setContentTitle("Incoming call")
    .setContentText("(919) 555-1234")
    .setPriority(NotificationCompat.PRIORITY_HIGH)
    .setCategory(NotificationCompat.CATEGORY_CALL)

    // Use a full-screen intent only for the highest-priority alerts where you
    // have an associated activity that you would like to launch after the user
    // interacts with the notification. Also, if your app targets Android 10
    // or higher, you need to request the USE_FULL_SCREEN_INTENT permission in
    // order for the platform to invoke this notification.
    .setFullScreenIntent(fullScreenPendingIntent, true)
```

**Comment by MaikuB** [comment]
I assume you with specifying the full-screen intent. If so then it's not possible. If you have a need for this then you'll need to look at adding your own code as the plugin to solve for cases you need to support. 

The plugin can't solve for all scenarios. If it were then it would also need to consider how to handle when the plugin is used in an add-to-app scenario. In this case, there may be multiple activities that could be launched by an intent. This is different from a Flutter application where there's only one activity. There'd need to be a way to specify which activity should be launched from the Dart side. Should you happen to know of a way though, feel free to submit a PR. If not, I'll be closing this

**Comment by Ted-chiptech** [comment]
Just throw out an idea here for people who try to achieve this behavior. flutter local notification has full screen intent in 1.5.0 beta 8 now, so could leverage it to launch the whole application, and due to flutter appliation is one activity, we need to write some logic to jump to certain screens after it launched, in order to do this, we could override the didChangeAppLifecycleState method in root level, and jump to certain page when status equals AppLifecycleState.resumed. My scenario is slightly more complex as I am use FCM onBackgroundMessage option, the callback will executed in a isolated environment, so I am also using shared preferences to pass screen route between them so it will know which screen should navigate to when the application launched. Hopefully this could provide some help.

**Comment by MaikuB** [comment]
Thanks for the info @Ted-chiptech. Yes it got added though I should clarify what I meant from the previous message was that it's to do with loading specific activities, which is what it's normally associated with. If you take a look at the example app though, it already handles going to a specific page and this is via the existing `onSelectNotification` callback. That may need tweaking for your scenario since you're using FCM

**Comment by Ted-Zhang** [comment]
Thanks @MaikuB, yes, ```onSelectNotification``` callback is great to cover the scenario that navigate to certain screen when user tap on the push notification message. I think the problem I was facing is a little bit more special due to it requires to launch the flutter app from FCM background notification callback when the screen is locked and received some push notification messages, and we don't have navigatorkey at that stage due to it is running in isolated box, so I was use shared preferences as mediator to pass the screen route back once flutter app is resumed and navigatorkey becomes available. I think this probably a rare user case, but just in case if someone was troubled by the same issue 😄

**Comment by niteshgrg** [comment]
@Ted-Zhang How were you launching the app from myBackgroundMessageHandler ?

**Comment by Ted-chiptech** [comment]
> @Ted-Zhang How were you launching the app from myBackgroundMessageHandler ?

I was using FlutterLocalNotificationsPlugin.show() method and set the fullScreenIntent to true.

**Comment by dawit-michael** [comment]
> Just throw out an idea here for people who try to achieve this behavior. flutter local notification has full screen intent in 1.5.0 beta 8 now, so could leverage it to launch the whole application, and due to flutter appliation is one activity, we need to write some logic to jump to certain screens after it launched, in order to do this, we could override the didChangeAppLifecycleState method in root level, and jump to certain page when status equals AppLifecycleState.resumed. My scenario is slightly more complex as I am use FCM onBackgroundMessage option, the callback will executed in a isolated environment, so I am also using shared preferences to pass screen route between them so it will know which screen should navigate to when the application launch. Hopefully this could provide some help.

your a life saver. Thank you
