### ISSUE TITLE
Multiple Daily Notifications

### ISSUE THREAD

**Issue by JeffScaturro** [MaikuB/flutter_local_notifications#61]
Thanks so much for writing this plugin, it's incredibly useful. Hopefully those final issues get cleared out with flutter soon so it can be officially adopted. 

Onto the not so great part, I have two different and independent notifications scheduled to be shown daily calling [`showDailyAtTime `](https://github.com/MaikuB/flutter_local_notifications#show-a-daily-notification-at-a-specific-time). One is shown in the morning, and the other in the evening. They both have unique notification ids and titles, while the body is the same.

If I schedule them to display relatively close to the current time, they will both execute and display. However the next day only the last one scheduled will display, which is the evening one in our case. The code execution is as follows:
- (*await*) cancel *all* existing notifications through plugin
- (*await*) schedule morning reminder 
- (*await*) schedule evening reminder

Have you seen anything similar or know of any current issues that may cause this? Thanks.

**Comment by MaikuB** [comment]
Thanks for the compliments though I don't expect it to be an official plugin :)

Anyway, I've not heard of any such issues. Sounds like you're saying both notifications were showing and then one would disappear? If so, perhaps this is the OS doing it? I don't normally leave my notifications to the next day to see but there shouldn't be anything to do with the API that would result in the behaviour you're describing.

**Comment by JeffScaturro** [comment]
Right, I'd schedule the morning & evening notifications, say around mid-day. I'd get the evening notification that night. The next morning there would not be a notification, however in the evening there would be one. I am testing this on an iOS device (iPhone) currently, so not sure if this is seen on Android yet. I wanted to check prior to diving too deep to see if it was familiar at all or not. I have some more testing planned for Tuesday & Wednesday and can update this issue with any findings and ultimately close it out. If any changes come up I'll be sure to drop a PR! 

Thanks again.

**Comment by MaikuB** [comment]
Might be worth scheduling just one in the morning to see what happens but yeah if you find something wrong then a PR would be much appreciated :)

**Comment by MaikuB** [comment]
Yeah I think you're onto something there. Tagging @javiercbk in case he may know too or have run into the same issue. I suspect what needs to be done is to change the components used as per the line code you linked to.

May well be that the fix is that on that line you linked to, if a day has been specified (for weekly notifications) then the components used are `NSCalendarUnitDay | NSCalendarUnitHour | NSCalendarUnitMinute | NSCalendarUnitSecond`, otherwise use `NSCalendarUnitHour | NSCalendarUnitMinute | NSCalendarUnitSecond`. This something you can fork, test on and submit a PR for? If you check the Dart docs, pubspec allows for referencing packages that are local or git-based https://www.dartlang.org/tools/pub/dependencies

**Comment by JeffScaturro** [comment]
I can definitely do that. I should be able to get some time tonight or tomorrow on it. Thanks!

**Comment by MaikuB** [comment]
Sure, I'm pretty confident that will solve the issue but figured it would be better to have another pair of eyes on it :)

**Comment by MaikuB** [comment]
With regards to regression, it shouldn't be an issue. Though to be safe,  I think you should specify the calendar property of the date components be Gregorian as I suspect this could cause issues for apps/devices that use a different calendar system.

**Comment by JeffScaturro** [comment]
Theoretically it should work; I'll know if this works in practice early tomorrow, and if so I'll get a PR up.

**Comment by MaikuB** [comment]
Yep though for the us in western world, the default will most likely be Gregorian that's why it'll work. I'd suggest making that change to set the calendar now if you can so you can see if it still works as it's something I'd like to see done. Particularly when you look at documentation for the Swift bridge to NSDateComponents [here](https://developer.apple.com/documentation/foundation/datecomponents/1779873-calendar) and talks about the behaviour on what happens if the calendar is left out. I'd expect the same behaviour for the NSDateComponents class and the documentation for the latter says it's meaningless in itself unless a calendar is specified.

**Comment by JeffScaturro** [comment]
I included the calendar assignment in 6c4e6a6900842571c9ef6f0a0986c4da12a358f6.

**Comment by MaikuB** [comment]
Been looking a bit into this too and I reckon the same change will be needed in `showLocalNotification`. Unfortunately I've only got a simulator for this given this affects only older iOS versions so will need to wait to verify that it works

**Comment by JeffScaturro** [comment]
Just got my morning notification! 🎉 Just going to do a sanity regression test on the weekly notification and will create a PR.

**Comment by JeffScaturro** [comment]
Closing issue with Open PR.

**Comment by MaikuB** [comment]
FYI, I published a new version with your fix included :)

**Comment by JeffScaturro** [comment]
Awesome! Thank you!
