### ISSUE TITLE
how to cancel ongoing notification after i close the app

### ISSUE THREAD

**Issue by AdiKK17** [MaikuB/flutter_local_notifications#649]
I tried to call .cancelAll() from dispose since dispose is last called but  the notification still persists in the status bar

**Comment by MaikuB** [comment]
The problem here is `dispose` is synchronous and `cancelAll` is asynchronous, there's no guarantee that it will be finished by the time the app/widget is disposed. `dispose` can end up removing the plugin from memory before everything is done too. This problem isn't specific to the plugin and can happen to general asynchronous methods so you'll need to research how to this one e.g. see if there are iOS/Android APIs you can use and write iOS/Android native code

**Comment by AdiKK17** [comment]
I want something like this  https://stackoverflow.com/questions/11292993/always-show-service-in-notification-bar! Can I do this with this plugin or do I have to write native code as you said?

**Comment by AdiKK17** [comment]
@MaikuB any ideas to the above query?

**Comment by MaikuB** [comment]
What is exactly that you're trying to ask? The link refers to an ongoing notification that you're already using. All features of the plugin are documented in the readme and covered in the example app for you to see if there's anything that is close to what you're after

**Comment by AdiKK17** [comment]
The plugin works perfectly but what I am trying to ask is that can I close the ongoing notification with the help of this plugin when the user closes the app.
For eg- Like in Google meet it shows an ongoing notification while we are on the video call and if we close the app or leave the conference the ongoing notification disappears

how can I implement this feature?

**Comment by MaikuB** [comment]
You'll need to write your own native code

**Comment by AdiKK17** [comment]
okay thanks!
