### ISSUE TITLE
Conflict Between AndroidNotificationChannel  and AndroidNotificationDetails

### ISSUE THREAD

**Issue by gfiury** [MaikuB/flutter_local_notifications#663]
Hi @MaikuB,

I'm trying to add the default ringtone sound, but there is a strange behavior that I want to confirm

1) I have Android 10 so an AndroidNotificationChannel is required right?
2) Looking at the code AndroidNotificationChannel  and AndroidNotificationDetails have similar properties, but they don't interact with each other. is this right?

The behavior that I'm seeing is that the Channel is having a priority over the sound. So it does not matter if a set a new sound on the AndroidNotificationDetails, the one is played is the sound set on the Channel.

What happens if the AndroidNotificationChannel has the property playsound on false, and the AndroidNotificationDetails has playsound on true?

Is this the expected behavior?

Regards,
William

**Comment by gfiury** [comment]
I figured it out, with a test from here flutter_local_notifications/test/platform_flutter_local_notifications_test.dart.

I made a channel for each type of Notification, before calling the show notificaiton.

**Comment by MaikuB** [comment]
Some of those similar properties you mention across the two classes will refer to the same properties of a native Android notification channel. The API docs should tell which ones are tied to a channel. If you haven't read the Android docs on notification channels then I'd suggest you do so. Once the channel has been created through either approach, the configuration will remain as is unless it's deleted and recreated.

They are meant to provide alternatives on how the channel is created. One way is to include the info about the channel as part of the notification details. The channel will get created before the notification is shown. This way was provided so developers didn't have check what the platform the code is running on. 

As the way to develop plugins evolved a second way was provided so that developers could create the channels through the Android implementation of the plugin that has a method for creating channels via the `AndroidNotificationChannel`. This was provided as developers wanted to be able to create channels in advance without having to show a notification.

If you create a channel first and then try to use the properties associated with `AndroidNotificationDetails` and change the values then it's expected behaviour that it won't change
