### ISSUE TITLE
System UI crashes while receiving push notification

### ISSUE THREAD

**Issue by sojoraja1** [MaikuB/flutter_local_notifications#685]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

![image](https://user-images.githubusercontent.com/36787347/85938073-6f47de00-b929-11ea-9483-38521791e220.png)
![image](https://user-images.githubusercontent.com/36787347/85938078-7969dc80-b929-11ea-9279-e7496769b6f8.png)

**Comment by MaikuB** [comment]
Please provide all of the information that is in the bug report template or this will be closed. It also mentions you double check the example app and all the steps in the readme. Please make sure you do this before you open a bug as crashes etc are likely due to you missing a step given how long the plugin has been made available

**Comment by MaikuB** [comment]
Closing due to lack of response about filing a complete bug report
