### ISSUE TITLE
Android: ACTION_BOOT_COMPLETED verification fails MY_PACKAGE_REPLACED broadcast

### ISSUE THREAD

**Issue by nadavfima** [MaikuB/flutter_local_notifications#689]
The next line would fail any potential MY_PACKAGE_REPLACED broadcasts you might want to listen to:

https://github.com/MaikuB/flutter_local_notifications/blob/a31d4fa9b38b49135e07ff627d55318e8d85f881/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java#L13

When an android app is updated, all set alarms are cancelled.
Therefore, we'll need to reschedule all notifications when update is complete.

So we need to remove this verification (or add to it?), and maybe even recommend using `MY_PACKAGE_REPLACED` as well in the README.

@MaikuB 
WDYT? Should I create a Pull Request?

**Comment by MaikuB** [comment]
Yeah a PR would be great though if you know of ways to reproduce this locally (off memory it can be done with ADB) so that I can also confirm the solution in the PR works then that would be great.

My thinking is that if it's possible, the PR should add that as intent to check reduce the amount of changes developers need to do on their end. Some already have issues figuring out how to edit the manifest file as well

**Comment by nadavfima** [comment]
Yea, reproducing this just takes reinstalling the APK via ADB.

So I'll fork and create the PR tomorrow. Shouldn't take too long.
I'll add the new action to the verification statement, and add it to the readme.

**Comment by MaikuB** [comment]
Sounds great and thanks for catching this

**Comment by MaikuB** [comment]
Released now, thanks :)
