### ISSUE TITLE
Receive notification with firebase_messaging OR with flutter_local_notifications based on a condition

### ISSUE THREAD

**Issue by joaomarcos96** [MaikuB/flutter_local_notifications#711]
Hi there.

This issue is more a question than a bug report.

Is there a way to receive notifications with `firebase_messaging` OR with `flutter_local_notifications` based on a condition, without ending up with a duplicate notification? For example, if there's some key in the payload, display the notification with `flutter_local_notifications`, otherwise, with `firebase_messaging`. Is this possible, at least on Android?

Thanks in advance!

**Comment by MaikuB** [comment]
Sorry but I don't understand what you're trying to achieve here and what you're after doesn't make sense. If you have somehow have duplicates then that's an issue in your application logic. Local notifications only appear because your application requested to show one. 

Your question to implies to me that you might not understand how firebase_messaging works either. If you look at the readme, it documents all the scenarios where notifications appear. You don't get the chance to intercept the message before a  push notification is shown

**Comment by joaomarcos96** [comment]
It makes sense only because I would have to come up with my own solution to display push notifications with image. Therefore this issue does not belong here since my real problem is that firebase_messaging does not provide a way to include image in push notification. I was just trying to find a workaround using your package.

**Comment by MaikuB** [comment]
I'd suggest you look at the FCM docs as there should be ways to include the image in a push notification
