### ISSUE TITLE
Cancelling a single daily notification

### ISSUE THREAD

**Issue by eug48** [MaikuB/flutter_local_notifications#712]
Thank you for this plugin. I'm using it to show reminders for users to take food photos. For example users can configure a daily reminder at 8am. This is working well but when a user takes a photo at say 7:45am it'd be good to cancel the upcoming reminder. I'm probably missing something but I suppose there are two ways to do this:

1. An API to cancel only the next notification, e.g. `cancelNext(id)`
2. Adding an argument like `startAfter` to `showDailyAtTime` which can be set after the original notification is cancelled

Do any of these options sound like good ideas?

**Comment by MaikuB** [comment]
Neither of those fit with how the native APIs work. If you need to cancel/remove a single notification then what you're dealing with isn't really a single recurring notification. This is what they actually are right now and how the native APIs treat them.

If you need the level of control you're after then you should be looking into your solution for scheduling individual notifications or see if a plugin like https://pub.dev/packages/device_calendar works for your scenarios

**Comment by MaikuB** [comment]
Actually there is one thing...your second idea is similar to what's available in the current beta release. `showDailyAtTime` has been deprecated due to timezone issues but there is a `zonedSchedule` method for scheduling a notification to occur at a specific date and time relative to a given timezone. There is an optional argument for specifying if this should occur daily. I'd suggest giving the beta a go to see if it works but it could be that https://pub.dev/packages/device_calendar is more suited for what you're after. I don't know/remember if it has the ability to remove a reminder though

**Comment by eug48** [comment]
I was thinking that when the plugin gets woken up by the native API it could check whether `cancelNext` is set, and if so just ignore having been awaken instead of showing a notification?

Thanks, I will definitely check out `zonedSchedule`. device_calendar is a very interesting idea but I'd like the app to have minimal permissions.. I guess device_calendar can be used optionally.

**Comment by MaikuB** [comment]
> I was thinking that when the plugin gets woken up by the native API it could check whether cancelNext is set, and if so just ignore having been awaken instead of showing a notification?

What you're describing is functionality that is more application-specific as opposed to core logic for a plugin whose purpose is to provide a standard wrapper for the underlying native APIs. Moreover, what you're suggesting isn't technically possible as it can't be intercepted when the app isn't running on iOS

**Comment by MaikuB** [comment]
Closing since questions have been answered
