### ISSUE TITLE
Support for profile image (image left of the text)

### ISSUE THREAD

**Issue by yanivshaked** [MaikuB/flutter_local_notifications#713]
Hi,

Currently the plugin supports displaying an image on the far right end of the notification bar.
Are there any plans to add support for an image (typically a profile image) to be displayed left of the text?

![image](https://user-images.githubusercontent.com/13107481/87542549-c8469e80-c6ab-11ea-9eb0-4191a3a73d74.png)

Thank you!

**Comment by MaikuB** [comment]
That the image is on the right isn't because of how the plugin works. It's actually because that's how the native APIs work. You can see this in the official docs https://developer.android.com/training/notify-user/expanded#image-style. Even profile images are the on right. So to answer your question, no as the native APIs don't support this to begin with.

**Comment by yanivshaked** [comment]
Thank you for your quick response!

**Comment by yanivshaked** [comment]
Actually, it is possible, using the MessagingStyleInformation !
![image](https://user-images.githubusercontent.com/13107481/87545047-0e9dfc80-c6b0-11ea-822d-60a2a14eb9da.png)

**Comment by MaikuB** [comment]
Ah yes. Sorry thought you meant just taking the default style and having the image on left

**Comment by girish54321** [comment]
@yanivshaked this is maybe a custom view which they used in native app code.
