### ISSUE TITLE
Support String IDs instead of Integer IDs

### ISSUE THREAD

**Issue by lukaslihotzki** [MaikuB/flutter_local_notifications#771]
flutter_local_notifications currently supports Integer IDs only. In some applications, only String IDs are directly usable. To use Integer IDs (with flutter_local_notifications) in such a case, an extra persistent mapping has to be maintained or the strings have to be hashed which adds the risk of collisions.

iOS seems to only support String IDs natively. Integer IDs are converted to strings for [show](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L460) and [cancel](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L318).
Android supports Integer IDs ([notify](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#notify(int,%20android.app.Notification)) and [cancel](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#cancel(int))) or (String, Integer) tuple IDs alternatively ([notify](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#notify(java.lang.String,%20int,%20android.app.Notification)) and [cancel](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#cancel(java.lang.String,%20int))).
Scheduled notifications [use](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L264) PendingIntent in Android. There, a String could be passed with [putExtra](https://developer.android.com/reference/android/content/Intent#putExtra(java.lang.String,%20java.lang.String)) instead of using the Intent's requestCode.

Therefore, flutter_local_notifications possibly could support String IDs too. (I didn't check all features of flutter_local_notifications, there are so many.)

**Comment by lukaslihotzki** [comment]
This seems like a duplicate of #709. Sorry. However, as I explained, Android seems to support String IDs.

**Comment by MaikuB** [comment]
How would you propose the plugin add support for this? Bear in mind that it should still support apps that were using integer IDs somehow.

Those Android APIs you linked to still need an integer ID. The string is extra information that is completely optional.

> Scheduled notifications use PendingIntent in Android. There, a String could be passed with putExtra instead of using the Intent's requestCode.

What are you proposing to use for the request code here? How would the plugin process a request to cancel a scheduled notification?

**Comment by lukaslihotzki** [comment]
> How would you propose the plugin add support for this? Bear in mind that it should still support apps that were using integer IDs somehow.

Pass only string IDs to the native plugins. On Dart side, convert integers to strings for compatibility and provide new API for using string IDs directly.

> Those Android APIs you linked to still need an integer ID. The string is extra information that is completely optional.

With the API I linked, notifications are identified by both the string and the integer. If strings are unique for each notification, the integer ID can be always 0 for example.

> What are you proposing to use for the request code here? How would the plugin process a request to cancel a scheduled notification?

Ok, extras do not work because they are ignored by filterEquals. However, the action of the intent should work to distinguish multiple intents in cancelling. So, I propose to do `intent.setAction(stringId);` after https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L919 and `notificationIntent.setAction(stringId);` after https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L262. (stringId should be prefixed with the package name.)

> Edit: for what it's worth, the cross-platform notification plugins that I've seen for other frameworks only support integer IDs. I'm assuming that is due to some of the concerns I've covered

I will try to make a branch that supports String IDs for simple use cases in Android. iOS development is more difficult for me.

Are you generally interested in upstreaming String IDs if they work?

**Comment by MaikuB** [comment]
> Pass only string IDs to the native plugins. On Dart side, convert integers to strings for compatibility and provide new API for using string IDs directly.

I'd like to avoid new APIs if possible as it could have adverse effect on being able to maintain the plugin. There's extra overhead if adding support for a new feature would require adding two methods. Dart's lack of support for method overloading would likely require the methods to have different names that could be affect readability

> With the API I linked, notifications are identified by both the string and the integer. If strings are unique for each notification, the integer ID can be always 0 for example.

Yep I did read that are used together however it does mean the integer ID could be any arbitrary value so there's a element of "laziness" for lack of better description

> Ok, extras do not work because they are ignored by filterEquals. However, the action of the intent should work to distinguish multiple intents in cancelling. So, I propose to do intent.setAction(stringId); after https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L919 and notificationIntent.setAction(stringId); after https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L262. (stringId should be prefixed with the package name.)

I get why this is done though seems more like a workaround. As far as I know, when working with intents, the identifier is the kind of information that would have normally been specified as an extra as you've pointed out since it's information that isn't in the form of a URI to use [setData](https://developer.android.com/reference/android/content/Intent#setData(android.net.Uri)). Anyone (e.g. future maintainers/contributors) that looks at the Android implementation that sees an action would likely expect to see either data or an extra specified as well and could be thrown off by this as it goes against how it would normally be used.

> Are you generally interested in upstreaming String IDs if they work?

I'd be interested in taking a look if you get it working on all platforms to see how it would affect the maintainability of the plugin. It may not be merged in though based on some of the points I've raised. There hasn't been much of a demand for it and the notification plugins for other frameworks that have been around for longer have continued to work fine with supporting only integer IDs. Any solution that would be merged would also need to ensure that existing scheduled notifications would continue to appear as well. I don't know how much of the code you've seen but part of the plugin relies on saving notification details in JSON format to shared preferences. This is needed as rebooting the phone would remove all alarms used to display scheduled notifications. A successful reboot triggers a receiver that reads from shared preferences to reschedule the notifications.

I should mention that the current beta release supports macOS. That work is being done in the `time_zone_macos_support` so if you're going to do work on this, I would suggest doing based on that branch.

**Comment by lukaslihotzki** [comment]
> There's extra overhead if adding support for a new feature would require adding two methods.

Agreed. One option would be to take Objects as IDs in the API and call toString on that internally. Another option would be to deprecate the integer ID methods and not provide them for new features. Users can switch to the string ID methods easily by adding `.toString()`.

> Dart's lack of support for method overloading would likely require the methods to have different names that could be affect readability

Another option instead of new method names would be a new [FlutterLocalNotificationsPlugin](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin-class.html) class taking always string IDs instead of integer IDs, because probably users don't need to mix ID types, so method names could stay exactly the same. These classes could extend a shared base class for methods taking no IDs.

> Yep I did read that they are used together however it does mean the integer ID could be any arbitrary value so there's a element of "laziness" for lack of better description

Currently on Android, null is passed as a String effectively (by using the overloaded method that passes null implicitly), and the integer is specified by the user. With the new approach, the String would be specified by the user, and the integer 0 would be fixed. So it is all about the difference between null and 0.

> I get why this is done though seems more like a workaround. As far as I know, when working with intents, the identifier is the kind of information that would have normally been specified as an extra as you've pointed out since it's information that isn't in the form of a URI to use setData.

Yes, extras would be the best method to specify a notification ID. However, an Intent can't be selected for cancelling by its extras. So we have to use another property as a workaround. This is currently requestCode for integer IDs and could be the action for string IDs. Both should be confusing, because normally, constants are used for requestCode and action.

> other frameworks that have been around for longer have continued to work fine with supporting only integer IDs.

At least on Android itself, Google seems to have decided that it's useful to add the string ID method overloads in addition to pure integer IDs.

**Comment by MaikuB** [comment]
I get your point about the difference between null and 0 but the comparison between being made null and 0 is for between an optional and mandatory value. It would surprise me that Google added an overload as a sort of kludge as the Android APIs does at times seem to not be very well designed. As the plugin is a wrapper for the native APIs, it should IMO allow the users to specify the integer ID. However, it is an Android-specific parameter

Having had more of a discussion on this, bearing in the workarounds and suggestions that involve duplication in some form, I would say that I'm not looking to have support added in. The downsides and effort involved IMO far outweigh the benefits for something that I've seen very little demand for. As such, I'm closing this. Feel free to continue working on this on your fork and demonstrating how it would look though from what you've mentioned, it looks like you're only going to look at the Android.

**Comment by lukaslihotzki** [comment]
Using regex to replace the integer type of IDs with the string type works surprisingly well, at least for Android without scheduled notifications.

I needed to remove legacy code as described in this TODO: https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java#L29

The `intent.getIntExtra(FlutterLocalNotificationsPlugin.NOTIFICATION_ID, 0)` should always return 0 because the `NOTIFICATION_ID` extra seems to be never set, so I suppose the true-part of the `if` is the legacy code and should be removed, and the `else`-part (with gson) should be kept.

If that is correct, could you please remove the legacy code too? This would help me to keep the diff to your code small (and regex substitutions only).

As next steps, I will try to implement it for iOS as well and publish it on Github.

**Comment by MaikuB** [comment]
I removed the todo in the other branch but left the code. You don't see it referenced as I removed the code that caused the issue a while back but left it as a fix for the issue described there. 

I'm not sure how you're making changes but sounds like you may have downloaded the code manually rather than forking. In case you missed my previous reply, not intending to merge the changes though happy to take a look to see how you approached it
