### ISSUE TITLE
Scheduling a notification that replaces the last scheduled notification

### ISSUE THREAD

**Issue by Lachlan24** [MaikuB/flutter_local_notifications#794]
Hey, does anyone know if there is a solution to this problem. I went into more detail in this StackOverflow post.
https://stackoverflow.com/questions/63762098/flutter-how-to-a-schedule-a-notification-that-replaces-the-last-scheduled-notif
Thanks.

**Comment by DrobyshevAlex** [comment]
You could set **unique identifier** (ID) for your notifications.

**Comment by Lachlan24** [comment]
> You could set unique identifier (**ID**) for your notifications.
> 
> `flutterLocalNotificationsPlugin.schedule(ID, title, body....`

Hey, thanks for your reply but i think you might have misunderstood the issue i am having. My intention is to prevent spam on the users phone. I want each notification to replace the last if the user hasn't viewed the previous. Sort of like how if you use the same ID for a notification it overrides the previous notification that used that id. Although that doesn't work if your scheduling all the notifications at the same time as it prevents the previous schelude from ever alerting the user.

**Comment by MaikuB** [comment]
As your question relates to solving a problem specific to your app, you're unlikely to get answers here as it's really where developers going to report bugs. At a guess, you may need to come up with your custom solution that doesn't rely on this plugin and would schedule a single notification at time given part of the issue is you're scheduling them all in one. You may need to dig into the native APIs to achieve this
