### ISSUE TITLE
How to add multiple custom sounds for different notifications from single application.?

### ISSUE THREAD

**Issue by saravananmnm** [MaikuB/flutter_local_notifications#805]
is it possible to config multiple custom sounds.?

Am using flutter_local_notifications: ^1.4.4+4 version.

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.20.2 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Samsung Galaxy S10 (mobile) • 192.168.241.104:5555 • android-x86 • Android 10 (API 29)

• No issues found!

**Comment by Gowthamsubramaniam94** [comment]
@MaikuB Is it possible to add multiple custom notification sounds for each notification type?

**Comment by MaikuB** [comment]
Please try to make sure you go through the readme and API docs before asking a question as a lot of effort has gone into putting this together. If you go through to https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#%EF%B8%8F-android-setup, you should see that sounds are to tied to notification channels so if you really want different sounds then you need different channels. I'd suggest you read the official Android documentation further to understand how notifications work on Android since the plugin is a wrapper for those APIs
