### ISSUE TITLE
Local notification with Firebase push notification

### ISSUE THREAD

**Issue by AlexShniperson-INO** [MaikuB/flutter_local_notifications#811]
Hi

Is there a way to setup this library correctly with combination of Firebase push notifications?
It looks like push notifications doesn't work for iOS.
i read note somewhere at internet that some Native code should be writen, could you please route me what should i do for iOS?

**Comment by dgaedcke** [comment]
They should work together fine as long as you use the FCM package to request IOS permissions.  It's probably that request that informs FCM to being creating & serving it's own tokens.
If this is not working, please be specific as to the symptoms you see ... "doesn't work" is not specific enough for anyone to act.

**Comment by AlexShniperson-INO** [comment]
it looks like i found problem: 
swizzle should don't be disabled at iOS otherwise we should manually handle messages and send them into `UNUserNotificationCenter` as it described in [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/receive#swift:-ios-10)

so in my case `Runner/Info.plist` should contain
```
<key>FirebaseAppDelegateProxyEnabled</key>
<true/>
```

**Comment by AlexShniperson-INO** [comment]
I consider it necessary to leave a note stating that the order of initialization matters for iOS
```
import UIKit
import Flutter
import Firebase
import UserNotifications

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self
        }
        
        GeneratedPluginRegistrant.register(with: self)
        application.registerForRemoteNotifications()
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
```

**Comment by MaikuB** [comment]
> it looks like i found problem:
swizzle should don't be disabled at iOS otherwise we should manually handle messages and send them into UNUserNotificationCenter as it described in Firebase documentation

That doesn't sound right. Did you perhaps originally miss a step such as modifying the `AppDelegate` file that was mentioned in the readme

> I consider it necessary to leave a note stating that the order of initialization matters for iOS

I'm not sure what you mean here and how the code you showed relates to it. I have a sample app that I use for testing both firebase_messaging and this plugin together . [This](https://github.com/MaikuB/flutter_firebase_local_notifications_examples/blob/master/kotlin_swift/ios/Runner/AppDelegate.swift) is the link to it's associated `AppDelegate` file and method swizzling has been disabled. I've yet to hear of others having issues with after following the steps in the readme. If you do have more trouble with it then I would suggest you engage with the wider [community](https://flutter.dev/community) (e.g. Slack, Discord etc) where there are more people who can help look at your app

**Comment by MaikuB** [comment]
Closing this as I haven't seen any further response to point out that there's an issue with the plugin
