### ISSUE TITLE
Calling  _configureSelectNotificationSubject(); on initState executes selectNotificationSubject listener logic

### ISSUE THREAD

**Issue by joankabello** [MaikuB/flutter_local_notifications#845]
Hello @MaikuB ,

I am using your example code for testing right now and if the method  _configureSelectNotificationSubject(); is called in initState as you mentioned on README, everytime that i use Navigator.push to go on the HomePage will execute selectNotificationSubject listener logic.

This happens because the method _configureSelectNotificationSubject(); is called on initState, is there any other way how can i call this method ?

**Comment by MaikuB** [comment]
> is called in initState as you mentioned on README

Where did you see this in the readme as I don't see it?

Please note that at the end of the day, what's there in the example app is just example code. It's up to you to figure out how what changes need to be done for your context as everyone has their own approach to state management. This may even involve avoiding the use of streams/Rx. If you're going to persist with the approach then it's up to you to find out a location in your app where it's only called once.

Note I don't provide direct one on one support as everyone's context is different and it's not sustainable for me to do so. If you're going to continue to look for help, please look at using one of the sites at https://flutter.dev/community

**Comment by joankabello** [comment]
> > is called in initState as you mentioned on README
> 
> Where did you see this in the readme as I don't see it?
> 
> Please note that at the end of the day, what's there in the example app is just example code. It's up to you to figure out how what changes need to be done for your context as everyone has their own approach to state management. This may even involve avoiding the use of streams/Rx. If you're going to persist with the approach then it's up to you to find out a location in your app where it's only called once.
> 
> Note I don't provide direct one on one support as everyone's context is different and it's not sustainable for me to do so. If you're going to continue to look for help, please look at using one of the sites at https://flutter.dev/community

I think the problem is on the callback `onSelectNotification` becasue it is executed when you open the app, shouldn't this callback wait until i tap the notification and then add the event `selectNotificationSubject` or do any other logic ?

**Comment by ejulfaey** [comment]
I have same problem here

**Comment by MaikuB** [comment]
The callback is only being called once and is something you could verify. As mentioned earlier, you need to look at making changes that is suitable for your app. If you stick with what's in the example then you should look at seeing what is done is suitable and understand the APIs it uses e.g. https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html

**Comment by joankabello** [comment]
> The callback is only being called once and is something you could verify. As mentioned earlier, you need to look at making changes that is suitable for your app. If you stick with what's in the example then you should look at seeing what is done is suitable and understand the APIs it uses e.g. https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html

I am not using the example. 
Even if i don't add an event and just `print` smth the callback will be executed

**Comment by MaikuB** [comment]
> I am not using the example

You initially said

> I am using your example code for testing right now and if the method _configureSelectNotificationSubject(); 

so that's what I'm referring to. I can only assume you stuck with using BehaviorSubject that is probably global. If so, have you read the docs on how it behaves?

**Comment by Gowthamsubramaniam94** [comment]
@joankabello Did you got any solution on this?

**Comment by joankabello** [comment]
@Gowthamsubramaniam94 I did found any workaround into this. Even just adding a `print` inside the `onSelectNotification` will be called every time i open the app. I hope @MaikuB to investigate into it. Since i do the initialization only once on main() and i don't use rxdart at all

**Comment by MaikuB** [comment]
@joankabello I'm not going to investigate anything when the issue/steps hasn't been described clearly. Contradictory statements have been provided where at first say you follow the example app that by calling `_configureSelectNotificationSubject()` which makes calls to variables that use rxdart and then you say you don't use the example. Which is it? I had questions that weren't answered either.

If you have a bug to report then use bug report template with a link to a repository to reproduce the bug. If the callback was being called just on startup then this issue should be more widespread and reproducible with the example app in the repo, yet running it with a print statement does show that the print is called on startup. The onus is on you to provide detailed steps and code to reproduce this issue given a lot of OSS projects like this are done freely in spare time so it's not wise to go looking into issues without clear information

**Comment by joankabello** [comment]
The problem described is clear enough.
The callback onSelectNotification is executed when you kill your app and open it up again.

The statements are not contradictory at all. Since that you insisted that the problem was because i didn't used the rxDart Subject correctly i just tried with a print function to reproduce the issue.

Just because it works in your example app this doesn't mean that works properly.
It can be reproduced as a problem in your app very easily just by adding more routes.

Other users or people are reporting the issue as you can see.
Also by helping others with their coding problems using this package will not make you any harm. (Since i saw this behaviour in other issues too)

Thank you for your responses and time!

**Comment by MaikuB** [comment]
> The problem described is clear enough.
> The callback onSelectNotification is executed when you kill your app and open it up again.
> 
> The statements are not contradictory at all. Since that you insisted that the problem was because i didn't used the rxDart Subject correctly i just tried with a print function to reproduce the issue.

You say it's clear but you've really described two different issues in this thread. One is around taking the example app and using the `BehaviorSubject`  without understanding how it works and answering if you have read the docs. If you had, then should've seen the following

```
A special StreamController that captures the latest item that has been added to the controller, and emits that as the first item to any new listener.
```

This means your code being called twice is the expected behaviour. You say you added a print statement but don't provide any links to code etc to really indicate that you stopped using `BehaviorSubject`. For all I know, you are still putting the statement inside the logic for listening to the `BehaviorSubject`  (e.g. [here](https://github.com/MaikuB/flutter_local_notifications/blob/4111de48bdbedab632f65ac2892159ba1d22543a/flutter_local_notifications/example/lib/main.dart#L202)) when I had referred you to read the API docs so you understand how it works. Note this is different from the plugin invoking the callback twice. This goes back to my point on understanding the code/APIs being used in the example app and modifying it for your purposes.

The other problem you describe is around `onSelectNotification` being called when the app starts up, which you started with saying you _think_ that is the issue. If this problem exists then it would mean the callback is invoked soon after calling `initalize`. To date, I have yet to be provided a minimal app to reproduce this problem so the claim that there's an issue remains unsubstantiated.  You should be able to create a minimal app from scratch, add a reference to the plugin and call `initialize` to confirm this. If you had done so then you should see that the callback doesn't get invoked. There is even code on the Android side to ensure the callback is only invoked when a notification was tapped on at https://github.com/MaikuB/flutter_local_notifications/blob/4111de48bdbedab632f65ac2892159ba1d22543a/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L1148

> Just because it works in your example app this doesn't mean that works properly.
> It can be reproduced as a problem in your app very easily just by adding more routes.

That it doesn't work for your app doesn't mean there's an issue with the plugin either and I had referred you to look at how `BehaviorSubject`  works . The example app is mentioned as it basically a minimal app for using the plugin. This is to ensure developers do their own due diligence to isolate the problem to ensure it's not an issue with their code.

> Other users or people are reporting the issue as you can see.

Given the issue was originally on calling `_configureSelectNotificationSubject()`, the issue they're experiencing is more likely to do with sticking with using `BehaviorSubject`. Furthermore, I saw one issue opened recently with no reproduction steps/code where they claimed the callback wasn't invoked on startup.

> Also by helping others with their coding problems using this package will not make you any harm. (Since i saw this behaviour in other issues too)

I already ask in the top-level readme to limit issues to actual bugs or feature requests since this is done on spare time and is why I close issues if someone cannot provide enough information. If you are personally able to spend more time helping others then great but everyone's circumstances are different.

When one decides to engage with a maintainer, it's not unreasonable for a maintainer that uses their own free-time to look at issues for the community to respect that fact and provide as much info as requested to ensure that time is spent wisely. This is spare time that could be used on other things like resolving actual bugs or even spending time with family. This benefits both sides as it ensures problems are resolved more swiftly. Even having to reply takes up time. It is really up to the community to do their part to ensure OSS is maintainable as most is provided "as-is" and is stated as such in a lot of OSS licences. I'd suggest looking into sustainability with OSS such as watching [this](https://www.youtube.com/watch?v=Mm_RuObpeGo). There are lot of stories on OSS maintainers experiencing burnout as well.

Thus far, I'm being asked I look into things without providing concrete evidence when even the language you've used implies you're speculating and when I ask questions like what section of the readme you're referring to or if you looked into the API docs, they don't get answered.
