### ISSUE TITLE
zonedSchedule is awesome and handy but why deprecating the old schedule method

### ISSUE THREAD

**Issue by obadajasm** [MaikuB/flutter_local_notifications#846]
I'm working with an api that automatically handle the time zone difference after passing the required country code etc..
And another project which is directly related to a fixed city so there is no need to the whole time zone logic.

I admit after working with the new zonedSchedule it's super powerful and effective.
So if I want  to upgrade my package now I'm forced to write a logica that I won't use .

So why deprecating the old schedule method rather than having the two of them.🤔

**Comment by MaikuB** [comment]
That it works for your own context is not sufficient grounds for keeping both methods as there are others using the plugin and I also need to consider the additional burden it adds with regards to maintenance, which includes dealing with issues opened on the repo. Furthermore, the original method had issues on iOS when users ended up in different timezones (e.g. moved from one location to another). You could be in one timezone and say a notification should fire at 3PM, when you went to another location with a different timezone it would fire at 3PM relative to that location's timezone. This has been a longstanding issue along with dealing with daylight savings and the solution is to specify the timezone.

Note that a beta release that included these changes and a deprecation notice on the old method had been out for a number of months so this isn't something that just dropped out of nowhere. You should be able to watch the repo to be notified about releases in case you haven't done so already.

If you still prefer to use the old method because it's more convenient for you, the code is open-source and can be forked such that you can reference a fork in your own apps
