### ISSUE TITLE
Notification Sound Doesn't Play on MIUI 11.0.1 

### ISSUE THREAD

**Issue by irufano** [MaikuB/flutter_local_notifications#852]
Is there a way to force allow sound without allow manual on setting notif in app on MIUI 11.0.1 especially for e.g. Xiaomi, Huawei device ?

**Comment by MaikuB** [comment]
Not something that can be done as far as I know. From what I've gathered, those manufacturers customised their Android implementation such that it deviates from the standard behaviour

**Comment by sm2017** [comment]
@MaikuB Do you found any solution? By default **allow sound** is off for my application, but for **[Telegram](https://github.com/DrKLO/Telegram)** it on, so I think  there must be a way

**Comment by MaikuB** [comment]
If you do some research then you should find that this a common problem/limitation and not specific to the plugin e.g. https://threema.ch/en/faq/notification_channels_xiaomi. Given the issue is on customised Android implementations, there are no standard Android APIs that can be used to programatically enable this and the API docs are available for to check at https://developer.android.com/reference. Regarding the Telegram, the bigger companies have likely applied to get their application exempt to provide a smoother experience. You can try talking to the device manufacturers but I'm guessing you'd have to be working for a well-known company to be able to have app exempt from the standard restrictions

**Comment by sm2017** [comment]
@MaikuB thank you very much
