### ISSUE TITLE
ScheduledNotificationReceiver java.lang.NullPointerException

### ISSUE THREAD

**Issue by leonardocustodio** [MaikuB/flutter_local_notifications#867]
I'm having this following issue on crashlytics, It happens on very few devices.
I can't reproduce it on the devices that I have, neither the simulator.

Anyone has an idea of what could be happening?

```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
```

Best regards,
Leonardo

**Comment by MaikuB** [comment]
Have you checked to make sure all of the release build configuration has been done correctly? In that PR that you just commented on, I've also mentioned that there have been at least one known case where apps weren't awaiting the initialisation. This can lead to random occurrences in trying to show a notification using the default icon before the details of the default icon has been saved. That may explain why you have problems reproducing this and is something you'll need to check in your application's codebase. Otherwise, I'll need a minimal app that follows what you do in your own application

**Comment by leonardocustodio** [comment]
Hmm after your comment I may have found something. I will test it out and get back to you.
Thank you @MaikuB

**Comment by MaikuB** [comment]
Turning on this rule should help find issues like this https://dart-lang.github.io/linter/lints/unawaited_futures.html. Note though that it won't help fix notifications that have already been scheduled unless the user has run the app again to have the default icon saved to shared preferences. The details of the icon to use is fetched just before the notification should be shown

**Comment by MaikuB** [comment]
@leonardocustodio any updates?

**Comment by leonardocustodio** [comment]
Sorry it took a while. I was waiting to see if it would pop any new crashes on crashlytics. And looks like it did not, only the devices that were crashing before. I will make an update to "reset" their configuration.

Thanks a lot @MaikuB you were right ;)
Best regards,
