### ISSUE TITLE
Dismiss FCM notification

### ISSUE THREAD

**Issue by swapnens** [MaikuB/flutter_local_notifications#897]
**Describe the bug**

I want to receive an FCM notification and throw a local notification based on this. I try to cancel the fcm notification but it does not work.
**To Reproduce**

1. Receive a fcm notification.
2. In the onBackgroundMessage callback, try to cancel this notification.
3. Notice that the notification is still in the notification tray.

**Comment by MaikuB** [comment]
Fcm notifications aren't related to this notifications generated by this plugin. If you need to cancel a fcm notification then you'll need to look at their docs to see if it's supported. This issue is likely related as they say they use an id of 0 https://github.com/firebase/quickstart-android/issues/744. Have you tried cancelling a notification with an id of 0? If that doesn't work because a tag is used as well then you'll need to write your own custom code with platform channels that so that the id and tag are passed to https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#cancel(java.lang.String,%20int)

**Comment by MaikuB** [comment]
Closing due to lack of further response. If you still have issues with this then you'll need to look into how those SDKs work and likely need to write your own code to handle cancelling the push notifications

**Comment by Manuito83** [comment]
I've looking at this and it is indeed possible and easy to create a MethodChannel and just cancel notifications via either

`notificationManager.cancelAll()`

or 

`notificationManager.cancel(<TAG>, id)`, being the id always 0 for FCM

**Comment by KirillArtemenko** [comment]
> I've looking at this and it is indeed possible and easy to create a MethodChannel and just cancel notifications via either
> `notificationManager.cancel(<TAG>, id)`, being the id always 0 for FCM

The Eraser plugin can close notifications by <TAG>, see here: https://pub.dev/packages/eraser
