### ISSUE TITLE
There is no sound in Android

### ISSUE THREAD

**Issue by misici234** [MaikuB/flutter_local_notifications#929]
**Describe the bug**
There is no sound in Android

**To Reproduce**

1. Run "Plugin example app" on Android emulator
2. Click on "Show plain notification with payload"
3. The notification is displayed but there is no sound

**Expected behavior**
Expected to hear default sound as soon as notification is displayed. This problem doesn't exist in iOS. As far as I remember, sound worked on both Android and iOS in   flutter_local_notifications: ^1.4.4+4

**Sample code to reproduce the problem**
Just test the example project in Android.

**Comment by MaikuB** [comment]
There haven't been any changes relating to this to cause this issue. You might be running into a weird issue on your development environment. I had a similar issue in the past where my emulator would stop playing notification sounds within the same app session and then the issue persisted. It hasn't happened since I got a new Macbook and the sounds always played on a real Android device.

Not something I can help with here and it's possible you may continue to run into the same issue with your emulators as I never I figured out why emulators decided to "break" on my old Macbook. If you have a real device, then you may need to use that as part of your development if your problem continues to persist

**Comment by liri2006** [comment]
@MaikuB I have the same issue. I've tried on emulator and on two different real devices. Result is the same - example app shows notification, but does not play any sound.

**Comment by misici234** [comment]
@MaikuB I tested on a physical device and I agree. There was a sound from the device. Also, notification icon on the emulator appeared as a small, miserable, gray circle. However, on the device, it looked like a real icon.
