### ISSUE TITLE
Navigation error when clicking back from screen

### ISSUE THREAD

**Issue by soanpr123** [MaikuB/flutter_local_notifications#961]
I have two screens A and B. When I press the notification, I switch to screen B. But when I press the back button from screen B to screen A, the error is like video. Can you help me.

Code  screen A
```
 @override
  void initState() {
    super.initState();
    localnotifiManager.getApplaucher().then((value) => {if (value) {}});
    localnotifiManager.setOnNotificationReceive(onNotificationReceive);
    localnotifiManager.setOnNotificationClick(onClick);
    }




```
    

```
 onClick(String payLoad) {

    print(payLoad);
    if (payLoad == "") {
      MyApp.navigatorKey.currentState
          .push(MaterialPageRoute(builder: (context) => Questionary()));
    }
  }
```

  Code when click back button in screen B  : 
  ```
 return WillPopScope(
      onWillPop: () {

        return showDialog(
          context: context,
          builder: (_) => Stilmulation(
            title: "Questionnaire Reminder",
            description: "Do you want to answer questionnaire now?",
            ButtonYes: (BuildContext context) {
              Navigator.pop(context);
              startBottomsheet(context);

            },
            ButtonNo: (BuildContext context) {
             Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(
                  builder: (BuildContext context) => Dashboard()), (
                  Route<dynamic>route) => `false);`
            },
          ),
        );
      },
      child:...
```

https://user-images.githubusercontent.com/44558413/103337899-41e21580-4aaf-11eb-8340-37e13b36e8e1.mp4

**Comment by soanpr123** [comment]
https://user-images.githubusercontent.com/44558413/103337796-00516a80-4aaf-11eb-8cc1-bf7eba7e8ba4.mp4

**Comment by MaikuB** [comment]
It's not even clear what your issue is and it looks as though you got general issues in your applications where dialogs appear too often on other pages before even a local notification is shown. This is likely something you need to debug to find out as debugging each person's app isn't something I do as it wouldn't be sustainable for me to do so given I only work on the plugin in my spare time. If you need more help with your app, I'd suggest reaching out to wider [community](https://flutter.dev/community) by visiting places like Slack and Stack Overflow
