### ISSUE TITLE
Large Icon not visible in android Oreo 

### ISSUE THREAD

**Issue by niteesh1215** [MaikuB/flutter_local_notifications#976]
The large icon works fine on emulator running android 10, however when I try it on my phone having android version oreo, the icon doesn't appear instead a black square appears. 

AndroidNotificationDetails(
        medicationChannelId,
        'Reminder notifications',
        'other reminders',
        groupKey: groupKey,
        //setAsGroupSummary: true,
        icon: '@drawable/ic_stat_name',
        sound: RawResourceAndroidNotificationSound('notification'),
        color: Colors.green,
        largeIcon: DrawableResourceAndroidBitmap('ic_launcher_foreground'),
        enableLights: true,
        ledColor: const Color.fromARGB(255, 255, 0, 0),
        ledOnMs: 1000,
        ledOffMs: 500);

**Comment by MaikuB** [comment]
There isn't any specific to different Android versions. If you're running on an Android device and you're doing so in release mode then make sure you've gone through the readme to do all of the release build configuration. The issue you described sounds similar to what happens when that hasn't been done
