### ISSUE TITLE
missingplugin exception for method getTimeZoneName

### ISSUE THREAD

**Issue by Priyalkothari** [MaikuB/flutter_local_notifications#998]
**Describe the bug**
Unhandled Exception: MissingPluginException(No implementation found for method getTimeZoneName on channel dexterx.dev/flutter_local_notifications_example)
E/flutter ( 3036): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 3036): <asynchronous suspension>
E/flutter ( 3036): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 3036): #2      _configureLocalTimeZone (package:newproject/main.dart:148:46)
E/flutter ( 3036): #3      main (package:newproject/main.dart:207:9)
E/flutter ( 3036): <asynchronous suspension>
E/flutter ( 3036): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 3036): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 3036): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 3036): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 3036): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 3036): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 3036): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 3036): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

I am getting above error while I want to schedule notification using timezone. Why this error comes on app started. In main method I have called code to configure timezone as shown in ur example.

**Comment by MaikuB** [comment]
This is what was documented in the readme when it comes to scheduling notifications that requires timezone information

> The timezone package doesn't provide a way to obtain the current time zone on the device so developers will need to use platform channels (which is what the example app does) or use other packages that may be able to provide the information (e.g. flutter_native_timezone).

Your issue here you've copied code that makes use of platform channels, which requires code to be written in Java/Kotlin on for Android and objective C/Swift for iOS. You can read more this at https://flutter.dev/docs/development/platform-integration/platform-channels. So as written in the readme that I quoted above, you need to do that by copying the remaining code in the example app or make use of other plugins

Note: this isn't a bug with the plugin when you're copying code from the example app that isn't part of the plugin's API so be careful about copying code without understanding what's being used in

**Comment by Priyalkothari** [comment]
Thank u I have solved this error by adding flutter_native_timezone plugin
to my project.
